create table if not exists public.program_catalog_fi_staging (
  id bigint generated by default as identity primary key,
  source_name text not null,
  source_program_key text not null,
  institution_name text not null,
  institution_id uuid references catalog.institutions(id) on delete restrict,
  source_program_name text,
  title text not null,
  degree_level text not null default 'MASTER',
  school_faculty text,
  field_category text,
  city text,
  duration_years numeric,
  language_context text,
  official_program_url text not null,
  international_source_url text,
  source_as_of date,
  collection_status text not null default 'official_current_program_verified',
  verification_tier text not null default 'A',
  collected_at timestamptz not null default now(),
  unique(source_name,source_program_key),
  check (degree_level in ('BACHELOR','MASTER','DOCTORATE','PROFESSIONAL','DIPLOMA','CERTIFICATE')),
  check (duration_years is null or duration_years > 0),
  check (verification_tier in ('A','B','C'))
);
create index if not exists program_catalog_fi_staging_institution_idx on public.program_catalog_fi_staging(institution_id);
create index if not exists program_catalog_fi_staging_title_idx on public.program_catalog_fi_staging(lower(title));
create index if not exists program_catalog_fi_staging_tier_idx on public.program_catalog_fi_staging(verification_tier,degree_level);

create table if not exists public.program_occupation_fi_staging (
  program_catalog_id bigint not null references public.program_catalog_fi_staging(id) on delete cascade,
  canonical_career_id text not null,
  rule_version text not null,
  match_basis text not null default 'official_program_title',
  match_pattern text not null,
  review_status text not null default 'candidate',
  relation_type text,
  source_checked_at date,
  reviewer_note text,
  matched_at timestamptz not null default now(),
  reviewed_at timestamptz,
  primary key(program_catalog_id,canonical_career_id),
  check (review_status in ('candidate','approved','rejected')),
  check (relation_type is null or relation_type in ('direct','common_pathway','related'))
);
create index if not exists program_occupation_fi_staging_career_idx on public.program_occupation_fi_staging(canonical_career_id,review_status);

create table if not exists public.program_international_fi_staging (
  id bigint generated by default as identity primary key,
  program_catalog_id bigint not null unique references public.program_catalog_fi_staging(id) on delete cascade,
  international_students_eligible boolean,
  international_admission_status text not null default 'eligible_schedule_unknown',
  language_requirement_context text,
  visa_context text,
  intake_label text,
  intake_start_date date,
  application_deadline date,
  admission_source_url text,
  international_source_url text,
  source_as_of date,
  verification_status text not null default 'verified_general',
  rule_notes text,
  verified_at timestamptz,
  collected_at timestamptz not null default now(),
  check (international_admission_status in ('open','closed','not_yet_open','restricted','eligible_schedule_unknown','unknown')),
  check (verification_status in ('unverified','verified_general','verified_program','stale','rejected'))
);

alter table public.program_catalog_fi_staging enable row level security;
alter table public.program_occupation_fi_staging enable row level security;
alter table public.program_international_fi_staging enable row level security;
revoke all on public.program_catalog_fi_staging from public,anon,authenticated;
revoke all on public.program_occupation_fi_staging from public,anon,authenticated;
revoke all on public.program_international_fi_staging from public,anon,authenticated;
grant select,insert,update,delete on public.program_catalog_fi_staging to service_role;
grant select,insert,update,delete on public.program_occupation_fi_staging to service_role;
grant select,insert,update,delete on public.program_international_fi_staging to service_role;
grant usage,select on all sequences in schema public to service_role;
