-- France Cities Phase 4: exactly five verified decision metrics for each Tier A destination.

with t as (select id,slug from core.geographies where country_code='FR' and status='active' and metadata->>'publication_tier'='A'),
v(slug,amount,label,kind,code,url) as (values
 ('paris',2103778::numeric,'Paris commune','insee_commune','75056','https://www.insee.fr/fr/statistiques/2011101?geo=COM-75056'),
 ('paris-saclay',326692,'Communauté Paris-Saclay','insee_epci','200056232','https://www.insee.fr/fr/statistiques/2011101?geo=EPCI-200056232'),
 ('bordeaux',854334,'Bordeaux Métropole','insee_epci','243300316','https://www.insee.fr/fr/statistiques/2011101?geo=EPCI-243300316'),
 ('strasbourg',522596,'Eurométropole de Strasbourg','insee_epci','246700488','https://www.insee.fr/fr/statistiques/2011101?geo=EPCI-246700488'),
 ('grenoble',450608,'Grenoble-Alpes-Métropole','insee_epci','200040715','https://www.insee.fr/fr/statistiques/2011101?geo=EPCI-200040715'),
 ('aix-marseille',1939077,'Métropole d''Aix-Marseille-Provence','insee_epci','200054807','https://www.insee.fr/fr/statistiques/2011101?geo=EPCI-200054807'),
 ('nice',574287,'Métropole Nice Côte d''Azur','insee_epci','200030195','https://www.insee.fr/fr/statistiques/2011101?geo=EPCI-200030195'))
insert into public.report_metric_evidence_city(id,geography_id,scope_type,scope_id,metric_key,value,source_name,source_url,data_as_of,last_verified_at,confidence,evidence_kind,review_status,created_at,updated_at)
select gen_random_uuid(),t.id,'city',t.id::text,'city_population',jsonb_build_object('amount',v.amount,'geography',v.label,'geography_kind',v.kind,'official_code',v.code,'reference_year',2023,'geography_as_of','2026-01-01','scope_contract_preserved',true),'INSEE — Recensement de la population 2023',v.url,'2023-01-01',now(),'high','observed','verified',now(),now() from v join t using(slug)
on conflict(geography_id,metric_key) do update set value=excluded.value,source_name=excluded.source_name,source_url=excluded.source_url,data_as_of=excluded.data_as_of,last_verified_at=now(),confidence='high',evidence_kind='observed',review_status='verified',updated_at=now();

with t as (select id,slug from core.geographies where country_code='FR' and status='active' and metadata->>'publication_tier'='A'),
v(slug,lo,hi,kind,note,confidence,source,url,support_url) as (values
 ('paris',600::numeric,900::numeric,'psl_paris_student_budget','PSL current guidance covers housing, food and transportation; recreation and entertainment are excluded.','high','Université PSL — Graduate admissions FAQ','https://psl.eu/en/education/faq-graduate-admissions',null::text),
 ('paris-saclay',940,1350,'campus_france_planning_bracket','Campus France publishes €940 for the rest of France and €1,350 for Paris. Paris-Saclay is retained as this planning bracket rather than a fabricated local average.','low','Campus France — Preparing your budget','https://www.australie.campusfrance.org/preparing-your-budget','https://www.universite-paris-saclay.fr/en/vie-de-campus/accueil-des-publics-internationaux/venir-luniversite-paris-saclay/cost-living'),
 ('bordeaux',940,940,'campus_france_rest_france_planning_total','Campus France rest-of-France planning total; University of Bordeaux local housing examples are supporting context, not a spending survey.','medium','Campus France — Preparing your budget','https://www.australie.campusfrance.org/preparing-your-budget','https://www.u-bordeaux.fr/en/international/come-to-bordeaux/international-students/plan-ahead-for-your-stay-in-bordeaux'),
 ('strasbourg',940,940,'campus_france_rest_france_planning_total','Campus France rest-of-France planning total; University of Strasbourg publishes local cost components but no synthetic monthly total.','medium','Campus France — Preparing your budget','https://www.australie.campusfrance.org/preparing-your-budget','https://international-welcome.unistra.fr/funding-your-mobility-in-strasbourg/budgeting/'),
 ('grenoble',700,1300,'uga_component_derived_planning_range','Rounded planning range derived from current UGA housing, food, transport, bank-charge and other-expense guidance; not a survey average.','medium','Université Grenoble Alpes — Student budget','https://etudiant.univ-grenoble-alpes.fr/en/daily/managing-your-budget/student-budget/installation-costs/installation-costs-1368398.kjsp','https://etudiant.univ-grenoble-alpes.fr/en/daily/managing-your-budget/student-budget/everyday-expenses/'),
 ('aix-marseille',836,1156,'amu_habitual_month_budget','AMU publishes habitual-month totals of €836 in CROUS residence and €1,156 in private accommodation and recommends at least €1,100.','high','Aix-Marseille Université — International degree students','https://www.univ-amu.fr/en/etudiants-internationaux/etudiants-internationaux-formation-diplomante',null),
 ('nice',940,1350,'campus_france_large_city_planning_bracket','Campus France national planning bracket retained because no current university-wide Nice total was verified; not a local market survey.','low','Campus France — Preparing your budget','https://www.australie.campusfrance.org/preparing-your-budget','https://univ-cotedazur.fr/'))
insert into public.report_metric_evidence_city(id,geography_id,scope_type,scope_id,metric_key,value,source_name,source_url,data_as_of,last_verified_at,confidence,evidence_kind,review_status,created_at,updated_at)
select gen_random_uuid(),t.id,'city',t.id::text,'student_living_cost_monthly_range',jsonb_build_object('low',v.lo,'high',v.hi,'period','month','currency','EUR','reference_kind',v.kind,'note',v.note,'supporting_source_url',v.support_url,'indicative',true,'methodology_varies_by_destination',true,'not_cost_ranking',true),v.source,v.url,'2026-08-10',now(),v.confidence,'observed','verified',now(),now() from v join t using(slug)
on conflict(geography_id,metric_key) do update set value=excluded.value,source_name=excluded.source_name,source_url=excluded.source_url,data_as_of=excluded.data_as_of,last_verified_at=now(),confidence=excluded.confidence,evidence_kind='observed',review_status='verified',updated_at=now();

with t as (select id,slug from core.geographies where country_code='FR' and status='active' and metadata->>'publication_tier'='A'),
v(slug,amount,period,kind,eligibility,effective_from,source,url) as (values
 ('paris',401.30::numeric,'year','imagine_r_student','Student in Île-de-France; product eligibility applies',null::date,'Île-de-France Mobilités — Forfait imagine R Étudiant','https://www.iledefrance-mobilites.fr/titres-et-tarifs/detail/forfait-imagine-r-etudiant'),
 ('paris-saclay',401.30,'year','imagine_r_student','Student in Île-de-France; product eligibility applies',null::date,'Île-de-France Mobilités — Forfait imagine R Étudiant','https://www.iledefrance-mobilites.fr/titres-et-tarifs/detail/forfait-imagine-r-etudiant'),
 ('bordeaux',21.40,'month','tbm_pass_jeune','Pass Jeune for ages 11–27',null::date,'TBM — Pass Jeune','https://www.infotbm.com/fr/tarifs/pass-jeune.html'),
 ('strasbourg',28,'month','cts_18_25','Full youth fare for ages 18–25; solidarity reductions may apply',null::date,'CTS Strasbourg — Full-fare subscription','https://www.cts-strasbourg.eu/en/buy/our-tickets/regular-tickets/full-price-subscription/'),
 ('grenoble',19,'30_days','m_reso_18_25_studies','Ages 18–25 in studies; proof of enrolment required','2026-09-01'::date,'M réso — 18–25 Études','https://www.reso-m.fr/_tarifs/1296/67-abonnement-18-25-ans-etudes.htm?UTB_RESET=1'),
 ('aix-marseille',45,'month','amu_student_budget_transport','AMU indicative monthly transport pass; operator/product conditions vary',null::date,'Aix-Marseille Université — International degree students','https://www.univ-amu.fr/en/etudiants-internationaux/etudiants-internationaux-formation-diplomante'),
 ('nice',22.50,'month','lignes_azur_student_youth','Under 26; a student/apprentice 26+ product is also published at the same monthly fare',null::date,'Lignes d’Azur — Youth subscriptions','https://www.lignesdazur.com/en/youth-subscriptions-26-years-old'))
insert into public.report_metric_evidence_city(id,geography_id,scope_type,scope_id,metric_key,value,source_name,source_url,data_as_of,last_verified_at,confidence,evidence_kind,review_status,created_at,updated_at)
select gen_random_uuid(),t.id,'city',t.id::text,'student_transport_reference',jsonb_build_object('amount',v.amount,'period',v.period,'currency','EUR','reference_kind',v.kind,'eligibility',v.eligibility,'effective_from',v.effective_from,'eligibility_or_enrolment_conditions_apply',true,'source_native_period',true,'not_monthly_normalized',true),v.source,v.url,coalesce(v.effective_from,'2026-08-10'::date),now(),'high','observed','verified',now(),now() from v join t using(slug)
on conflict(geography_id,metric_key) do update set value=excluded.value,source_name=excluded.source_name,source_url=excluded.source_url,data_as_of=excluded.data_as_of,last_verified_at=now(),confidence='high',evidence_kind='observed',review_status='verified',updated_at=now();

insert into public.report_metric_evidence_city(id,geography_id,scope_type,scope_id,metric_key,value,source_name,source_url,data_as_of,last_verified_at,confidence,evidence_kind,review_status,created_at,updated_at)
select gen_random_uuid(),g.id,'city',g.id::text,'student_work_hours_year',jsonb_build_object('hours',964,'period','year','normal_work_share',0.60,'national_rule',true,'differentiates_cities',false,'exception','Algerian nationals: working time is limited to 50% of normal working hours in France','note','Foreign students are authorised to work 964 hours per year; employment is supplementary income and is not intended to cover all study expenses.'),'France-Visas — Student','https://www.france-visas.gouv.fr/en/etudiant','2026-08-10',now(),'high','observed','verified',now(),now()
from core.geographies g where g.country_code='FR' and g.status='active' and g.metadata->>'publication_tier'='A'
on conflict(geography_id,metric_key) do update set value=excluded.value,source_name=excluded.source_name,source_url=excluded.source_url,data_as_of=excluded.data_as_of,last_verified_at=now(),confidence='high',evidence_kind='observed',review_status='verified',updated_at=now();

with t as (select id,slug from core.geographies where country_code='FR' and status='active' and metadata->>'publication_tier'='A'),
v(slug,services,public_sector,industry,construction,agriculture,url) as (values
 ('paris',69.7::numeric,23.4::numeric,3.7::numeric,3.2::numeric,0.1::numeric,'https://www.insee.fr/fr/statistiques/2011101?geo=COM-75056'),
 ('paris-saclay',59.1,24.5,10.0,6.3,0.1,'https://www.insee.fr/fr/statistiques/2011101?geo=EPCI-200056232'),
 ('bordeaux',53.6,32.0,7.9,6.1,0.4,'https://www.insee.fr/fr/statistiques/2011101?geo=EPCI-243300316'),
 ('strasbourg',54.7,31.8,8.2,5.1,0.2,'https://www.insee.fr/fr/statistiques/2011101?geo=EPCI-246700488'),
 ('grenoble',47.5,33.9,13.0,5.5,0.2,'https://www.insee.fr/fr/statistiques/2011101?geo=EPCI-200040715'),
 ('aix-marseille',51.1,33.2,9.1,6.1,0.5,'https://www.insee.fr/fr/statistiques/2011101?geo=EPCI-200054807'),
 ('nice',53.9,32.3,5.7,7.8,0.4,'https://www.insee.fr/fr/statistiques/2011101?geo=EPCI-200030195'))
insert into public.report_metric_evidence_city(id,geography_id,scope_type,scope_id,metric_key,value,source_name,source_url,data_as_of,last_verified_at,confidence,evidence_kind,review_status,created_at,updated_at)
select gen_random_uuid(),t.id,'city',t.id::text,'employment_focus_sectors',jsonb_build_object('sectors',jsonb_build_array(jsonb_build_object('name','Commerce, transport and diverse services','share_percent',v.services),jsonb_build_object('name','Public administration, education, health and social work','share_percent',v.public_sector),jsonb_build_object('name','Industry','share_percent',v.industry),jsonb_build_object('name','Construction','share_percent',v.construction),jsonb_build_object('name','Agriculture','share_percent',v.agriculture)),'basis','INSEE RP2023 employment by activity sector at the Phase 2 population geography','reference_year',2023,'indicative',true,'not_shortage_ranking',true,'not_job_guarantee',true),'INSEE — RP2023 employment by activity sector',v.url,'2023-01-01',now(),'high','observed','verified',now(),now() from v join t using(slug)
on conflict(geography_id,metric_key) do update set value=excluded.value,source_name=excluded.source_name,source_url=excluded.source_url,data_as_of=excluded.data_as_of,last_verified_at=now(),confidence='high',evidence_kind='observed',review_status='verified',updated_at=now();

do $$ begin
 if (select count(*) from public.report_metric_evidence_city m join core.geographies g on g.id=m.geography_id where g.country_code='FR' and g.metadata->>'publication_tier'='A' and m.review_status='verified' and m.metric_key in ('city_population','student_living_cost_monthly_range','student_transport_reference','student_work_hours_year','employment_focus_sectors'))<>35 then raise exception 'FR Phase 4 expected exactly 35 verified core metric rows'; end if;
 if exists(select 1 from public.city_programme_directory_fr_v1) then raise exception 'FR city programme directory must remain empty'; end if;
end $$;