-- UAE Cities Phase 4: five source-aware decision-context metric families for each of four Tier A Cities.
-- Metric presence does not imply a numeric value is safely comparable. Emirate-wide values are never substituted for City-locality values.

with selected as (
  select id,slug,name from core.geographies
  where country_code='AE' and metadata->>'publication_tier'='A' and metadata->>'normalization_batch'='ae_city_geography_v1'
), metric_rows(slug,metric_key,value,source_name,source_url,data_as_of,confidence,evidence_kind) as (values
  ('abu-dhabi','city_population',jsonb_build_object('amount',null,'availability_status','not_published_at_verified_city_scope','geography','Abu Dhabi City locality','city_specific',true,'emirate_substitution_prohibited',true,'ranking_safe',false,'note','No common verified City-locality population series was identified for this release. Abu Dhabi emirate population must not be presented as Abu Dhabi City population.'),'Abu Dhabi City Municipality — official City scope','https://www.dmt.gov.ae/en/adm/About-Abu-Dhabi-City-Municipality/About-Us','2026-08-12','high','observed'),
  ('sharjah','city_population',jsonb_build_object('amount',null,'availability_status','not_published_at_verified_city_scope','geography','Sharjah City locality','city_specific',true,'emirate_substitution_prohibited',true,'ranking_safe',false,'note','Sharjah emirate population is not substituted for Sharjah City population.'),'Sharjah City Municipality — official City scope','https://portal.shjmun.gov.ae/en/AboutSharjahMunicipality/Pages/About-Sharjah.aspx','2026-08-12','high','observed'),
  ('al-ain','city_population',jsonb_build_object('amount',null,'availability_status','not_published_at_verified_city_scope','geography','Al Ain City locality','city_specific',true,'emirate_substitution_prohibited',true,'ranking_safe',false,'note','No verified release-safe City-locality population value is used. Abu Dhabi emirate totals are not substituted for Al Ain City.'),'Al Ain City Municipality — official City scope','https://www.dmt.gov.ae/en/aam/About-Al-Ain-Municipality/About-Us','2026-08-12','high','observed'),
  ('dubai','city_population',jsonb_build_object('amount',null,'availability_status','not_published_at_verified_city_scope','geography','Dubai City locality','city_specific',true,'emirate_substitution_prohibited',true,'ranking_safe',false,'note','Official Dubai statistical figures often use emirate-wide scope. This release does not relabel an emirate total as Dubai City population.'),'Dubai Municipality — official City authority','https://www.dm.gov.ae/about-dubai-municipality/about-dubai-municipality/','2026-08-12','high','observed'),

  ('abu-dhabi','student_living_cost_monthly_range',jsonb_build_object('low',735,'high',1470,'currency','USD','period','month','reference_kind','nyuad_graduate_on_campus_housing','full_budget',false,'city_specific',true,'ranking_safe',false,'note','NYU Abu Dhabi graduate housing monthly rates, from shared two-bedroom to two-bedroom per student. Accommodation only, not a full student budget.'),'NYU Abu Dhabi — Graduate housing rates','https://nyuad.nyu.edu/en/campus-life/housing-and-accommodation/residences/graduate/cost.html','2026-08-12','high','observed'),
  ('sharjah','student_living_cost_monthly_range',jsonb_build_object('low',null,'high',null,'currency','AED','period','regular_semester','reference_kind','aus_residential_hall_semester_reference','source_low',7000,'source_high',15000,'full_budget',false,'city_specific',true,'ranking_safe',false,'note','AUS 2026–2027 residential hall fees are published per semester, not per month. The source-native AED 7,000–15,000 semester range is retained without inventing a monthly conversion.'),'American University of Sharjah — Residential Halls Fees 2026–2027','https://www.aus.edu/node/14617','2026-03-16','high','observed'),
  ('al-ain','student_living_cost_monthly_range',jsonb_build_object('low',null,'high',null,'currency','AED','period','month','availability_status','not_published_on_verified_release_source','reference_kind','no_release_safe_numeric_reference','full_budget',false,'city_specific',true,'ranking_safe',false,'note','No current official Al Ain student monthly living-cost figure was used for this release; no substitute city or emirate estimate is inferred.'),'United Arab Emirates University — Al Ain campus','https://www.uaeu.ac.ae/en/about/contact_us.shtml','2026-08-12','medium','observed'),
  ('dubai','student_living_cost_monthly_range',jsonb_build_object('low',2363,'high',3200,'currency','AED','period','month','reference_kind','eau_on_campus_accommodation','full_budget',false,'city_specific',true,'ranking_safe',false,'note','Emirates Aviation University 2025–2026 on-campus accommodation monthly rates. Accommodation only, not a full student budget.'),'Emirates Aviation University — Campus accommodation','https://www.eau.ac.ae/campus/','2026-08-12','high','observed'),

  ('abu-dhabi','student_transport_reference',jsonb_build_object('amount',500,'currency','AED','period','1_year','reference_kind','hafilat_student_permit','student_specific',true,'city_specific',true,'source_native_period',true,'note','Annual student permit; unlimited trips within the city and suburbs in Abu Dhabi, Al Ain and Al Dhafra under published Hafilat conditions.'),'Abu Dhabi Mobility — Hafilat Student Permit','https://admobility.gov.ae/en/pb-bus-service/hafilat-personalized-passes','2026-08-12','high','observed'),
  ('sharjah','student_transport_reference',jsonb_build_object('amount',225,'currency','AED','period','30_days','reference_kind','sayer_subscription_card','student_specific',false,'city_specific',true,'source_native_period',true,'note','Sharjah Public Transport Sayer subscription card with unlimited travel for 30 days. This is a general subscription reference, not a student-only fare.'),'Sharjah Roads and Transport Authority — Sayer Card','https://www.srta.gov.ae/en-us/Transport-Sector/Sayer-Card.html','2026-08-12','high','observed'),
  ('al-ain','student_transport_reference',jsonb_build_object('amount',500,'currency','AED','period','1_year','reference_kind','hafilat_student_permit','student_specific',true,'city_specific',true,'source_native_period',true,'note','Annual student permit; unlimited trips within the city and suburbs in Abu Dhabi, Al Ain and Al Dhafra under published Hafilat conditions.'),'Abu Dhabi Mobility — Hafilat Student Permit','https://admobility.gov.ae/en/pb-bus-service/hafilat-personalized-passes','2026-08-12','high','observed'),
  ('dubai','student_transport_reference',jsonb_build_object('amount',70,'amount_high',175,'currency','AED','period','30_days','reference_kind','nol_student_30_day_pass','student_specific',true,'city_specific',true,'source_native_period',true,'note','Published 30-day student pass range: AED 70 for one zone to AED 175 for all zones. Eligibility follows RTA student nol conditions.'),'Dubai Roads and Transport Authority — nol fares','https://www.rta.ae/wps/portal/rta/ae/public-transport/Nol-Fares?lang=en','2026-07-16','high','observed'),

  ('abu-dhabi','student_work_hours_week',jsonb_build_object('hours_normal_period',null,'period','week','national_rule',true,'city_specific',false,'fixed_weekly_limit_published',false,'permit_required',true,'permit_kind','training_and_work_permit_for_students','permit_duration_months',3,'note','UAE student employment is represented as a permit-based national rule. This source does not establish one universal weekly-hour cap for higher-education students, so no numeric weekly limit is invented.'),'UAE Ministry of Human Resources and Emiratisation — Training and Work Permit for Students','https://mohre.gov.ae/en/services/training-and-work-permit-for-students-2022','2026-08-12','high','observed'),
  ('sharjah','student_work_hours_week',jsonb_build_object('hours_normal_period',null,'period','week','national_rule',true,'city_specific',false,'fixed_weekly_limit_published',false,'permit_required',true,'permit_kind','training_and_work_permit_for_students','permit_duration_months',3,'note','UAE student employment is permit-based national context; no City score or invented weekly cap.'),'UAE Ministry of Human Resources and Emiratisation — Training and Work Permit for Students','https://mohre.gov.ae/en/services/training-and-work-permit-for-students-2022','2026-08-12','high','observed'),
  ('al-ain','student_work_hours_week',jsonb_build_object('hours_normal_period',null,'period','week','national_rule',true,'city_specific',false,'fixed_weekly_limit_published',false,'permit_required',true,'permit_kind','training_and_work_permit_for_students','permit_duration_months',3,'note','UAE student employment is permit-based national context; no City score or invented weekly cap.'),'UAE Ministry of Human Resources and Emiratisation — Training and Work Permit for Students','https://mohre.gov.ae/en/services/training-and-work-permit-for-students-2022','2026-08-12','high','observed'),
  ('dubai','student_work_hours_week',jsonb_build_object('hours_normal_period',null,'period','week','national_rule',true,'city_specific',false,'fixed_weekly_limit_published',false,'permit_required',true,'permit_kind','training_and_work_permit_for_students','permit_duration_months',3,'note','UAE student employment is permit-based national context; no City score or invented weekly cap.'),'UAE Ministry of Human Resources and Emiratisation — Training and Work Permit for Students','https://mohre.gov.ae/en/services/training-and-work-permit-for-students-2022','2026-08-12','high','observed'),

  ('abu-dhabi','employment_focus_sectors',jsonb_build_object('basis','Abu Dhabi DED growth-sector framework','sectors',jsonb_build_array('Advanced manufacturing','Trade and logistics','ICT, advanced technology and space','Renewable energy','Tourism and hospitality','Financial services'),'indicative',true,'not_shortage_ranking',true,'not_job_guarantee',true),'Abu Dhabi Department of Economic Development — Growth Sectors','https://www.added.gov.ae/en/invest/growth-sectors','2026-07-24','high','observed'),
  ('sharjah','employment_focus_sectors',jsonb_build_object('basis','Sharjah Chamber 2025–2027 business-sector strategy and investment context','sectors',jsonb_build_array('Manufacturing','Logistics and supply chains','Technology and electronics','Tourism and creative economy','Healthcare and pharmaceuticals'),'indicative',true,'not_shortage_ranking',true,'not_job_guarantee',true),'Sharjah Chamber of Commerce and Industry — sector and investment priorities','https://sharjah.gov.ae/en/media-center/news/sharjah-chamber-vietnamese-trade-delegation-discuss-strengthening-economic-and-investment-cooperation/','2026-02-03','medium','observed'),
  ('al-ain','employment_focus_sectors',jsonb_build_object('basis','Abu Dhabi DED Al Ain industrial-location evidence','sectors',jsonb_build_array('Aerospace','Technology-based industries','Advanced manufacturing','Logistics'),'indicative',true,'not_shortage_ranking',true,'not_job_guarantee',true,'note','Nibras Al Ain and Al Ain industrial locations provide local economic context; this is not a shortage or hiring ranking.'),'Abu Dhabi Department of Economic Development — Industrial Parks / Nibras Al Ain','https://www.added.gov.ae/en/invest/growth-sectors/advanced-manufacturing/industrial-parks','2026-07-24','high','observed'),
  ('dubai','employment_focus_sectors',jsonb_build_object('basis','Dubai Department of Economy and Tourism current economy/tourism activity context','sectors',jsonb_build_array('Tourism and hospitality','Advanced manufacturing','Technology and digital business','Trade and logistics','Financial and business services'),'indicative',true,'not_shortage_ranking',true,'not_job_guarantee',true),'Dubai Department of Economy and Tourism — Economy and Tourism','https://www.dubaidet.gov.ae/en/','2026-07-07','medium','observed')
)
insert into public.report_metric_evidence_city(id,geography_id,scope_type,scope_id,metric_key,value,source_name,source_url,data_as_of,last_verified_at,confidence,evidence_kind,review_status,created_at,updated_at)
select md5('ae_city_phase4:'||s.id||':'||m.metric_key)::uuid,s.id,'city',s.id::text,m.metric_key,m.value,m.source_name,m.source_url,m.data_as_of::date,now(),m.confidence,m.evidence_kind,'verified',now(),now()
from metric_rows m join selected s using(slug)
on conflict(geography_id,metric_key) do update set
  value=excluded.value,source_name=excluded.source_name,source_url=excluded.source_url,data_as_of=excluded.data_as_of,
  last_verified_at=now(),confidence=excluded.confidence,evidence_kind=excluded.evidence_kind,review_status='verified',updated_at=now();

create or replace view public.city_metric_directory_ae_v1 with (security_invoker=true) as
select g.id city_id,g.slug city_slug,g.name city_name,r.metric_key,r.value,r.source_name,r.source_url,r.data_as_of,r.confidence,r.evidence_kind
from core.geographies g
join public.report_metric_evidence_city r on r.geography_id=g.id and r.scope_type='city' and r.review_status='verified'
where g.country_code='AE' and g.metadata->>'publication_tier'='A' and g.metadata->>'normalization_batch'='ae_city_geography_v1'
  and r.metric_key in ('city_population','student_living_cost_monthly_range','student_transport_reference','student_work_hours_week','employment_focus_sectors');

revoke all on public.city_metric_directory_ae_v1 from public,anon,authenticated;
grant select on public.city_metric_directory_ae_v1 to service_role;

do $$
declare metric_n integer; bad integer; deferred integer;
begin
  select count(*) into metric_n from public.city_metric_directory_ae_v1;
  if metric_n<>20 then raise exception 'AE Phase 4 expected 20 verified City metric rows, found %',metric_n; end if;

  select count(*) into bad from (
    select city_id,count(*) n from public.city_metric_directory_ae_v1 group by city_id having count(*)<>5
  ) x;
  if bad<>0 then raise exception 'Every AE Tier A City must have exactly five metric families'; end if;

  select count(*) into bad from public.city_metric_directory_ae_v1
  where metric_key='city_population' and (value->>'amount') is not null;
  if bad<>0 then raise exception 'AE Phase 4 must not substitute emirate population as City population'; end if;

  select count(*) into deferred from public.city_metric_directory_ae_v1 where city_slug in ('khor-fakkan','ajman','fujairah','ras-al-khaimah','umm-al-quwain');
  if deferred<>0 then raise exception 'AE Phase 4 deferred City leaked into metrics'; end if;
end $$;