-- CampCareer critical E2E fixture database.
-- IMPORTANT: run only against the dedicated campcareer-ci Supabase project.
-- This is NOT production migration history and must not be applied to production.
-- It exists only while production migration-history reconciliation is pending.

begin;

create table if not exists public.career_foundation_result_v1 (
  profile_key text,
  country_code text not null,
  canonical_occupation_id text not null,
  decision_ready boolean not null default false,
  score_ready boolean not null default false,
  publish_ready boolean not null default false,
  opportunity_score numeric,
  official_title text not null,
  snapshot_key text,
  primary key (country_code, canonical_occupation_id)
);

create table if not exists public.country_occupation_profiles (
  profile_key text primary key,
  country_code text not null,
  canonical_career_id text not null,
  official_title text not null,
  official_code_system text,
  official_code_version text,
  official_unit_group_code text,
  currency text,
  registration_required boolean not null default false,
  registration_authority text,
  registration_url text,
  publication_status text not null,
  source_checked_at date
);

create table if not exists public.country_occupation_metric_snapshots (
  id bigint generated by default as identity primary key,
  profile_key text not null,
  as_of_date date not null,
  employment_total numeric,
  median_weekly_earnings numeric,
  median_hourly_earnings numeric,
  annualised_median_salary numeric,
  all_occupations_median_weekly numeric,
  part_time_share_pct numeric,
  female_share_pct numeric,
  median_age numeric,
  average_full_time_hours numeric,
  vacancies_three_month_avg numeric,
  vacancy_period text,
  vacancy_yoy_pct numeric,
  employment_growth_5y_pct numeric,
  employment_growth_10y_pct numeric,
  shortage_component numeric,
  vacancy_intensity_component numeric,
  employer_diversity_component numeric,
  vacancy_trend_component numeric,
  entry_level_component numeric,
  salary_component numeric,
  growth_component numeric,
  visa_component numeric,
  entry_burden_component numeric,
  opportunity_score numeric,
  score_methodology_version text,
  score_status text,
  score_evidence jsonb default '{}'::jsonb,
  source_checked_at date
);

create table if not exists public.country_occupation_specialisations (
  id bigint generated by default as identity primary key,
  profile_key text not null,
  official_code text,
  official_title text,
  legacy_code_system text,
  legacy_code_version text,
  legacy_code text,
  shortage_rating numeric,
  visa_eligible boolean,
  included_in_rollup boolean not null default true,
  sort_order integer not null default 0
);

create table if not exists public.country_occupation_region_metrics (
  id bigint generated by default as identity primary key,
  profile_key text not null,
  region_code text not null,
  as_of_date date not null,
  shortage_rating numeric,
  vacancy_count numeric,
  source_url text
);

create table if not exists public.country_occupation_links (
  id bigint generated by default as identity primary key,
  profile_key text not null,
  link_type text not null,
  label text not null,
  url text not null,
  provider_type text,
  region_code text,
  sort_order integer not null default 0
);

create table if not exists public.country_occupation_program_links (
  id bigint generated by default as identity primary key,
  profile_key text not null,
  program_ref text not null,
  relation_type text not null
);

create table if not exists public.visa_pathways (
  id bigint generated by default as identity primary key,
  country_code text not null,
  country_name text,
  visa_name text not null,
  kind text not null,
  note text not null,
  authority text not null,
  source_url text not null,
  source_title text not null,
  last_verified_on date not null,
  display_order integer not null default 0
);

create table if not exists public.courses_au (
  id bigint primary key,
  institution_id text,
  course_code text,
  cricos_code text,
  title text,
  field_name text,
  broad_field text,
  narrow_field text,
  aqf_level integer,
  course_type text,
  duration_years numeric,
  tuition_fee_aud numeric,
  cricos_url text,
  qualifax_url text,
  official_course_url text,
  official_url_status text,
  official_url_checked_at timestamptz,
  cricos_status text,
  cricos_last_seen_at timestamptz,
  synced_at timestamptz,
  verified_city_ids text[],
  verified_city_slugs text[],
  verified_delivery_locations jsonb,
  location_source_resource text,
  location_source_last_modified timestamptz,
  location_verified_at timestamptz
);

create table if not exists public.colleges_au (
  institution_id text primary key,
  name text,
  state text,
  city text,
  website_url text
);

create table if not exists public.au_institution_identity_v1 (
  legacy_provider_id text primary key,
  institution_id text not null,
  institution_slug text not null,
  institution_name text not null,
  institution_kind text,
  ownership_type text
);

create table if not exists public.program_page_facts_au (
  id bigint generated by default as identity primary key,
  course_id bigint not null,
  field_key text not null,
  value jsonb,
  source_url text,
  review_status text,
  extracted_at timestamptz
);

create table if not exists public.institution_detail_v1 (
  institution_id text primary key,
  country_code text not null,
  slug text not null,
  canonical_name text not null,
  institution_kind text,
  ownership_type text,
  website_url text,
  status text not null,
  program_count integer,
  campus_count integer,
  city_count integer,
  city_names text[],
  cricos_provider_code text,
  cricos_source_url text,
  campus_locations jsonb default '[]'::jsonb,
  study_areas jsonb default '[]'::jsonb,
  programme_types jsonb default '[]'::jsonb,
  programme_preview jsonb default '[]'::jsonb,
  unique(country_code, slug)
);

create table if not exists public.institution_logo_v1 (
  institution_id text primary key,
  country_code text,
  slug text,
  logo_url text,
  logo_asset_type text,
  logo_source_url text
);

create table if not exists public.report_metric_evidence_country (
  id text primary key,
  scope_type text not null,
  scope_id text not null,
  metric_key text not null,
  value jsonb,
  source_name text not null,
  source_url text not null,
  data_as_of date,
  last_verified_at date,
  confidence text not null,
  review_status text not null
);

alter table public.career_foundation_result_v1 enable row level security;
alter table public.country_occupation_profiles enable row level security;
alter table public.country_occupation_metric_snapshots enable row level security;
alter table public.country_occupation_specialisations enable row level security;
alter table public.country_occupation_region_metrics enable row level security;
alter table public.country_occupation_links enable row level security;
alter table public.country_occupation_program_links enable row level security;
alter table public.visa_pathways enable row level security;
alter table public.courses_au enable row level security;
alter table public.colleges_au enable row level security;
alter table public.au_institution_identity_v1 enable row level security;
alter table public.program_page_facts_au enable row level security;
alter table public.institution_detail_v1 enable row level security;
alter table public.institution_logo_v1 enable row level security;
alter table public.report_metric_evidence_country enable row level security;

revoke all on all tables in schema public from anon, authenticated;
grant select on public.career_foundation_result_v1, public.visa_pathways to anon;
grant select on public.career_foundation_result_v1,
  public.country_occupation_profiles,
  public.country_occupation_metric_snapshots,
  public.country_occupation_specialisations,
  public.country_occupation_region_metrics,
  public.country_occupation_links,
  public.country_occupation_program_links,
  public.visa_pathways,
  public.courses_au,
  public.colleges_au,
  public.au_institution_identity_v1,
  public.program_page_facts_au,
  public.institution_detail_v1,
  public.institution_logo_v1,
  public.report_metric_evidence_country
to service_role;

drop policy if exists "ci public foundation read" on public.career_foundation_result_v1;
create policy "ci public foundation read" on public.career_foundation_result_v1
  for select to anon using (true);
drop policy if exists "ci public visa read" on public.visa_pathways;
create policy "ci public visa read" on public.visa_pathways
  for select to anon using (true);

do $$
declare t text;
begin
  foreach t in array array[
    'country_occupation_profiles','country_occupation_metric_snapshots',
    'country_occupation_specialisations','country_occupation_region_metrics',
    'country_occupation_links','country_occupation_program_links','courses_au',
    'colleges_au','au_institution_identity_v1','program_page_facts_au',
    'institution_detail_v1','institution_logo_v1','report_metric_evidence_country'
  ]
  loop
    execute format('drop policy if exists %I on public.%I', 'ci service role read', t);
    execute format('create policy %I on public.%I for select to service_role using (true)', 'ci service role read', t);
  end loop;
end $$;

truncate table
  public.country_occupation_metric_snapshots,
  public.country_occupation_specialisations,
  public.country_occupation_region_metrics,
  public.country_occupation_links,
  public.country_occupation_program_links,
  public.visa_pathways,
  public.program_page_facts_au
restart identity;

delete from public.career_foundation_result_v1;
delete from public.country_occupation_profiles;
delete from public.courses_au;
delete from public.colleges_au;
delete from public.au_institution_identity_v1;
delete from public.institution_detail_v1;
delete from public.institution_logo_v1;
delete from public.report_metric_evidence_country;

insert into public.country_occupation_profiles
(profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at)
values
('AU:registered-nurse','AU','registered-nurse','Registered Nurse','OSCA','2024 v1.0','2654','AUD',true,'Nursing and Midwifery Board of Australia','https://www.nursingmidwiferyboard.gov.au/Registration-Standards.aspx','decision_ready','2026-08-06'),
('AU:software-developer','AU','software-developer','Software Engineer','OSCA','2024 v1.0','2733','AUD',false,'Australian Computer Society (ACS) — migration skills assessment only; no statutory national occupational registration','https://www.acs.org.au/msa.html','profile_ready','2026-08-08');

insert into public.country_occupation_metric_snapshots
(profile_key,as_of_date,employment_total,median_weekly_earnings,median_hourly_earnings,annualised_median_salary,all_occupations_median_weekly,part_time_share_pct,female_share_pct,median_age,average_full_time_hours,vacancies_three_month_avg,vacancy_period,vacancy_yoy_pct,employment_growth_5y_pct,employment_growth_10y_pct,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at)
values
('AU:registered-nurse','2026-05-01',366200,2192,57,113984,1852,44,86,38,41,7287.66667,'2026-05-01',21.99,13.67,26.08,20,15,5,10,13,8,10,10,2,93,'career-opportunity-v1','provisional','{"ci_fixture":true}'::jsonb,'2026-08-06'),
('AU:software-developer','2026-05-01',null,2537,null,131924,1852,null,null,null,null,3392,'2026-05-01',-9.86,15.69,26.67,0,0,5,0,13,10,5,10,4,37,'career-opportunity-v1','provisional','{"ci_fixture":true}'::jsonb,'2026-08-15');

insert into public.country_occupation_specialisations
(profile_key,official_code,official_title,legacy_code_system,legacy_code_version,legacy_code,shortage_rating,visa_eligible,included_in_rollup,sort_order)
values
('AU:registered-nurse','265432','Registered Nurse (Acute Care)','ANZSCO','2013 v1.3','254415',5,true,true,1),
('AU:software-developer','273333','Software Engineer',null,null,null,null,true,true,1);

insert into public.country_occupation_region_metrics
(profile_key,region_code,as_of_date,shortage_rating,vacancy_count,source_url)
values
('AU:registered-nurse','NSW','2026-05-01',3,2535.66667,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),
('AU:registered-nurse','QLD','2026-05-01',3,1449.33333,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),
('AU:registered-nurse','VIC','2026-05-01',3,1619.33333,'https://www.jobsandskills.gov.au/data/internet-vacancy-index');

insert into public.country_occupation_links
(profile_key,link_type,label,url,provider_type,region_code,sort_order)
values
('AU:registered-nurse','source','JSA — Registered Nurses profile','https://www.jobsandskills.gov.au/data/occupation-and-industry-profiles/occupations-anzsco/2544-registered-nurses','official_labour_market',null,1),
('AU:registered-nurse','source','NMBA — Registration standards','https://www.nursingmidwiferyboard.gov.au/Registration-Standards.aspx','official_regulator',null,2),
('AU:registered-nurse','job_search','SEEK — Registered Nurse jobs','https://www.seek.com.au/registered-nurse-jobs','private_job_board',null,1),
('AU:software-developer','source','JSA — Software and Applications Programmers profile','https://www.jobsandskills.gov.au/data/occupation-and-industry-profiles/occupations/2613-software-and-applications-programmers','official_labour_market',null,1),
('AU:software-developer','job_search','SEEK — Software Engineer jobs','https://www.seek.com.au/software-engineer-jobs','private_job_board',null,1);

insert into public.visa_pathways
(country_code,country_name,visa_name,kind,note,authority,source_url,source_title,last_verified_on,display_order)
values
('AU','Australia','Student visa','Study','Full-time study at a registered Australian institution.','Department of Home Affairs','https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500','Student visa (subclass 500)','2026-08-06',10),
('AU','Australia','Temporary Graduate','Work','Temporary work rights after completing eligible Australian study.','Department of Home Affairs','https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-graduate-485','Temporary Graduate visa (subclass 485)','2026-08-06',20);

insert into public.colleges_au (institution_id,name,state,city,website_url)
values ('macquarie-university','Macquarie University','NSW','Sydney','https://www.mq.edu.au/');

insert into public.au_institution_identity_v1
(legacy_provider_id,institution_id,institution_slug,institution_name,institution_kind,ownership_type)
values ('macquarie-university','380ba0e6-c9bb-488c-9213-0b76f98dd5c6','macquarie-university','Macquarie University',null,null);

insert into public.courses_au
(id,institution_id,course_code,cricos_code,title,field_name,broad_field,narrow_field,aqf_level,course_type,duration_years,tuition_fee_aud,cricos_url,qualifax_url,official_course_url,official_url_status,official_url_checked_at,cricos_status,cricos_last_seen_at,synced_at,verified_city_ids,verified_city_slugs,verified_delivery_locations,location_source_resource,location_source_last_modified,location_verified_at)
values
(1,'macquarie-university','001357G','00002J','Bachelor of Arts','Liberal Arts and Sciences, General Studies and Humanities.','09 - Society and Culture','0903 - Studies in Human Society',7,'Bachelor Degree',3,43206,'https://cricos.education.gov.au/Course/CourseDetails.aspx?CourseCode=001357G',null,'https://www.mq.edu.au/study/find-a-course/courses/bachelor-of-arts','verified','2026-07-30T09:59:02Z','active','2026-07-18T10:03:54Z','2026-05-30T20:34:45Z',array['efe4c42f-cd2b-09bd-3834-624a53d2f9fb'],array['sydney'],
'[{"state":"NSW","cityId":"efe4c42f-cd2b-09bd-3834-624a53d2f9fb","source":"CRICOS Course Locations","campusId":"88da93be-8302-49f8-a598-229b31b31189","citySlug":"sydney","locality":"Macquarie University","postcode":"2109","courseCode":"001357G","locationName":"Macquarie University Wallumattagal Campus at North Ryde","providerCode":"00002J","canonicalCity":"Sydney"}]'::jsonb,
'CRICOS Course Locations','2026-08-04T08:04:04Z','2026-08-07T18:53:59Z');

insert into public.institution_detail_v1
(institution_id,country_code,slug,canonical_name,institution_kind,ownership_type,website_url,status,program_count,campus_count,city_count,city_names,cricos_provider_code,cricos_source_url,campus_locations,study_areas,programme_types,programme_preview)
values
('380ba0e6-c9bb-488c-9213-0b76f98dd5c6','AU','macquarie-university','Macquarie University',null,null,'https://www.mq.edu.au/','active',1,1,1,array['Sydney'],'00002J','https://cricos.education.gov.au/institution/InstitutionSearch.aspx',
'[{"id":"88da93be-8302-49f8-a598-229b31b31189","city":"Sydney","name":"Macquarie University Wallumattagal Campus at North Ryde","region":"NSW","address":"Wallumattagal Campus","citySlug":"sydney","postalCode":"2109","officialUrl":null,"reportedCity":"Sydney"}]'::jsonb,
'[{"name":"Liberal Arts and Sciences, General Studies and Humanities.","count":1}]'::jsonb,
'[{"name":"Bachelor Degree","count":1}]'::jsonb,
'[{"id":"ci-mq-ba","title":"Bachelor of Arts","fieldName":"Liberal Arts and Sciences, General Studies and Humanities.","programmeType":"Bachelor Degree","legacyProgramId":1}]'::jsonb),
('90a9efcf-85d7-4847-8845-a87c1f762d1b','AU','australian-catholic-university','Australian Catholic University',null,null,'https://www.acu.edu.au/','active',1,1,1,array['Sydney'],'00004G','https://cricos.education.gov.au/institution/InstitutionSearch.aspx',
'[{"id":"ci-acu-sydney","city":"Sydney","name":"Australian Catholic University-North Sydney Campus","region":"NSW","address":"40 Edward St","citySlug":"sydney","postalCode":"2060","officialUrl":null,"reportedCity":"Sydney"}]'::jsonb,
'[{"name":"Education, General.","count":1}]'::jsonb,
'[{"name":"Bachelor Degree","count":1}]'::jsonb,
'[]'::jsonb);

insert into public.report_metric_evidence_country
(id,scope_type,scope_id,metric_key,value,source_name,source_url,data_as_of,last_verified_at,confidence,review_status)
values
('ci-au-salary','country','AU','average_annual_salary','95000'::jsonb,'Australian Bureau of Statistics','https://www.abs.gov.au/','2026-01-01','2026-08-01','high','verified');

commit;
