import assert from "node:assert/strict"
import test from "node:test"

import { buildIrelandWaveABackfillSql } from "../scripts/generate-ie-wave-a-foundation-backfill"

const sql = buildIrelandWaveABackfillSql()

test("Ireland Wave A backfill is transactional and non-activating", () => {
  assert.match(sql, /^-- Generated by scripts\/generate-ie-wave-a-foundation-backfill\.ts\n/)
  assert.match(sql, /\nbegin;\n/)
  assert.match(sql, /\ncommit;$/)
  assert.equal((sql.match(/insert into public\.career_foundation_profiles/g) ?? []).length, 8)
  assert.equal((sql.match(/'EUR',false,/g) ?? []).length, 8)
  assert.doesNotMatch(sql, /'EUR',true,/)
  assert.match(sql, /Ireland Wave A backfill unexpectedly activated decision_ready/)
  assert.match(sql, /expected 8 foundation profiles/)
  assert.match(sql, /expected 6 evidence-complete score rows/)
  assert.match(sql, /unexpectedly produced % publish-ready rows/)
})

test("Ireland Wave A backfill creates one mapping and one nine-component snapshot per Career", () => {
  assert.equal((sql.match(/insert into public\.career_occupation_mappings/g) ?? []).length, 8)
  assert.equal((sql.match(/insert into public\.career_opportunity_score_snapshots/g) ?? []).length, 8)
  assert.equal((sql.match(/insert into public\.career_score_components/g) ?? []).length, 8)

  for (const careerId of [
    "software-developer",
    "cybersecurity-analyst",
    "data-engineer",
    "civil-engineer",
    "construction-manager",
    "accountant",
    "architect",
    "radiographer",
  ]) {
    assert.match(sql, new RegExp(`IE:${careerId}:2026-09-12:wave-a-v1`))
  }
})

test("incomplete Ireland Careers are persisted as unavailable evidence, not zero-filled components", () => {
  for (const careerId of ["accountant", "architect", "radiographer"]) {
    assert.match(sql, new RegExp(`IE:${careerId}.*unavailable`, "s"))
  }

  assert.match(sql, /insufficient_industry_coverage/)
  assert.match(sql, /no_evidence_found/)
})

test("generator retains explicit lineage tables", () => {
  assert.match(sql, /career_raw_observations/)
  assert.match(sql, /career_normalized_metrics/)
  assert.match(sql, /career_normalized_metric_inputs/)
  assert.match(sql, /career_score_component_metric_inputs/)
  assert.match(sql, /career_score_component_raw_inputs/)
})


test("generated backfill contains nine component rows per Ireland Career and no invalid numeric literals", () => {
  const blocks = [...sql.matchAll(
    /insert into public\.career_score_components[\s\S]*?values\n([\s\S]*?)\non conflict \(snapshot_key,component_key\)/g,
  )]
  assert.equal(blocks.length, 8)

  for (const block of blocks) {
    const rows = block[1].split("\n").filter((line) => line.trim().startsWith("("))
    assert.equal(rows.length, 9)
  }

  assert.doesNotMatch(sql, /\bundefined\b/)
  assert.doesNotMatch(sql, /\bNaN\b/)
})

test("generated backfill uses formula v4 and never changes the app public score allowlist", () => {
  assert.match(sql, /career-opportunity-v4-foundation/)
  assert.doesNotMatch(sql, /SCORE_READY_CAREER_PROFILES/)
})


test("generated raw observations preserve source reference periods instead of using the review date as the statistic period", () => {
  assert.match(sql, /employment_momentum','2019-2024'/)
  assert.match(sql, /projected_growth','2021-2035'/)
  assert.match(sql, /relative_salary','2022'/)
  assert.match(sql, /vacancy_intensity','2024-2025'/)
})
