import { readFileSync } from "node:fs"
import { pathToFileURL } from "node:url"

type Source = {
  authority: string
  title: string
  url: string
  sourceType: "official_primary" | "official_service" | "government_aggregator"
  note?: string
}

type Mapping = {
  taxonomy: string
  code: string
  title: string
  relation: "exact" | "broader" | "narrower" | "composite" | "proxy"
  quality: "high" | "medium" | "low"
  source: string
  verifiedOn: string
  rationale: string
}

type ComponentStatus = "normalized" | "pending"

type Component = {
  status: ComponentStatus
  normalizedValue?: number
  normalizedUnit?: string
  scoreValue?: number
  maxScore?: number
  directness?: "direct" | "proxy"
  evidenceStatus?: string
  source?: string
  sourceRefs?: string[]
  proxyReason?: string
  reason?: string
  derivedHhiUpperBound?: number
}

type Career = {
  careerId: string
  profileKey: string
  mapping: Mapping
  labourMarket: Record<string, unknown>
  projection: Record<string, unknown>
  components: Record<string, Component>
}

type WaveAData = {
  version: string
  checkedOn: string
  sources: Record<string, Source>
  benchmarks: Record<string, unknown>
  careers: Career[]
  readiness: {
    careers: Record<string, {
      careerDecisionReady: boolean
      pendingPublicComponents: string[]
      visaContextReady: boolean
    }>
  }
}

const FORMULA_VERSION = "career-opportunity-v4-foundation"
const REQUIRED_COMPONENTS = [
  "shortage_signal",
  "vacancy_intensity",
  "industry_diversity",
  "employment_momentum",
  "entry_accessibility",
  "relative_salary",
  "projected_growth",
  "visa_accessibility",
  "entry_burden",
] as const

const PUBLIC_COMPONENTS = REQUIRED_COMPONENTS.filter((key) => key !== "visa_accessibility")

const data = JSON.parse(
  readFileSync("data/curated/ie/wave-a-career-foundation.json", "utf8"),
) as WaveAData

const q = (value: string) => `'${value.replaceAll("'", "''")}'`
const nullableText = (value: string | undefined) => value ? q(value) : "null"
const jsonb = (value: unknown) => `${q(JSON.stringify(value))}::jsonb`
const textArray = (values: string[]) => `array[${values.map(q).join(",")}]`
const slug = (value: string) => value.replaceAll("_", "-")

const sourceKeysFor = (component: Component) =>
  component.sourceRefs?.length
    ? component.sourceRefs
    : component.source
      ? [component.source]
      : []

const componentEvidenceStatus = (componentKey: string, component: Component) => {
  if (component.status === "normalized") {
    return component.evidenceStatus
      ?? (component.directness === "direct" ? "direct_verified" : "proxy")
  }
  if (componentKey === "industry_diversity") return "insufficient_industry_coverage"
  return "no_evidence_found"
}

const componentSourceType = (component: Component) => {
  const key = sourceKeysFor(component)[0]
  return key ? data.sources[key]?.sourceType ?? "government_aggregator" : "government_aggregator"
}

const componentMappingQuality = (component: Component, career: Career) =>
  component.directness === "direct" ? career.mapping.quality : "medium"

const componentQuality = (component: Component) =>
  component.status === "normalized" && component.directness === "direct" ? "high" : "medium"

const componentConfidence = (component: Component) => {
  if (component.status !== "normalized") return 0.6
  return component.directness === "direct" ? 0.95 : 0.8
}

const recordValue = (value: unknown): Record<string, unknown> =>
  value != null && typeof value === "object" && !Array.isArray(value)
    ? value as Record<string, unknown>
    : { value }

const rawPayloadFor = (
  career: Career,
  componentKey: string,
  component: Component,
): Record<string, unknown> => {
  switch (componentKey) {
    case "employment_momentum":
      return {
        labourMarket: career.labourMarket,
        nationalBenchmark: data.benchmarks.recentEmploymentGrowthAnnualAvgPct,
      }
    case "projected_growth":
      return {
        projection: career.projection,
        nationalBenchmark: data.benchmarks.projectedNationalGrowthAnnualPct,
      }
    case "relative_salary":
      return recordValue(data.benchmarks.pay)
    case "industry_diversity":
      return {
        derivedHhiUpperBound: component.derivedHhiUpperBound ?? null,
        normalization: data.benchmarks.industryDiversity,
      }
    default:
      return {
        componentKey,
        normalizedValue: component.normalizedValue ?? null,
        scoreValue: component.scoreValue ?? null,
        reason: component.reason ?? null,
        proxyReason: component.proxyReason ?? null,
      }
  }
}

export function buildIrelandWaveABackfillSql() {
const sql: string[] = []
sql.push("-- Generated by scripts/generate-ie-wave-a-foundation-backfill.ts")
sql.push("-- Staging backfill only: this file must not activate public Ireland scores.")
sql.push("begin;")
sql.push("")

for (const [sourceKey, source] of Object.entries(data.sources)) {
  sql.push(`insert into public.career_official_sources (source_key,authority,title,url,source_type,last_verified_on,notes) values (${q(sourceKey)},${q(source.authority)},${q(source.title)},${q(source.url)},${q(source.sourceType)},${q(data.checkedOn)},${nullableText(source.note)}) on conflict (source_key) do update set authority=excluded.authority,title=excluded.title,url=excluded.url,source_type=excluded.source_type,last_verified_on=excluded.last_verified_on,notes=excluded.notes;`)
}
sql.push("")

for (const career of data.careers) {
  const readiness = data.readiness.careers[career.careerId]
  const publicComplete = PUBLIC_COMPONENTS.every(
    (key) => career.components[key]?.status === "normalized",
  )
  if (publicComplete !== readiness.careerDecisionReady) {
    throw new Error(`Readiness drift for ${career.careerId}`)
  }

  const decisionReason = publicComplete
    ? "Wave A evidence backfill is complete, but public activation remains intentionally disabled until the separate review/switch step."
    : `Wave A evidence remains incomplete: ${readiness.pendingPublicComponents.join(", ")}.`

  // Backfill is deliberately non-activating. A later reviewed switch changes
  // decision_ready and the application-level public readiness allowlist.
  sql.push(`insert into public.career_foundation_profiles (profile_key,country_code,canonical_occupation_id,currency,decision_ready,decision_readiness_reason,source_checked_on) values (${q(career.profileKey)},'IE',${q(career.careerId)},'EUR',false,${q(decisionReason)},${q(data.checkedOn)}) on conflict (profile_key) do update set country_code=excluded.country_code,canonical_occupation_id=excluded.canonical_occupation_id,currency=excluded.currency,decision_ready=false,decision_readiness_reason=excluded.decision_readiness_reason,source_checked_on=excluded.source_checked_on,updated_at=now();`)

  const mappingKey = `${career.profileKey}:SOC2010:${career.mapping.code}`
  const mappingSource = data.sources[career.mapping.source]
  if (!mappingSource) throw new Error(`Unknown mapping source ${career.mapping.source}`)
  sql.push(`insert into public.career_occupation_mappings (mapping_key,profile_key,canonical_occupation_id,country_code,official_taxonomy,official_taxonomy_version,official_code,official_title,mapping_relation,mapping_quality,rationale,source_key,source_url,verified_on,is_primary) values (${q(mappingKey)},${q(career.profileKey)},${q(career.careerId)},'IE',${q(career.mapping.taxonomy)},'2010',${q(career.mapping.code)},${q(career.mapping.title)},${q(career.mapping.relation)},${q(career.mapping.quality)},${q(career.mapping.rationale)},${q(career.mapping.source)},${q(mappingSource.url)},${q(career.mapping.verifiedOn)},true) on conflict (mapping_key) do update set official_title=excluded.official_title,mapping_relation=excluded.mapping_relation,mapping_quality=excluded.mapping_quality,rationale=excluded.rationale,source_key=excluded.source_key,source_url=excluded.source_url,verified_on=excluded.verified_on,is_primary=true;`)

  const snapshotKey = `${career.profileKey}:${data.checkedOn}:wave-a-v1`
  const componentRows: string[] = []
  const metricInputRows: string[] = []
  const rawInputRows: string[] = []

  for (const componentKey of REQUIRED_COMPONENTS) {
    const component = career.components[componentKey]
    if (!component) throw new Error(`Missing ${career.careerId} ${componentKey}`)

    const sourceKeys = sourceKeysFor(component)
    if (!sourceKeys.length) throw new Error(`Missing source for ${career.careerId} ${componentKey}`)

    const observationKeys: string[] = []
    for (const [index, sourceKey] of sourceKeys.entries()) {
      const source = data.sources[sourceKey]
      if (!source) throw new Error(`Unknown source ${sourceKey}`)
      const observationKey = `ie-${slug(career.careerId)}-${slug(componentKey)}-${index + 1}`
      observationKeys.push(observationKey)

      const available = component.status === "normalized"
      const rawValue = available
        ? jsonb({ ...rawPayloadFor(career, componentKey, component), sourceKey })
        : "null"
      const reason = available ? "null" : q(component.reason ?? "Evidence is not yet sufficient for normalization.")
      const directness = component.directness ?? "proxy"
      const proxyReason = directness === "proxy"
        ? q(component.proxyReason ?? component.reason ?? "Current evidence is broader than the canonical Career scope.")
        : "null"

      sql.push(`insert into public.career_raw_observations (observation_key,profile_key,mapping_key,source_key,metric_key,reference_period,as_of_date,raw_value,unit,availability,reason,directness,mapping_quality,proxy_reason,source_type,quality,confidence,last_verified_on,explanation) values (${q(observationKey)},${q(career.profileKey)},${q(mappingKey)},${q(sourceKey)},${q(componentKey)},${q(data.checkedOn)},${q(data.checkedOn)},${rawValue},${nullableText(component.normalizedUnit)},${q(available ? "available" : "unavailable")},${reason},${q(directness)},${q(componentMappingQuality(component, career))},${proxyReason},${q(source.sourceType)},${q(componentQuality(component))},${componentConfidence(component)},${q(data.checkedOn)},${q(component.reason ?? component.proxyReason ?? `Wave A ${componentKey} evidence.`)}) on conflict (observation_key) do update set source_key=excluded.source_key,metric_key=excluded.metric_key,reference_period=excluded.reference_period,as_of_date=excluded.as_of_date,raw_value=excluded.raw_value,unit=excluded.unit,availability=excluded.availability,reason=excluded.reason,directness=excluded.directness,mapping_quality=excluded.mapping_quality,proxy_reason=excluded.proxy_reason,source_type=excluded.source_type,quality=excluded.quality,confidence=excluded.confidence,last_verified_on=excluded.last_verified_on,explanation=excluded.explanation;`)
    }

    const metricKey = `${career.profileKey}:${componentKey}:wave-a-v1`
    const available = component.status === "normalized"
    if (available && (component.normalizedValue == null || !Number.isFinite(component.normalizedValue))) {
      throw new Error(`Normalized component missing value: ${career.careerId} ${componentKey}`)
    }
    const normalizedValue = available ? String(component.normalizedValue) : "null"
    const reason = available ? "null" : q(component.reason ?? "Evidence is not yet sufficient for normalization.")
    const directness = component.directness ?? "proxy"
    const proxyReason = directness === "proxy"
      ? q(component.proxyReason ?? component.reason ?? "Current evidence is broader than the canonical Career scope.")
      : "null"
    const sourceType = componentSourceType(component)
    const explanation = component.reason ?? component.proxyReason ?? `Wave A normalized ${componentKey}.`

    sql.push(`insert into public.career_normalized_metrics (normalized_metric_key,profile_key,metric_key,input_observation_refs,normalized_value,normalized_unit,formula_version,availability,reason,directness,mapping_quality,proxy_reason,source_type,quality,confidence,explanation) values (${q(metricKey)},${q(career.profileKey)},${q(componentKey)},${textArray(observationKeys)},${normalizedValue},${nullableText(component.normalizedUnit)},${q(FORMULA_VERSION)},${q(available ? "available" : "unavailable")},${reason},${q(directness)},${q(componentMappingQuality(component, career))},${proxyReason},${q(sourceType)},${q(componentQuality(component))},${componentConfidence(component)},${q(explanation)}) on conflict (normalized_metric_key) do update set input_observation_refs=excluded.input_observation_refs,normalized_value=excluded.normalized_value,normalized_unit=excluded.normalized_unit,formula_version=excluded.formula_version,availability=excluded.availability,reason=excluded.reason,directness=excluded.directness,mapping_quality=excluded.mapping_quality,proxy_reason=excluded.proxy_reason,source_type=excluded.source_type,quality=excluded.quality,confidence=excluded.confidence,explanation=excluded.explanation,calculated_at=now();`)

    for (const [index, observationKey] of observationKeys.entries()) {
      metricInputRows.push(`(${q(metricKey)},${q(observationKey)},${q(index === 0 ? "primary_evidence" : "persistence_evidence")},${q(componentKey === "vacancy_intensity" ? "fallback_evidence" : "input")})`)
      rawInputRows.push(`(${q(snapshotKey)},${q(componentKey)},${q(observationKey)},${q(index === 0 ? "primary_evidence" : "supporting_evidence")})`)
    }

    componentRows.push(`(${q(snapshotKey)},${q(career.profileKey)},${q(componentKey)},${textArray(observationKeys)},${textArray([metricKey])},${normalizedValue},${q(FORMULA_VERSION)},${q(available ? "available" : "unavailable")},${q(directness)},${q(componentMappingQuality(component, career))},${proxyReason},${q(sourceType)},${q(componentQuality(component))},${componentConfidence(component)},${q(explanation)},${reason},${q(componentEvidenceStatus(componentKey, component))})`)
  }

  sql.push(`insert into public.career_opportunity_score_snapshots (snapshot_key,profile_key,as_of_date,formula_version,required_component_keys,explanation) values (${q(snapshotKey)},${q(career.profileKey)},${q(data.checkedOn)},${q(FORMULA_VERSION)},${textArray([...REQUIRED_COMPONENTS])},${q("Ireland Wave A normalized evidence backfill. Public activation is intentionally handled in a separate reviewed switch.")}) on conflict (snapshot_key) do update set required_component_keys=excluded.required_component_keys,explanation=excluded.explanation;`)

  sql.push(`insert into public.career_score_components (snapshot_key,profile_key,component_key,raw_input_refs,normalized_metric_refs,normalized_value,formula_version,availability,directness,mapping_quality,proxy_reason,source_type,quality,confidence,explanation,reason,evidence_status) values\n${componentRows.join(",\n")}\non conflict (snapshot_key,component_key) do update set raw_input_refs=excluded.raw_input_refs,normalized_metric_refs=excluded.normalized_metric_refs,normalized_value=excluded.normalized_value,formula_version=excluded.formula_version,availability=excluded.availability,directness=excluded.directness,mapping_quality=excluded.mapping_quality,proxy_reason=excluded.proxy_reason,source_type=excluded.source_type,quality=excluded.quality,confidence=excluded.confidence,explanation=excluded.explanation,reason=excluded.reason,evidence_status=excluded.evidence_status,calculated_at=now();`)

  sql.push(`insert into public.career_normalized_metric_inputs (normalized_metric_key,observation_key,input_role,usage_type) values\n${metricInputRows.join(",\n")}\non conflict do nothing;`)
  sql.push(`insert into public.career_score_component_metric_inputs (snapshot_key,component_key,normalized_metric_key,input_role) select ${q(snapshotKey)},c.component_key,m.normalized_metric_key,'scored_metric' from public.career_score_components c join public.career_normalized_metrics m on m.profile_key=c.profile_key and m.normalized_metric_key=(c.normalized_metric_refs)[1] where c.snapshot_key=${q(snapshotKey)} on conflict do nothing;`)
  sql.push(`insert into public.career_score_component_raw_inputs (snapshot_key,component_key,observation_key,input_role) values\n${rawInputRows.join(",\n")}\non conflict do nothing;`)
  sql.push("")
}

sql.push("-- Safety assertion: this generated backfill must never activate Ireland foundation profiles.")
sql.push("do $$ begin if exists (select 1 from public.career_foundation_profiles where country_code='IE' and canonical_occupation_id in ('software-developer','cybersecurity-analyst','data-engineer','civil-engineer','construction-manager','accountant','architect','radiographer') and decision_ready=true) then raise exception 'Ireland Wave A backfill unexpectedly activated decision_ready'; end if; end $$;")
sql.push("commit;")

return sql.join("\n")
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  process.stdout.write(buildIrelandWaveABackfillSql())
}
