insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('JP:civil-engineer','JP','civil-engineer','土木技術者 — design/construction/other umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:mechanical-engineer','JP','mechanical-engineer','機械技術者 — development/manufacturing umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:electrical-engineer','JP','electrical-engineer','電気技術者 — development/manufacturing/facility umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:manufacturing-engineer','JP','manufacturing-engineer','生産技術者 — sector-specific manufacturing-engineering umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:industrial-engineer','JP','industrial-engineer','産業・生産システム改善技術者 — no standalone MHLW code','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:chemical-engineer','JP','chemical-engineer','化学技術者 — development/manufacturing umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:environmental-engineer','JP','environmental-engineer','環境技術者 — environmental/civil measurement umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:engineering-technician','JP','engineering-technician','工学技術補助者 — cross-discipline technical-support umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-10',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at) values
('JP:civil-engineer','2026-08-10',0,0,0,0,12,0,0,0,3,15,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','Civil Engineer spans MHLW 008-04 civil design, 008-05 civil construction management and 008-06 other civil engineering; no false single rollup is assigned.','entry_level_basis','Civil-engineering study and graduate engineering pathways provide structured entry, with practical project experience important.','qualification_note','The occupation is not universally licensed, although legally designated construction-site engineer appointments can require recognised qualifications or experience.','market_scope','No exact recurring canonical civil-engineer market series is normalised yet.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-10'),
('JP:mechanical-engineer','2026-08-10',0,0,0,0,12,0,0,0,3,15,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','Mechanical Engineer spans 006-03 mechanical development/design and 007-04 mechanical manufacturing engineering.','entry_level_basis','Mechanical-engineering degrees and graduate technical roles provide a structured route, with design and production experience valued.','qualification_note','No single personal licence is required across the full occupation.','market_scope','Development and manufacturing groups are not blended into a fabricated exact labour-market series.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-10'),
('JP:electrical-engineer','2026-08-10',0,0,0,0,12,0,0,0,2,14,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','Electrical Engineer spans 006-02 electrical/electronic development, 007-02 electrical/electronic manufacturing and facility engineering, and selected 007-03 electrical-construction engineering scope.','entry_level_basis','Electrical and electronic engineering study provides a structured professional entry route.','qualification_note','The occupation is not universally licensed, but specified electrical facilities require appointment of a qualified 電気主任技術者 and some construction responsibilities have separate statutory requirements.','market_scope','The distinct official groups are not merged into a fabricated exact employment or vacancy series.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-10'),
('JP:manufacturing-engineer','2026-08-10',0,0,0,0,12,0,0,0,3,15,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','Manufacturing engineering is sector-specific in the MHLW 007 family rather than one generic occupation, spanning production engineering for food, electrical/electronic, machinery, automotive, transport equipment, materials, chemicals and other manufacturing.','entry_level_basis','Mechanical, materials, electrical, chemical and related engineering study can lead into production/process engineering; eleven reviewed programmes are retained as related rather than direct.','qualification_note','No universal personal manufacturing-engineer licence covers the full canonical role.','market_scope','Sector-specific 007 data are not combined into one invented generic manufacturing-engineer market series.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-10'),
('JP:industrial-engineer','2026-08-10',0,0,0,0,12,0,0,0,3,15,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','Industrial Engineer has no standalone MHLW small-class code; process, productivity, quality and systems-improvement work is distributed across sector-specific manufacturing-engineering classifications.','entry_level_basis','Industrial, systems, operations and engineering study is relevant; the one reviewed Japanese industrial-engineering programme remains a direct academic pathway.','qualification_note','No universal personal industrial-engineer licence applies across the canonical scope.','market_scope','Sector-specific manufacturing classifications are retained as references only and not treated as an exact industrial-engineer market series.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-10'),
('JP:chemical-engineer','2026-08-10',0,0,0,0,12,0,0,0,3,15,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','Chemical Engineer spans 006-07 chemical-product development engineering and 007-08 chemical-product manufacturing engineering.','entry_level_basis','Chemical engineering and applied chemistry degrees provide structured entry, with process, plant and product-development experience relevant.','qualification_note','No single personal licence is required for every chemical-engineering role; plant, safety and legally designated duties can carry separate requirements.','market_scope','Development and manufacturing groups are not blended into a fabricated exact canonical market series.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-10'),
('JP:environmental-engineer','2026-08-10',0,0,0,0,12,0,0,0,3,15,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','Environmental Engineer has no standalone MHLW small-class code; environmental measurement/investigation can fall under 011-99 while environmental civil-infrastructure work can overlap 008-04 and 008-06.','entry_level_basis','Environmental, civil and related engineering study provides relevant entry pathways.','qualification_note','The canonical occupation is not universally licensed, although statutory measurements in specified workplaces must be performed by registered 作業環境測定士.','market_scope','Measurement and civil-engineering source groups are not merged into an invented exact environmental-engineer series.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-10'),
('JP:engineering-technician','2026-08-10',0,0,0,0,15,0,0,0,5,20,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','Japan does not provide one generic Engineering Technician small-class code matching the canonical cross-discipline role; technical drafting/support scopes such as 080-04 and 080-05 are retained only as references.','entry_level_basis','Technical colleges, vocational study and supervised engineering-support experience can provide practical entry without requiring a full professional-engineering role.','qualification_note','No universal personal engineering-technician licence covers the broad canonical occupation.','market_scope','Drafting and discipline-specific technician groups are not aggregated into a fabricated generic technician labour series.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-10')
on conflict (profile_key,as_of_date) do update set shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('JP:civil-engineer','008-04','土木設計技術者',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:civil-engineer','008-05','土木施工管理技術者',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:civil-engineer','008-06','土木技術者（設計・施工管理を除く）',null,null,false,3,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:mechanical-engineer','006-03','機械開発技術者',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:mechanical-engineer','007-04','機械製造技術者',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:electrical-engineer','006-02','電気・電子・電気通信開発技術者（通信ネットワークを除く）',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:electrical-engineer','007-02','電気・電子・電気通信製造技術者（通信ネットワーク・電気工事技術者を除く）',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:electrical-engineer','007-03','電気工事技術者 — professional engineering scope',null,null,false,3,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:manufacturing-engineer','007-01','食品製造技術者 — production engineering scope',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:manufacturing-engineer','007-02','電気・電子・電気通信製造技術者',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:manufacturing-engineer','007-04','機械製造技術者',null,null,false,3,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:manufacturing-engineer','007-05','自動車製造技術者',null,null,false,4,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:manufacturing-engineer','007-06','輸送用機器製造技術者（自動車を除く）',null,null,false,5,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:manufacturing-engineer','007-07','金属製錬・材料製造技術者',null,null,false,6,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:manufacturing-engineer','007-08','化学製品製造技術者',null,null,false,7,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:manufacturing-engineer','007-99','その他の製造技術者',null,null,false,8,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:industrial-engineer','007-02','製造工程・品質・工数改善 scope（電気・電子）',null,null,false,1,'https://www.hellowork.mhlw.go.jp/info/mhlw_job_dictionary_02.html','2026-08-10'),
('JP:industrial-engineer','007-04','製造工程・品質・工数改善 scope（機械）',null,null,false,2,'https://www.hellowork.mhlw.go.jp/info/mhlw_job_dictionary_02.html','2026-08-10'),
('JP:industrial-engineer','007-99','その他の製造技術者 — systems/process improvement reference',null,null,false,3,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:chemical-engineer','006-07','化学製品開発技術者',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:chemical-engineer','007-08','化学製品製造技術者',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:environmental-engineer','011-99','環境調査員・作業環境測定等 environmental measurement scope',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:environmental-engineer','008-04','環境・上下水道等の土木設計 scope',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:environmental-engineer','008-06','環境・上下水道等のその他土木技術 scope',null,null,false,3,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:engineering-technician','080-04','建築・土木製図 technical-support scope',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:engineering-technician','080-05','機械・電気電子製図 technical-support scope',null,null,false,2,'https://www.hellowork.mhlw.go.jp/info/mhlw_job_dictionary_08.html','2026-08-10')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'job_search','Hello Work job search','https://www.hellowork.mhlw.go.jp/kensaku/GECA110010.do','government',10,'2026-08-10' from public.country_occupation_profiles p where p.country_code='JP' and p.canonical_career_id in ('civil-engineer','mechanical-engineer','electrical-engineer','manufacturing-engineer','industrial-engineer','chemical-engineer','environmental-engineer','engineering-technician')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'source','2022 MHLW occupation classification','https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','government',20,'2026-08-10' from public.country_occupation_profiles p where p.country_code='JP' and p.canonical_career_id in ('civil-engineer','mechanical-engineer','electrical-engineer','manufacturing-engineer','industrial-engineer','chemical-engineer','environmental-engineer','engineering-technician')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at) values
('JP:civil-engineer','source','Construction-site engineer appointment framework — MLIT','https://www.kkr.mlit.go.jp/kensei/kensetugyo/index.html','government',30,'2026-08-10'),
('JP:electrical-engineer','source','Chief Electrical Engineer qualification — METI','https://www.meti.go.jp/information/license/c_text25.html','government',30,'2026-08-10'),
('JP:environmental-engineer','source','Working Environment Measurement Expert — MHLW','https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/roudoukijun/anzen/newpage_00012.html','government',30,'2026-08-10')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'JP:'||o.canonical_career_id,c.source_program_key,case when o.relation_type='direct' then 'direct' else 'related' end,coalesce(o.source_checked_at,'2026-08-10'::date)
from public.program_occupation_jp_staging o
join public.program_catalog_jp_staging c on c.id=o.program_catalog_id
where o.review_status='approved'
  and o.canonical_career_id in ('civil-engineer','mechanical-engineer','electrical-engineer','manufacturing-engineer','industrial-engineer','chemical-engineer','environmental-engineer','engineering-technician')
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;;
