-- Japan Hospitality occupation cohort.
-- Classification basis: 2022 revision of the Ministry of Health, Labour and Welfare occupation classification.

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('JP:chef','JP','chef','料理人・シェフ — skilled cuisine/career-progression umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-11',now()),
('JP:cook','JP','cook','調理員 — chain/institutional/general cooking umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-11',now()),
('JP:hotel-manager','JP','hotel-manager','ホテル・旅館支配人 — management/frontline-service umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-11',now()),
('JP:restaurant-manager','JP','restaurant-manager','飲食店店長 — corporate-management/frontline-service umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-11',now()),
('JP:baker','JP','baker','パン製造工・パン職人','MHLW Occupation Classification','2022','072-01','JPY',false,null,null,'profile_ready','2026-08-11',now()),
('JP:tourism-manager','JP','tourism-manager','観光・旅行マネジメント — management/tour-planning umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-11',now()),
('JP:event-planner','JP','event-planner','イベントプランナー','MHLW Occupation Classification','2022','033-03','JPY',false,null,null,'profile_ready','2026-08-11',now()),
('JP:hospitality-supervisor','JP','hospitality-supervisor','ホスピタリティ現場監督者 — restaurant/hotel/front/housekeeping umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-11',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at) values
('JP:chef','2026-08-11',0,0,0,0,12,0,0,0,4,16,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','Japan classifies skilled restaurant cooking primarily by cuisine under 055-01 to 055-04 rather than by a universal Chef seniority code. 055-02 explicitly includes シェフ.','entry_level_basis','Culinary school or workplace apprenticeship can lead into skilled cooking; senior chef responsibility usually follows substantial practical experience. Two reviewed advanced cuisine programmes are direct and one general culinary programme is related.','qualification_note','No universal statutory Chef licence is required to perform the broad occupation. 調理師 is a protected licensed title, but job tag states entry to professional cooking itself does not universally require that licence.','market_scope','Cuisine classifications are not merged into a fabricated exact Chef labour series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('JP:cook','2026-08-11',0,0,0,0,15,0,0,0,5,20,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','The broad Cook role is represented across 055-05 chain cooking, 055-06 school meals, 055-07 other institutional catering and 055-99 other cooking rather than one exact code.','entry_level_basis','Commercial cooking can be entered through workplace training or culinary study; three reviewed Japanese culinary programmes are direct study pathways.','qualification_note','No universal statutory Cook licence is required. The 調理師 title is licensed and protected, while specific establishments and food-safety responsibilities can carry separate requirements.','market_scope','Chain, institutional and other cooking groups are preserved separately and are not combined into one exact Cook market series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('JP:hotel-manager','2026-08-11',0,0,0,0,10,0,0,0,5,15,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','Hotel managers split between 002-01 company managers when management is primary and 056-02 旅館・ホテル支配人 when frontline hospitality/service management is primary.','entry_level_basis','Hospitality or tourism study can support entry, but job tag describes progression through hotel departments and management experience as the common route. One reviewed programme is direct and one is related.','qualification_note','No universal statutory Hotel Manager licence applies; venue, food, liquor or other regulated operations can impose separate role-specific requirements.','market_scope','Corporate management and frontline hotel-management classifications are not merged into one unsupported exact series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('JP:restaurant-manager','2026-08-11',0,0,0,0,12,0,0,0,5,17,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','Restaurant managers can fall under 002-01 when corporate management is primary, 003-99 for qualifying owner-managed businesses, or 056-01 when frontline service/restaurant operations are primary.','entry_level_basis','Hospitality study is relevant, but management usually develops from restaurant operations, customer service, staffing, purchasing and commercial responsibility; two reviewed programmes are related pathways.','qualification_note','No universal statutory Restaurant Manager licence applies. Food-hygiene, liquor and venue responsibilities can require separate designated persons or credentials.','market_scope','Management and service-centred restaurant-manager groups are preserved separately rather than combined into one exact market series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('JP:baker','2026-08-11',0,0,0,0,15,0,0,0,5,20,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','MHLW 072-01 directly includes bread production workers and bakers; automated production-equipment operators are classified separately under 068-01.','entry_level_basis','Bakery work can be entered without a mandatory academic credential; one reviewed advanced bread programme is direct and one confectionery programme is related.','qualification_note','No universal statutory Baker licence applies. パン製造技能士 can support progression but is not universal entry permission; independent food businesses have separate hygiene and business obligations.','market_scope','CampCareer does not mix 068-01 automated production operators into the primary baker classification.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('JP:tourism-manager','2026-08-11',0,0,0,0,10,0,0,0,5,15,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','There is no standalone MHLW Tourism Manager code. Tourism management can combine organisational management under 002-01 with tour and travel-product planning explicitly listed in 033-03.','entry_level_basis','Tourism and hospitality study plus operating, commercial and supplier-management experience provide common foundations; two reviewed Japanese tourism programmes are direct academic pathways.','qualification_note','No universal Tourism Manager licence applies. Narrow travel operations such as itinerary management or travel-business responsibilities can carry separate statutory or training requirements.','market_scope','Management, travel planning, sales and guiding occupations are not merged into a fabricated Tourism Manager labour series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('JP:event-planner','2026-08-11',0,0,0,0,12,0,0,0,5,17,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','MHLW 033-03 directly lists イベントプランナー within planning and research clerical occupations. Creative production leadership can fall separately under 020-99 and is not automatically rolled into this profile.','entry_level_basis','Event, hospitality, tourism, marketing and communications study can support entry; the two reviewed Japanese programmes are related rather than occupational qualifications.','qualification_note','No universal statutory Event Planner licence applies. Venue, safety, alcohol, entertainment and public-space permissions depend on the event and organiser.','market_scope','033-03 is broader than event planning alone, so group-level market data are not treated as exact Event Planner observations.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('JP:hospitality-supervisor','2026-08-11',0,0,0,0,12,0,0,0,5,17,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','Japan has no single generic Hospitality Supervisor code. Frontline supervision is distributed across restaurant management 056-01, hotel management 056-02, food service 056-03, hotel front/service 056-04/05 and housekeeping work such as 096-03.','entry_level_basis','Hospitality study plus frontline experience commonly leads to shift-lead and supervisory responsibility; one reviewed hospitality-tourism programme is direct and one tourism programme is related.','qualification_note','No universal statutory Hospitality Supervisor licence applies. Food, liquor, gaming, accommodation and safety responsibilities can carry venue-specific credentials or designated-person requirements.','market_scope','Distinct restaurant, hotel, service and housekeeping classifications are not aggregated into one exact supervisor market series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11')
on conflict (profile_key,as_of_date) do update set shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('JP:chef','055-01','日本料理調理人 — skilled cuisine scope',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-11'),
('JP:chef','055-02','西洋料理調理人 — includes シェフ',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-11'),
('JP:chef','055-03','中華料理調理人 — skilled cuisine scope',null,null,false,3,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-11'),
('JP:chef','055-04','各国料理調理人 — skilled cuisine scope',null,null,false,4,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-11'),
('JP:cook','055-05','飲食チェーン店等調理員',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-11'),
('JP:cook','055-06','学校給食調理員',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-11'),
('JP:cook','055-07','給食等調理員（学校を除く）',null,null,false,3,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-11'),
('JP:cook','055-99','その他の飲食物調理の職業',null,null,false,4,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-11'),
('JP:hotel-manager','002-01','会社管理職員 — hotel corporate-management scope',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1&pageNo=2','2026-08-11'),
('JP:hotel-manager','056-02','旅館・ホテル支配人 — frontline hospitality-management scope',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1&pageNo=7','2026-08-11'),
('JP:restaurant-manager','002-01','会社管理職員 — restaurant corporate-management scope',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1&pageNo=2','2026-08-11'),
('JP:restaurant-manager','003-99','他に分類されない管理的職業 — owner-manager scope',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1&pageNo=2','2026-08-11'),
('JP:restaurant-manager','056-01','飲食店店長 — frontline service-management scope',null,null,false,3,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1&pageNo=7','2026-08-11'),
('JP:baker','072-01','パン・菓子製造工 — bread-production scope',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1&pageNo=9','2026-08-11'),
('JP:tourism-manager','002-01','会社管理職員 — tourism-management scope',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1&pageNo=2','2026-08-11'),
('JP:tourism-manager','033-03','企画・調査事務員 — tour/travel-product planning scope',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1&pageNo=5','2026-08-11'),
('JP:event-planner','033-03','イベントプランナー',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1&pageNo=5','2026-08-11'),
('JP:hospitality-supervisor','056-01','飲食店店長 — restaurant supervisor reference',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1&pageNo=7','2026-08-11'),
('JP:hospitality-supervisor','056-02','旅館・ホテル支配人 — hotel supervisor reference',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1&pageNo=7','2026-08-11'),
('JP:hospitality-supervisor','056-03','飲食店ホール係・配ぜん人 — food-service reference',null,null,false,3,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1&pageNo=7','2026-08-11'),
('JP:hospitality-supervisor','056-04','旅館・ホテルフロント係 — front-office reference',null,null,false,4,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1&pageNo=7','2026-08-11'),
('JP:hospitality-supervisor','056-05','旅館・ホテル接客係 — guest-service reference',null,null,false,5,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1&pageNo=7','2026-08-11'),
('JP:hospitality-supervisor','096-03','旅館・ホテル客室清掃整備員 — housekeeping reference',null,null,false,6,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1&pageNo=11','2026-08-11')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'job_search','Hello Work job search','https://www.hellowork.mhlw.go.jp/kensaku/GECA110010.do','government',10,'2026-08-11' from public.country_occupation_profiles p where p.country_code='JP' and p.canonical_career_id in ('chef','cook','hotel-manager','restaurant-manager','baker','tourism-manager','event-planner','hospitality-supervisor')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'source','MHLW 2022 occupation classification','https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','government',20,'2026-08-11' from public.country_occupation_profiles p where p.country_code='JP' and p.canonical_career_id in ('chef','cook','hotel-manager','restaurant-manager','baker','tourism-manager','event-planner','hospitality-supervisor')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'JP:'||o.canonical_career_id,c.source_program_key,case when o.relation_type='direct' then 'direct' else 'related' end,coalesce(o.source_checked_at,'2026-08-11'::date)
from public.program_occupation_jp_staging o join public.program_catalog_jp_staging c on c.id=o.program_catalog_id
where o.review_status='approved' and o.canonical_career_id in ('chef','cook','hotel-manager','restaurant-manager','baker','tourism-manager','event-planner','hospitality-supervisor')
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;;
