-- Australia Aircraft Maintenance Technician profile.
-- Canonical profile is an umbrella across current OSCA 332131, 332132 and 332133.

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at)
values ('AU:aircraft-maintenance-technician','AU','aircraft-maintenance-technician','Aircraft Maintenance Technician','OSCA','2024 v1.0','3321','AUD',false,'CASA Part 66 licence applies to licensed certifying privileges; TRA assesses migration occupations','https://www.casa.gov.au/licences-and-certificates/maintenance-engineers/aircraft-engineer-licences','profile_ready','2026-08-09',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,employment_total,median_weekly_earnings,median_hourly_earnings,annualised_median_salary,all_occupations_median_weekly,part_time_share_pct,female_share_pct,median_age,average_full_time_hours,vacancies_three_month_avg,vacancy_period,vacancy_yoy_pct,employment_growth_5y_pct,employment_growth_10y_pct,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at)
values ('AU:aircraft-maintenance-technician','2026-05-01',4350,null,null,null,1852,null,null,null,null,122.33333,'2026-05-01',14.69,1.04,6.93,20,0,5,0,13,0,5,10,3,56,'career-opportunity-v1','provisional',jsonb_build_object(
 'classification_scope','Canonical Aircraft Maintenance Technician preserves exact current OSCA 332131 Avionics, 332132 Mechanical and 332133 Structures streams.',
 'labour_scope','Exact legacy stream employment totals 2,300 avionics, 1,800 mechanical and 250 structures, summed to 4,350. Combined demographics and earnings are intentionally null rather than fabricated.',
 'vacancy_scope','Broader ANZSCO 3231 vacancies were 122.33 in May 2026 versus 106.67 in May 2025, about +14.69% year on year; intensity and trend receive no credit.',
 'projection_scope','Broader ANZSCO 3231 projections are +1.04% to 2030 and +6.93% to 2035; partial growth credit only.',
 'shortage_note','JSA 2025 OSL rates all three current technician streams as Shortage nationally.',
 'visa_basis','Legacy ANZSCO 323111, 323112 and 323113 are current CSOL pathways with Trades Recognition Australia as assessing authority.',
 'entry_level_basis','National Aeroskills vocational qualifications provide direct avionics, mechanical and structures pathways even though no verified matching CRICOS course is forced into the current CampCareer catalogue.',
 'entry_burden_basis','Part 66 licensing adds burden for certifying privileges, while non-certifying technician roles remain distinct.'
),'2026-08-09')
on conflict (profile_key,as_of_date) do update set employment_total=excluded.employment_total,median_weekly_earnings=excluded.median_weekly_earnings,median_hourly_earnings=excluded.median_hourly_earnings,annualised_median_salary=excluded.annualised_median_salary,all_occupations_median_weekly=excluded.all_occupations_median_weekly,part_time_share_pct=excluded.part_time_share_pct,female_share_pct=excluded.female_share_pct,median_age=excluded.median_age,average_full_time_hours=excluded.average_full_time_hours,vacancies_three_month_avg=excluded.vacancies_three_month_avg,vacancy_period=excluded.vacancy_period,vacancy_yoy_pct=excluded.vacancy_yoy_pct,employment_growth_5y_pct=excluded.employment_growth_5y_pct,employment_growth_10y_pct=excluded.employment_growth_10y_pct,shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,legacy_code_system,legacy_code_version,legacy_code,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('AU:aircraft-maintenance-technician','332131','Aircraft Maintenance Technician (Avionics)','ANZSCO','2022','323111',null,true,true,1,'https://www.abs.gov.au/statistics/classifications/osca-occupation-standard-classification-australia/2024-version-1-0','2026-08-09'),
('AU:aircraft-maintenance-technician','332132','Aircraft Maintenance Technician (Mechanical)','ANZSCO','2022','323112',null,true,true,2,'https://www.abs.gov.au/statistics/classifications/osca-occupation-standard-classification-australia/2024-version-1-0','2026-08-09'),
('AU:aircraft-maintenance-technician','332133','Aircraft Maintenance Technician (Structures)','ANZSCO','2022','323113',null,true,true,3,'https://www.abs.gov.au/statistics/classifications/osca-occupation-standard-classification-australia/2024-version-1-0','2026-08-09')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,legacy_code_system=excluded.legacy_code_system,legacy_code_version=excluded.legacy_code_version,legacy_code=excluded.legacy_code,shortage_rating=excluded.shortage_rating,visa_eligible=excluded.visa_eligible,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_region_metrics (profile_key,region_code,as_of_date,shortage_rating,vacancy_count,source_url) values
('AU:aircraft-maintenance-technician','ACT','2026-05-01',null,2,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:aircraft-maintenance-technician','NSW','2026-05-01',null,21.66667,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:aircraft-maintenance-technician','NT','2026-05-01',null,7,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:aircraft-maintenance-technician','QLD','2026-05-01',null,45,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:aircraft-maintenance-technician','SA','2026-05-01',null,10,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:aircraft-maintenance-technician','TAS','2026-05-01',null,1,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:aircraft-maintenance-technician','VIC','2026-05-01',null,9.66667,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:aircraft-maintenance-technician','WA','2026-05-01',null,26,'https://www.jobsandskills.gov.au/data/internet-vacancy-index')
on conflict (profile_key,region_code,as_of_date) do update set shortage_rating=excluded.shortage_rating,vacancy_count=excluded.vacancy_count,source_url=excluded.source_url;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,region_code,sort_order,source_checked_at) values
('AU:aircraft-maintenance-technician','job_search','SEEK — Aircraft Maintenance Technician jobs','https://www.seek.com.au/aircraft-maintenance-jobs','private_job_board',null,1,'2026-08-09'),('AU:aircraft-maintenance-technician','employer','Qantas Careers','https://careers.qantas.com/','airline',null,1,'2026-08-09'),('AU:aircraft-maintenance-technician','employer','Virgin Australia Careers','https://careers.virginaustralia.com/','airline',null,2,'2026-08-09'),('AU:aircraft-maintenance-technician','employer','Boeing Australia Careers','https://jobs.boeing.com/location/australia-jobs/185/2077456/2','aerospace',null,3,'2026-08-09'),('AU:aircraft-maintenance-technician','employer','BAE Systems Australia Careers','https://www.baesystems.com/en-aus/careers','aerospace_defence',null,4,'2026-08-09'),('AU:aircraft-maintenance-technician','employer','Jetstar Careers','https://careers.jetstar.com/','airline',null,5,'2026-08-09'),('AU:aircraft-maintenance-technician','entry_program','training.gov.au — Aeroskills qualifications','https://training.gov.au/','national_training_register',null,1,'2026-08-09'),('AU:aircraft-maintenance-technician','source','CASA — Aircraft engineer licences','https://www.casa.gov.au/licences-and-certificates/maintenance-engineers/aircraft-engineer-licences','official_licensing',null,1,'2026-08-09'),('AU:aircraft-maintenance-technician','source','JSA — 2025 Occupation Shortage List','https://www.jobsandskills.gov.au/data/occupation-shortage-analysis/occupation-shortage-list','official_shortage',null,2,'2026-08-09')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,region_code=excluded.region_code,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;;
