create table if not exists public.institution_student_sponsor_nl_staging (
  id bigint generated by default as identity primary key,
  source_name text not null default 'IND public register Study',
  source_sponsor_key text not null,
  sponsor_name text not null,
  education_category text,
  institution_id uuid references catalog.institutions(id),
  brin_code text,
  match_status text not null default 'unmatched'
    check (match_status in ('unmatched','candidate','matched','rejected')),
  match_basis text,
  source_url text not null,
  source_as_of date not null,
  collected_at timestamptz not null default now(),
  unique (source_name, source_sponsor_key)
);
create index if not exists institution_student_sponsor_nl_staging_institution_idx on public.institution_student_sponsor_nl_staging (institution_id, match_status);
create index if not exists institution_student_sponsor_nl_staging_name_idx on public.institution_student_sponsor_nl_staging (lower(sponsor_name));
create table if not exists public.program_catalog_nl_staging (
  id bigint generated by default as identity primary key,
  source_name text not null,
  source_program_key text not null,
  recognised_program_code text,
  offered_program_code text,
  institution_name text not null,
  institution_id uuid references catalog.institutions(id),
  brin_code text,
  education_sector text not null default 'UNKNOWN' check (education_sector in ('WO','HBO','MBO','OTHER','UNKNOWN')),
  source_program_name text,
  title text not null,
  native_level_code text,
  degree_type text,
  eqf_level integer,
  nlqf_level integer,
  ects integer check (ects is null or ects > 0),
  canonical_level text not null default 'UNKNOWN' check (canonical_level in ('ASSOCIATE_DEGREE','BACHELOR','MASTER','DOCTORATE','CERTIFICATE','OTHER','UNKNOWN')),
  programme_type text,
  field_category text,
  city text,
  campus text,
  duration_months integer check (duration_months is null or duration_months > 0),
  study_mode text,
  language_code text,
  official_program_url text not null,
  recognition_source_url text,
  source_as_of date,
  collection_status text not null default 'official_program_verified',
  verification_tier text not null default 'C' check (verification_tier in ('A','B','C')),
  collected_at timestamptz not null default now(),
  unique (source_name, source_program_key)
);
create index if not exists program_catalog_nl_staging_institution_idx on public.program_catalog_nl_staging (institution_id);
create index if not exists program_catalog_nl_staging_code_idx on public.program_catalog_nl_staging (recognised_program_code);
create index if not exists program_catalog_nl_staging_sector_idx on public.program_catalog_nl_staging (education_sector, canonical_level, verification_tier);
create index if not exists program_catalog_nl_staging_title_idx on public.program_catalog_nl_staging (lower(title));
create table if not exists public.program_international_nl_staging (
  id bigint generated by default as identity primary key,
  program_catalog_id bigint not null unique references public.program_catalog_nl_staging(id) on delete cascade,
  student_sponsor_record_id bigint references public.institution_student_sponsor_nl_staging(id),
  student_sponsor_eligible boolean,
  accredited_programme_evidence boolean,
  full_time_evidence boolean,
  international_students_eligible boolean,
  international_admission_status text not null default 'not_yet_verified',
  language_requirement_context text,
  residence_permit_context text,
  intake_label text,
  intake_start_date date,
  application_deadline date,
  admission_source_url text,
  international_source_url text,
  sponsor_source_url text,
  source_as_of date,
  verification_status text not null default 'not_yet_verified',
  rule_notes text,
  verified_at timestamptz,
  collected_at timestamptz not null default now()
);
create index if not exists program_international_nl_staging_status_idx on public.program_international_nl_staging (international_admission_status, international_students_eligible);
create index if not exists program_international_nl_staging_sponsor_idx on public.program_international_nl_staging (student_sponsor_record_id);
create table if not exists public.program_occupation_nl_staging (
  program_catalog_id bigint not null references public.program_catalog_nl_staging(id) on delete cascade,
  canonical_career_id text not null,
  rule_version text not null,
  match_basis text not null default 'official_program_title_review',
  match_pattern text not null,
  review_status text not null default 'candidate' check (review_status in ('candidate','approved','rejected')),
  relation_type text,
  source_checked_at date,
  reviewer_note text,
  matched_at timestamptz not null default now(),
  reviewed_at timestamptz,
  primary key (program_catalog_id, canonical_career_id)
);
create index if not exists program_occupation_nl_staging_career_idx on public.program_occupation_nl_staging (canonical_career_id, review_status);
alter table public.institution_student_sponsor_nl_staging enable row level security;
alter table public.program_catalog_nl_staging enable row level security;
alter table public.program_international_nl_staging enable row level security;
alter table public.program_occupation_nl_staging enable row level security;
revoke all on table public.institution_student_sponsor_nl_staging from public, anon, authenticated;
revoke all on table public.program_catalog_nl_staging from public, anon, authenticated;
revoke all on table public.program_international_nl_staging from public, anon, authenticated;
revoke all on table public.program_occupation_nl_staging from public, anon, authenticated;
grant select, insert, update, delete on table public.institution_student_sponsor_nl_staging to service_role;
grant select, insert, update, delete on table public.program_catalog_nl_staging to service_role;
grant select, insert, update, delete on table public.program_international_nl_staging to service_role;
grant select, insert, update, delete on table public.program_occupation_nl_staging to service_role;
grant usage, select on all sequences in schema public to service_role;
comment on table public.institution_student_sponsor_nl_staging is 'Netherlands Phase 2 staging for IND recognised Study sponsor evidence; sponsor status is institution-level evidence only.';
comment on table public.program_catalog_nl_staging is 'Netherlands Phase 2 programme discovery staging sourced from current DUO/RIO and official provider programme evidence.';
comment on column public.program_catalog_nl_staging.recognised_program_code is 'Official Dutch recognised programme identity (RIO/CROHO code) when directly evidenced; never infer from title.';
comment on column public.program_catalog_nl_staging.education_sector is 'Preserve the Dutch WO/HBO/MBO sector distinction instead of collapsing it into one university type.';
comment on table public.program_international_nl_staging is 'Programme-level international-study evidence. IND sponsor recognition alone does not prove admission to a specific programme.';
comment on table public.program_occupation_nl_staging is 'Netherlands programme relationships to the canonical CampCareer 80-career taxonomy.';;
