create schema if not exists ingest;

create table if not exists ingest.visa_pathways (
  id bigint generated by default as identity primary key,
  country_code text not null check (country_code ~ '^[A-Z]{2}$'),
  country_name text not null,
  visa_name text not null,
  kind text not null check (kind in ('Study', 'Work', 'Working holiday', 'Skilled', 'Family', 'Temporary')),
  note text not null,
  authority text not null,
  source_url text not null check (source_url ~ '^https://'),
  source_title text not null,
  last_verified_on date not null,
  display_order integer not null default 0 check (display_order >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (country_code, visa_name)
);

comment on table ingest.visa_pathways is
  'Verified navigation catalogue for the workspace /visas surface. Source facts remain controlled by the issuing authority.';
comment on column ingest.visa_pathways.last_verified_on is
  'Date the official issuing-authority page was reviewed for catalogue inclusion.';

insert into ingest.visa_pathways (
  country_code, country_name, visa_name, kind, note, authority, source_url,
  source_title, last_verified_on, display_order, is_active
)
values
  ('AU', 'Australia', 'Student visa', 'Study', 'Full-time study at a registered Australian institution.', 'Department of Home Affairs', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500', 'Student visa (subclass 500)', date '2026-08-06', 10, true),
  ('AU', 'Australia', 'Working Holiday', 'Working holiday', 'Work and travel under the Working Holiday visa programme.', 'Department of Home Affairs', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/work-holiday-417', 'Working Holiday visa (subclass 417)', date '2026-08-06', 20, true),
  ('AU', 'Australia', 'Temporary Graduate', 'Work', 'Temporary work rights after completing eligible Australian study.', 'Department of Home Affairs', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-graduate-485', 'Temporary Graduate visa (subclass 485)', date '2026-08-06', 30, true),
  ('AU', 'Australia', 'Skilled Independent', 'Skilled', 'Points-tested permanent skilled migration without a sponsor or nominator.', 'Department of Home Affairs', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-independent-189', 'Skilled Independent visa (subclass 189)', date '2026-08-06', 40, true),
  ('AU', 'Australia', 'Skilled Nominated', 'Skilled', 'Points-tested permanent skilled migration with state or territory nomination.', 'Department of Home Affairs', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-nominated-190', 'Skilled Nominated visa (subclass 190)', date '2026-08-06', 50, true),
  ('AU', 'Australia', 'Skilled Work Regional', 'Skilled', 'Provisional skilled migration for eligible regional Australia pathways.', 'Department of Home Affairs', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-work-regional-provisional-491', 'Skilled Work Regional (Provisional) visa (subclass 491)', date '2026-08-06', 60, true),
  ('AU', 'Australia', 'Temporary Skill Shortage', 'Work', 'Employer-sponsored temporary skilled work under the current subclass 482 framework.', 'Department of Home Affairs', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skills-in-demand-482', 'Skills in Demand visa (subclass 482)', date '2026-08-06', 70, true),
  ('CA', 'Canada', 'Study Permit', 'Study', 'Allows eligible international students to study at a designated learning institution.', 'Immigration, Refugees and Citizenship Canada', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html', 'Study permit', date '2026-08-06', 10, true),
  ('CA', 'Canada', 'Post-Graduation Work Permit', 'Work', 'Open work permit for eligible graduates of designated learning institutions.', 'Immigration, Refugees and Citizenship Canada', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/work/after-graduation.html', 'Post-graduation work permit', date '2026-08-06', 20, true),
  ('CA', 'Canada', 'Express Entry', 'Skilled', 'Application management system for eligible federal economic immigration programmes.', 'Immigration, Refugees and Citizenship Canada', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html', 'Express Entry', date '2026-08-06', 30, true),
  ('CA', 'Canada', 'Provincial Nominee Program', 'Skilled', 'Permanent residence pathway based on provincial or territorial nomination.', 'Immigration, Refugees and Citizenship Canada', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/provincial-nominees.html', 'Provincial Nominee Program', date '2026-08-06', 40, true),
  ('CA', 'Canada', 'International Experience Canada', 'Working holiday', 'Youth mobility work-permit categories for citizens of partner countries.', 'Immigration, Refugees and Citizenship Canada', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/work-canada/iec.html', 'International Experience Canada', date '2026-08-06', 50, true),
  ('US', 'United States', 'F-1 Student', 'Study', 'Academic study at an SEVP-certified school under F-1 status.', 'U.S. Citizenship and Immigration Services', 'https://www.uscis.gov/working-in-the-united-states/students-and-exchange-visitors/students-and-employment', 'Students and Employment', date '2026-08-06', 10, true),
  ('US', 'United States', 'H-1B Specialty Occupation', 'Work', 'Employer petition for qualifying specialty-occupation employment.', 'U.S. Citizenship and Immigration Services', 'https://www.uscis.gov/working-in-the-united-states/h-1b-specialty-occupations', 'H-1B Specialty Occupations', date '2026-08-06', 20, true),
  ('US', 'United States', 'J-1 Exchange Visitor', 'Work', 'Department of State exchange programmes for approved participant categories.', 'U.S. Department of State', 'https://j1visa.state.gov/programs/', 'Exchange Visitor Program categories', date '2026-08-06', 30, true),
  ('US', 'United States', 'L-1 Intracompany Transferee', 'Work', 'Intracompany transfer for qualifying executives, managers or specialised-knowledge employees.', 'U.S. Citizenship and Immigration Services', 'https://www.uscis.gov/working-in-the-united-states/temporary-workers/l-1a-intracompany-transferee-executive-or-manager', 'L-1A Intracompany Transferee Executive or Manager', date '2026-08-06', 40, true),
  ('US', 'United States', 'OPT / STEM OPT', 'Work', 'Temporary employment authorisation directly related to an eligible F-1 field of study.', 'U.S. Citizenship and Immigration Services', 'https://www.uscis.gov/working-in-the-united-states/students-and-exchange-visitors/optional-practical-training-opt-for-f-1-students', 'Optional Practical Training for F-1 Students', date '2026-08-06', 50, true),
  ('UK', 'United Kingdom', 'Student visa', 'Study', 'Study with a licensed UK student sponsor.', 'UK Visas and Immigration', 'https://www.gov.uk/student-visa', 'Student visa', date '2026-08-06', 10, true),
  ('UK', 'United Kingdom', 'Skilled Worker', 'Work', 'Sponsored work in an eligible occupation meeting current salary and route rules.', 'UK Visas and Immigration', 'https://www.gov.uk/skilled-worker-visa', 'Skilled Worker visa', date '2026-08-06', 20, true),
  ('UK', 'United Kingdom', 'Graduate visa', 'Work', 'Post-study permission after successful completion of an eligible UK course.', 'UK Visas and Immigration', 'https://www.gov.uk/graduate-visa', 'Graduate visa', date '2026-08-06', 30, true),
  ('UK', 'United Kingdom', 'Health and Care Worker', 'Work', 'Sponsored route for eligible health and adult social care occupations.', 'UK Visas and Immigration', 'https://www.gov.uk/health-care-worker-visa', 'Health and Care Worker visa', date '2026-08-06', 40, true),
  ('UK', 'United Kingdom', 'Youth Mobility Scheme', 'Working holiday', 'Temporary work and travel route for eligible young people from participating countries.', 'UK Visas and Immigration', 'https://www.gov.uk/youth-mobility', 'Youth Mobility Scheme visa', date '2026-08-06', 50, true),
  ('IE', 'Ireland', 'Student visa', 'Study', 'Study in Ireland on an eligible course and register the appropriate student permission.', 'Immigration Service Delivery', 'https://www.irishimmigration.ie/coming-to-study-in-ireland/', 'Coming to study in Ireland', date '2026-08-06', 10, true),
  ('IE', 'Ireland', 'Stamp 1G', 'Work', 'Third Level Graduate Programme permission to seek graduate employment after eligible Irish study.', 'Immigration Service Delivery', 'https://www.irishimmigration.ie/my-situation-has-changed-since-i-arrived-in-ireland/third-level-graduate-programme/', 'Third Level Graduate Programme', date '2026-08-06', 20, true),
  ('IE', 'Ireland', 'Working Holiday / Youth Mobility', 'Working holiday', 'Working-holiday authorisation under Ireland''s bilateral agreements.', 'Department of Foreign Affairs', 'https://www.ireland.ie/en/dfa/overseas-travel/working-holidays/', 'Working holidays', date '2026-08-06', 30, true),
  ('IE', 'Ireland', 'Critical Skills Employment Permit', 'Skilled', 'Employment permit for qualifying occupations, remuneration and job offers.', 'Department of Enterprise, Tourism and Employment', 'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/permit-types/critical-skills-employment-permit/', 'Critical Skills Employment Permit', date '2026-08-06', 40, true),
  ('DE', 'Germany', 'Student visa', 'Study', 'National visa and residence route for recognised higher education or preparatory study.', 'Federal Government of Germany', 'https://www.make-it-in-germany.com/en/visa-residence/types/studying', 'Visa for studying', date '2026-08-06', 10, true),
  ('DE', 'Germany', 'EU Blue Card', 'Skilled', 'Residence title for qualifying highly skilled employment meeting current salary rules.', 'Federal Government of Germany', 'https://www.make-it-in-germany.com/en/visa-residence/types/eu-blue-card', 'EU Blue Card', date '2026-08-06', 20, true),
  ('DE', 'Germany', 'Skilled Worker visa', 'Work', 'Residence route for qualified professionals with recognised qualifications and eligible employment.', 'Federal Government of Germany', 'https://www.make-it-in-germany.com/en/visa-residence/types/work-qualified-professionals', 'Work visa for qualified professionals', date '2026-08-06', 30, true),
  ('DE', 'Germany', 'Working Holiday', 'Working holiday', 'Work and travel under a German bilateral youth-mobility agreement.', 'Federal Foreign Office', 'https://www.auswaertiges-amt.de/en/visa-service/buergerservice/faq/workingholiday/606672', 'Working Holiday Programme', date '2026-08-06', 40, true),
  ('DE', 'Germany', 'Job Seeker Visa', 'Temporary', 'Job-search route, including the current Opportunity Card where applicable.', 'Federal Government of Germany', 'https://www.make-it-in-germany.com/en/visa-residence/opportunity-card', 'Opportunity Card for job search', date '2026-08-06', 50, true),
  ('DE', 'Germany', 'Family Reunion Visa', 'Family', 'Residence route for eligible family members joining a person in Germany.', 'Federal Government of Germany', 'https://www.make-it-in-germany.com/en/visa-residence/family-reunification', 'Family reunification', date '2026-08-06', 60, true),
  ('NL', 'Netherlands', 'Student visa', 'Study', 'Residence route for study with an IND-recognised educational sponsor.', 'Immigration and Naturalisation Service', 'https://ind.nl/en/residence-permits/study/student-residence-permit-for-university-or-higher-professional-education', 'Student residence permit for higher education', date '2026-08-06', 10, true),
  ('NL', 'Netherlands', 'Highly Skilled Migrant', 'Skilled', 'Employer-sponsored residence permit through an IND-recognised sponsor.', 'Immigration and Naturalisation Service', 'https://ind.nl/en/residence-permits/work/highly-skilled-migrant', 'Highly skilled migrant', date '2026-08-06', 20, true),
  ('NL', 'Netherlands', 'Orientation Year', 'Work', 'One-year residence permit for eligible graduates and researchers to seek work.', 'Immigration and Naturalisation Service', 'https://ind.nl/en/residence-permits/work/residence-permit-for-orientation-year', 'Orientation year for highly educated persons', date '2026-08-06', 30, true),
  ('NL', 'Netherlands', 'Working Holiday', 'Working holiday', 'Cultural-exchange residence route for eligible partner-country nationals.', 'Immigration and Naturalisation Service', 'https://ind.nl/en/residence-permits/au-pair-and-exchange/working-holiday-residence-permit', 'Working Holiday residence permit', date '2026-08-06', 40, true),
  ('BE', 'Belgium', 'Student visa', 'Study', 'Long-stay study route for recognised Belgian higher education.', 'Belgian Immigration Office', 'https://dofi.ibz.be/en/themes/third-country-nationals/study', 'Study in Belgium', date '2026-08-06', 10, true),
  ('BE', 'Belgium', 'Single Permit', 'Work', 'Combined regional work authorisation and federal residence decision.', 'Belgian Immigration Office', 'https://dofi.ibz.be/en/themas/onderdanen-van-derde-landen/werk/single-permit', 'Single Permit', date '2026-08-06', 20, true),
  ('BE', 'Belgium', 'Working Holiday', 'Working holiday', 'Temporary working-holiday stay under a Belgian bilateral agreement.', 'Belgian Immigration Office', 'https://dofi.ibz.be/en/themes/ressortissants-dun-pays-tiers/travail/working-holiday-programme', 'Working Holiday Programme', date '2026-08-06', 30, true),
  ('FR', 'France', 'Student visa', 'Study', 'Long-stay study visa route for eligible French higher education.', 'France-Visas', 'https://www.france-visas.gouv.fr/en/etudiant', 'Student', date '2026-08-06', 10, true),
  ('FR', 'France', 'Talent Passport', 'Skilled', 'Multi-year talent residence route for qualifying professional, research and project categories.', 'France-Visas', 'https://france-visas.gouv.fr/en/web/france-visas/talents-internationaux-et-attractivite-economique', 'Talent Passport', date '2026-08-06', 20, true),
  ('FR', 'France', 'Working Holiday', 'Working holiday', 'Work and travel in France under an eligible bilateral agreement.', 'France-Visas', 'https://www.france-visas.gouv.fr/en/web/france-visas/jeunes-voyageurs', 'Young traveller and working holiday', date '2026-08-06', 30, true)
on conflict (country_code, visa_name) do update
set country_name = excluded.country_name,
    kind = excluded.kind,
    note = excluded.note,
    authority = excluded.authority,
    source_url = excluded.source_url,
    source_title = excluded.source_title,
    last_verified_on = excluded.last_verified_on,
    display_order = excluded.display_order,
    is_active = excluded.is_active,
    updated_at = now();

create or replace view public.visa_pathways as
select id, country_code, country_name, visa_name, kind, note, authority,
       source_url, source_title, last_verified_on, display_order, updated_at
from ingest.visa_pathways
where is_active;

comment on view public.visa_pathways is
  'Read-only public catalogue consumed by the workspace /visas page.';

grant select on public.visa_pathways to anon, authenticated;
grant select, insert, update, delete on ingest.visa_pathways to service_role;
revoke all on ingest.visa_pathways from anon, authenticated;;
