-- Japan Technology occupation cohort.
-- Classification basis: 2022 revision of the Ministry of Health, Labour and Welfare occupation classification.

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('JP:software-developer','JP','software-developer','ソフトウェア開発者 — development umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:data-analyst','JP','data-analyst','データアナリスト — analytics scope without standalone MHLW code','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:data-engineer','JP','data-engineer','データエンジニア','MHLW Occupation Classification','2022','010-99','JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:cybersecurity-analyst','JP','cybersecurity-analyst','サイバーセキュリティアナリスト — operations/vulnerability umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:network-administrator','JP','network-administrator','ITシステム運用管理者 — network administrator scope','MHLW Occupation Classification','2022','010-04','JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:cloud-engineer','JP','cloud-engineer','クラウドエンジニア — infrastructure design/operations umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:database-administrator','JP','database-administrator','ITシステム運用管理者 — database administrator scope','MHLW Occupation Classification','2022','010-04','JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:ict-support-technician','JP','ict-support-technician','ITヘルプデスク','MHLW Occupation Classification','2022','010-05','JPY',false,null,null,'profile_ready','2026-08-10',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at) values
('JP:software-developer','2026-08-10',0,0,0,0,15,0,0,0,3,18,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','Canonical Software Developer spans 009-01 web/open development, 009-02 embedded/control development, 009-03 programming and 009-99 other software-development work; no single code is fabricated.','entry_level_basis','Computing study, projects and practical software-development skills provide multiple entry routes; seven approved Japanese programmes are retained as direct study links.','market_scope','No exact recurring cross-country-comparable market series exists for the canonical umbrella.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:data-analyst','2026-08-10',0,0,0,0,10,0,0,0,5,15,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','The 2022 MHLW classification has no standalone Data Analyst code. Job tag places Data Scientist under 011-99, but Data Analyst is broader business-facing analytics and is not equated with Data Scientist.','entry_level_basis','Quantitative, computing, economics and business programmes are related pathways; eight approved programme links are retained only as related.','market_scope','Data-scientist or individual vacancy statistics are not reused as exact Data Analyst evidence.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:data-engineer','2026-08-10',0,0,0,0,10,0,0,0,5,15,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','2022 MHLW 010-99 explicitly lists データエンジニア and ビッグデータエンジニア.','entry_level_basis','Computer science and information programmes are common pathways, but production data-platform work often expects database, programming and cloud skills.','market_scope','010-99 is a broad residual IT group, so its statistics are not treated as Data Engineer-only evidence.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:cybersecurity-analyst','2026-08-10',0,0,0,0,10,0,0,0,3,13,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','Operational security analysts align to 010-04 IT system operations, while vulnerability-diagnosis security engineers are listed in 010-99; the canonical role spans both and therefore has no fabricated single code.','entry_level_basis','Computing programmes provide related preparation, while practical systems, network and security-operations skills remain important.','qualification_note','IPA information-security certifications are professional credentials, not a universal statutory licence to practise this occupation.','market_scope','Broader system-operations or residual-IT figures are not scored as exact cyber-analyst data.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:network-administrator','2026-08-10',0,0,0,0,15,0,0,0,3,18,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','Job tag explicitly lists ネットワーク管理者 as an alternative title under 010-04 ITシステム運用管理者.','entry_level_basis','Networking and information-systems study plus hands-on server/network administration support entry; four approved programmes are retained as related.','qualification_note','Vendor and IPA certifications can support employability but are not a universal statutory licence.','market_scope','010-04 includes broader system administration, so group statistics are not treated as network-administrator-only evidence.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:cloud-engineer','2026-08-10',0,0,0,0,10,0,0,0,3,13,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','Cloud infrastructure design/build aligns to 010-02 ITシステム設計技術者, while ongoing cloud operations aligns to 010-04; the canonical role spans both.','entry_level_basis','Computer science and information programmes are related pathways, but cloud platform, networking, Linux and infrastructure experience are commonly needed.','qualification_note','Cloud-vendor and IPA credentials are optional professional signals, not a universal statutory licence.','market_scope','System-design and operations statistics are not merged into a fabricated Cloud Engineer series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:database-administrator','2026-08-10',0,0,0,0,12,0,0,0,3,15,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','Database administration is represented through 010-04 ITシステム運用管理者, restricted to database operations, access, backup, performance and reliability work.','entry_level_basis','Computing study is related preparation; practical database and systems-administration skills are important.','qualification_note','IPA Database Specialist and vendor credentials are not universal statutory licences.','market_scope','010-04 system-administration statistics are broader than DBA and remain unscored.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:ict-support-technician','2026-08-10',0,0,0,0,15,0,0,0,5,20,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','2022 MHLW 010-05 ITヘルプデスク directly covers internal help desk and technical user-support work.','entry_level_basis','The occupation can be entered through IT study, certifications and practical support experience; four approved programmes are retained as related pathways.','qualification_note','No universal statutory occupational licence is required.','market_scope','Published help-desk statistics are not yet normalised into the cross-country scoring model.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10')
on conflict (profile_key,as_of_date) do update set shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('JP:software-developer','009-01','ソフトウェア開発技術者（WEB・オープン系）',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:software-developer','009-02','ソフトウェア開発技術者（組込・制御系）',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:software-developer','009-03','プログラマー',null,null,false,3,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:software-developer','009-99','その他の情報処理・通信技術者（ソフトウェア開発）',null,null,false,4,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:data-analyst','011-99','他に分類されない技術の職業 — data-science/analytics reference only',null,null,false,1,'https://shigoto.mhlw.go.jp/User/Occupation/Detail/323','2026-08-10'),
('JP:data-engineer','010-99','その他の情報処理・通信技術者（ソフトウェア開発を除く） — data engineer',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:cybersecurity-analyst','010-04','ITシステム運用管理者 — security operations analyst scope',null,null,false,1,'https://shigoto.mhlw.go.jp/Occupation/Detail?occupationId=321','2026-08-10'),
('JP:cybersecurity-analyst','010-99','その他の情報処理・通信技術者 — vulnerability-diagnosis security scope',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:network-administrator','010-04','ITシステム運用管理者 — network administrator scope',null,null,true,1,'https://shigoto.mhlw.go.jp/User/Occupation/Detail/319','2026-08-10'),
('JP:cloud-engineer','010-02','ITシステム設計技術者 — cloud infrastructure design/build scope',null,null,false,1,'https://shigoto.mhlw.go.jp/User/Occupation/Detail/318','2026-08-10'),
('JP:cloud-engineer','010-04','ITシステム運用管理者 — cloud operations scope',null,null,false,2,'https://shigoto.mhlw.go.jp/User/Occupation/Detail/319','2026-08-10'),
('JP:database-administrator','010-04','ITシステム運用管理者 — database administrator scope',null,null,true,1,'https://shigoto.mhlw.go.jp/User/Occupation/Detail/319','2026-08-10'),
('JP:ict-support-technician','010-05','ITヘルプデスク',null,null,true,1,'https://shigoto.mhlw.go.jp/Occupation/Detail?occupationId=320','2026-08-10')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'job_search','Hello Work job search','https://www.hellowork.mhlw.go.jp/kensaku/GECA110010.do','government',10,'2026-08-10' from public.country_occupation_profiles p where p.country_code='JP' and p.canonical_career_id in ('software-developer','data-analyst','data-engineer','cybersecurity-analyst','network-administrator','cloud-engineer','database-administrator','ict-support-technician')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'source','2022 MHLW occupation classification','https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','government',20,'2026-08-10' from public.country_occupation_profiles p where p.country_code='JP' and p.canonical_career_id in ('software-developer','data-analyst','data-engineer','cybersecurity-analyst','network-administrator','cloud-engineer','database-administrator','ict-support-technician')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'JP:'||o.canonical_career_id,c.source_program_key,case when o.relation_type='direct' then 'direct' else 'related' end,coalesce(o.source_checked_at,'2026-08-10'::date)
from public.program_occupation_jp_staging o
join public.program_catalog_jp_staging c on c.id=o.program_catalog_id
where o.review_status='approved'
  and o.canonical_career_id in ('software-developer','data-analyst','data-engineer','cybersecurity-analyst','network-administrator','cloud-engineer','database-administrator','ict-support-technician')
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;;
