-- Australia Logistics Coordinator profile.
-- OSCA 571131 Logistics Officer explicitly lists Logistics Coordinator as an alternative title.

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at)
values ('AU:logistics-coordinator','AU','logistics-coordinator','Logistics Officer','OSCA','2024 v1.0','5711','AUD',false,'No statutory registration',null,'profile_ready','2026-08-09',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,employment_total,median_weekly_earnings,median_hourly_earnings,annualised_median_salary,all_occupations_median_weekly,part_time_share_pct,female_share_pct,median_age,average_full_time_hours,vacancies_three_month_avg,vacancy_period,vacancy_yoy_pct,employment_growth_5y_pct,employment_growth_10y_pct,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at)
values ('AU:logistics-coordinator','2026-05-01',25900,null,null,null,1852,14,34,42,44,939,'2026-05-01',13.36,4.97,10.73,0,0,5,0,15,0,5,0,5,30,'career-opportunity-v1','provisional',jsonb_build_object(
 'classification_scope','OSCA 571131 Logistics Officer explicitly lists Logistics Coordinator as an alternative title; legacy ANZSCO 591211 is used for exact labour context.',
 'labour_scope','Legacy ANZSCO 591211 reports 25,900 workers, 14% part-time share, 34% female share, median age 42 and 44 average full-time hours. Reviewed exact earnings remain unavailable.',
 'vacancy_scope','Broader ANZSCO 5912 vacancies were 939 in May 2026 versus 828.33 in May 2025, about +13.36% year on year; the broader series receives no intensity or trend credit.',
 'projection_scope','Broader ANZSCO 5912 projections are +4.97% to 2030 and +10.73% to 2035; partial growth credit only.',
 'shortage_note','JSA 2025 OSL records OSCA 571131 Logistics Officer as No Shortage nationally.',
 'visa_basis','No direct current Core Skills Occupation List pathway is assigned to the exact Logistics Coordinator scope.',
 'entry_level_basis','Current verified logistics and supply-chain programs provide direct study routes, while operations experience is also common.',
 'entry_burden_basis','No statutory occupational licence applies.'
),'2026-08-09')
on conflict (profile_key,as_of_date) do update set employment_total=excluded.employment_total,median_weekly_earnings=excluded.median_weekly_earnings,median_hourly_earnings=excluded.median_hourly_earnings,annualised_median_salary=excluded.annualised_median_salary,all_occupations_median_weekly=excluded.all_occupations_median_weekly,part_time_share_pct=excluded.part_time_share_pct,female_share_pct=excluded.female_share_pct,median_age=excluded.median_age,average_full_time_hours=excluded.average_full_time_hours,vacancies_three_month_avg=excluded.vacancies_three_month_avg,vacancy_period=excluded.vacancy_period,vacancy_yoy_pct=excluded.vacancy_yoy_pct,employment_growth_5y_pct=excluded.employment_growth_5y_pct,employment_growth_10y_pct=excluded.employment_growth_10y_pct,shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,legacy_code_system,legacy_code_version,legacy_code,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at)
values ('AU:logistics-coordinator','571131','Logistics Officer / Logistics Coordinator','ANZSCO','2022','591211',null,false,true,1,'https://www.abs.gov.au/statistics/classifications/osca-occupation-standard-classification-australia/2024-version-1-0','2026-08-09')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,legacy_code_system=excluded.legacy_code_system,legacy_code_version=excluded.legacy_code_version,legacy_code=excluded.legacy_code,shortage_rating=excluded.shortage_rating,visa_eligible=excluded.visa_eligible,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_region_metrics (profile_key,region_code,as_of_date,shortage_rating,vacancy_count,source_url) values
('AU:logistics-coordinator','ACT','2026-05-01',null,10.66667,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:logistics-coordinator','NSW','2026-05-01',null,284.66667,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:logistics-coordinator','NT','2026-05-01',null,10,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:logistics-coordinator','QLD','2026-05-01',null,216,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:logistics-coordinator','SA','2026-05-01',null,60.33333,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:logistics-coordinator','TAS','2026-05-01',null,10.33333,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:logistics-coordinator','VIC','2026-05-01',null,207.33333,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:logistics-coordinator','WA','2026-05-01',null,139.66667,'https://www.jobsandskills.gov.au/data/internet-vacancy-index')
on conflict (profile_key,region_code,as_of_date) do update set shortage_rating=excluded.shortage_rating,vacancy_count=excluded.vacancy_count,source_url=excluded.source_url;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,region_code,sort_order,source_checked_at) values
('AU:logistics-coordinator','job_search','SEEK — Logistics Coordinator jobs','https://www.seek.com.au/logistics-coordinator-jobs','private_job_board',null,1,'2026-08-09'),('AU:logistics-coordinator','employer','DHL Careers','https://careers.dhl.com/','transport_logistics',null,1,'2026-08-09'),('AU:logistics-coordinator','employer','Linfox Careers','https://www.linfox.com/careers/','transport_logistics',null,2,'2026-08-09'),('AU:logistics-coordinator','employer','Toll Group Careers','https://www.tollgroup.com/careers','transport_logistics',null,3,'2026-08-09'),('AU:logistics-coordinator','employer','CEVA Logistics Careers','https://www.cevalogistics.com/en/careers','transport_logistics',null,4,'2026-08-09'),('AU:logistics-coordinator','employer','Mainfreight Careers','https://www.mainfreight.com/australia/en-nz/careers','transport_logistics',null,5,'2026-08-09'),('AU:logistics-coordinator','entry_program','UTAS — Bachelor of Global Logistics and Maritime Management','https://www.utas.edu.au/courses/sci-eng/courses/p3e-bachelor-of-global-logistics-and-maritime-management?year=2026','university',null,1,'2026-08-09'),('AU:logistics-coordinator','entry_program','RMIT — Master of Supply Chain and Logistics Management','https://www.rmit.edu.au/study-with-us/levels-of-study/postgraduate-study/masters-by-coursework/master-of-supply-chain-and-logistics-management-mc198','university',null,2,'2026-08-09'),('AU:logistics-coordinator','source','JSA — 2025 Occupation Shortage List','https://www.jobsandskills.gov.au/data/occupation-shortage-analysis/occupation-shortage-list','official_shortage',null,1,'2026-08-09')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,region_code=excluded.region_code,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'AU:logistics-coordinator','au-program:'||id::text,'direct','2026-08-09' from public.courses_au where course_code in ('095526F','077513E')
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;;
