insert into public.country_occupation_profiles (
  profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,
  official_unit_group_code,currency,registration_required,registration_authority,registration_url,
  publication_status,source_checked_at,updated_at
) values
  ('IE:chef','IE','chef','Chefs — experienced professional chef scope','SOC','SOC 2010','5434','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:cook','IE','cook','Cooks','SOC','SOC 2010','5435','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:hotel-manager','IE','hotel-manager','Hotel and accommodation managers and proprietors — hotel manager scope','SOC','SOC 2010','1221','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:restaurant-manager','IE','restaurant-manager','Restaurant and catering establishment managers and proprietors — restaurant manager scope','SOC','SOC 2010','1223','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:baker','IE','baker','Bakers and flour confectioners — Baker scope','SOC','SOC 2010','5432','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:tourism-manager','IE','tourism-manager','Travel agency managers — tourism/travel management scope','SOC','SOC 2010','1226','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:event-planner','IE','event-planner','Conference and exhibition managers and organisers — event-planner scope','SOC','SOC 2010','3546','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:hospitality-supervisor','IE','hospitality-supervisor','Catering and bar managers — front-line hospitality supervision scope','SOC','SOC 2010','5436','EUR',false,null,null,'profile_ready','2026-08-11',now())
on conflict (profile_key) do update set
  official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,
  official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,
  registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,
  source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (
  profile_key,as_of_date,employment_total,median_hourly_earnings,annualised_median_salary,
  shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,
  entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,
  opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at
) values
  ('IE:chef','2026-08-11',null,null,null,20,0,0,0,12,0,0,6,5,43,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 5434 Chefs, with permit treatment bounded to the named experienced chef grades rather than all chef jobs.','shortage_note','SOLAS National Skills Bulletin 2025 directly identifies Chefs as a current Hospitality shortage; 20/20.','visa_basis','SOC 5434 is on the Ineligible List except Executive Chef, Head Chef and Sous Chef with at least 5 years experience, and Chef de Partie or Commis Chef with at least 2 years experience, in establishments other than fast-food outlets. This conditional route is treated as GEP-accessible rather than universal permit eligibility; 6/10.','entry_basis','Ireland has a current Chef de Partie Level 7 apprenticeship and other culinary routes, giving a strong structured work-based pathway; 12/15.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_burden_basis','No universal statutory personal registration requirement; 5/5.'),'2026-08-11'),
  ('IE:cook','2026-08-11',null,null,null,0,0,0,0,12,0,0,0,5,17,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 5435 Cooks, kept separate from the skilled Chef 5434 occupation.','shortage_note','SOLAS 2025 identifies Chefs, not Cooks, as the current Hospitality shortage; no shortage is borrowed; 0/20.','visa_basis','SOC 5435 Cooks is on the current Ineligible List effective 13 May 2026; 0/10.','entry_basis','Practical culinary training and workplace progression make entry comparatively accessible, but this does not change current employment-permit ineligibility; 12/15.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_burden_basis','No universal statutory personal registration requirement; 5/5.'),'2026-08-11'),
  ('IE:hotel-manager','2026-08-11',null,null,null,0,0,0,0,8,0,0,6,5,19,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 1221 Hotel and accommodation managers and proprietors, constrained to genuine hotel/accommodation management.','shortage_note','SOLAS 2025 Hospitality reports sector churn and below-average group growth but only names Chefs as the occupation shortage; 0/20.','visa_basis','Hotel and accommodation managers and proprietors have a renewed General Employment Permit quota in the 2026 occupations review, with Labour Market Needs Test requirements. This is quota-based GEP access, not CSEP; 6/10.','entry_basis','Hospitality-management education or progression from operational hotel roles is common; 8/15.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_burden_basis','No universal statutory personal registration requirement; 5/5.'),'2026-08-11'),
  ('IE:restaurant-manager','2026-08-11',null,null,null,0,0,0,0,8,0,0,6,5,19,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 1223 Restaurant and catering establishment managers and proprietors, restaurant-management scope.','shortage_note','SOLAS 2025 Hospitality names Chefs as the shortage and does not publish an exact Restaurant Manager shortage; 0/20.','visa_basis','Restaurant and catering establishment managers and proprietors have a renewed General Employment Permit quota in the 2026 occupations review, subject to Labour Market Needs Test and other permit requirements; 6/10.','scope_boundary','The manager profile is not collapsed into Cook 5435 or Chef 5434; actual strategic management duties must fit 1223.','entry_basis','Hospitality/restaurant management study or progression from food-and-beverage operations is common; 8/15.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_burden_basis','No universal statutory personal registration requirement; 5/5.'),'2026-08-11'),
  ('IE:baker','2026-08-11',null,null,null,0,0,0,0,10,0,0,6,5,21,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 5432 Bakers and flour confectioners, restricted to Baker employment.','shortage_note','SOLAS 2025 Hospitality identifies Chefs as the current shortage and does not publish an exact Baker shortage; 0/20.','visa_basis','Baker was removed from the Ineligible List in the 2023 occupations expansion. The current 2026 Ineligible List names Flour confectioners under 5432 rather than Baker, so Baker is treated as ordinary GEP-accessible subject to current requirements; 6/10.','scope_boundary','Baker is kept separate from the currently ineligible Flour confectioner employment within the same SOC 5432 group.','entry_basis','Craft/FET bakery and workplace training routes make entry moderately accessible; 10/15.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_burden_basis','No universal statutory personal registration requirement; 5/5.'),'2026-08-11'),
  ('IE:tourism-manager','2026-08-11',null,null,null,0,0,0,0,8,0,0,0,5,13,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 1226 Travel agency managers, constrained to tourism/travel management rather than general tourism marketing or attraction operations.','shortage_note','SOLAS 2025 Arts, Sports and Tourism reports below-average group growth and does not publish an exact Tourism Manager shortage; 0/20.','visa_basis','SOC 1226 Travel agency managers is on the current Ineligible List effective 13 May 2026; 0/10.','scope_boundary','Broader tourism roles may classify differently, but the canonical management profile does not borrow permit access from unrelated hotel or hospitality-manager quota occupations.','entry_basis','Tourism/hospitality/business education plus operational progression is a common route; 8/15.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_burden_basis','No universal statutory personal registration requirement; 5/5.'),'2026-08-11'),
  ('IE:event-planner','2026-08-11',null,null,null,0,0,0,0,8,0,0,0,5,13,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 3546 Conference and exhibition managers and organisers, event-planning scope.','shortage_note','SOLAS 2025 Arts, Sports and Tourism does not publish an exact Event Planner shortage; 0/20.','visa_basis','SOC 3546 Conference and exhibition managers and organisers is on the current Ineligible List effective 13 May 2026; 0/10.','scope_boundary','Event Planner is not promoted into generic project management or marketing occupations to obtain a different permit outcome.','entry_basis','Event, hospitality, tourism, marketing or business study plus practical event delivery experience is common; 8/15.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_burden_basis','No universal statutory personal registration requirement; 5/5.'),'2026-08-11'),
  ('IE:hospitality-supervisor','2026-08-11',null,null,null,0,0,0,0,12,0,0,6,5,23,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 5436 Catering and bar managers, used for front-line hospitality supervision with responsibility for service delivery and staff rather than strategic hotel management.','shortage_note','SOLAS 2025 Hospitality identifies Chefs as the shortage and does not publish an exact hospitality-supervisor shortage; 0/20.','visa_basis','Catering and bar managers are included in the renewed 2026 hospitality-manager General Employment Permit quota, subject to Labour Market Needs Test and current quota/permit conditions; 6/10.','scope_boundary','The canonical supervisor is not promoted to Hotel Manager 1221 or Restaurant Manager 1223 unless the actual job carries the strategic management duties required by those groups.','entry_basis','Hospitality commonly supports rapid workplace progression from front-line roles to team leader and supervisor, with Fáilte Ireland training available for operational and leadership development; 12/15.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_burden_basis','No universal statutory personal registration requirement; 5/5.'),'2026-08-11')
on conflict (profile_key,as_of_date) do update set
  employment_total=excluded.employment_total,median_hourly_earnings=excluded.median_hourly_earnings,annualised_median_salary=excluded.annualised_median_salary,
  shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,
  entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,
  opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

delete from public.country_occupation_specialisations where profile_key in ('IE:chef','IE:cook','IE:hotel-manager','IE:restaurant-manager','IE:baker','IE:tourism-manager','IE:event-planner','IE:hospitality-supervisor');
insert into public.country_occupation_specialisations (profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
  ('IE:chef','5434','Chefs — named experienced chef permit-exception scope',20,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/ineligible-categories-of-employment/','2026-08-11'),
  ('IE:cook','5435','Cooks',null,false,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/ineligible-categories-of-employment/','2026-08-11'),
  ('IE:hotel-manager','1221','Hotel and accommodation managers and proprietors — hotel manager scope',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/latest-updates/','2026-08-11'),
  ('IE:restaurant-manager','1223','Restaurant and catering establishment managers and proprietors — restaurant manager scope',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/latest-updates/','2026-08-11'),
  ('IE:baker','5432','Bakers and flour confectioners — Baker scope',null,true,true,1,'https://enterprise.gov.ie/en/news-and-events/department-news/2023/december/20122023.html','2026-08-11'),
  ('IE:tourism-manager','1226','Travel agency managers — tourism/travel management scope',null,false,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/ineligible-categories-of-employment/','2026-08-11'),
  ('IE:event-planner','3546','Conference and exhibition managers and organisers — event-planner scope',null,false,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/ineligible-categories-of-employment/','2026-08-11'),
  ('IE:hospitality-supervisor','5436','Catering and bar managers — front-line hospitality supervision scope',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/latest-updates/','2026-08-11');

delete from public.country_occupation_links where profile_key in ('IE:chef','IE:cook','IE:hotel-manager','IE:restaurant-manager','IE:baker','IE:tourism-manager','IE:event-planner','IE:hospitality-supervisor');
insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,region_code,sort_order,source_checked_at) values
  ('IE:chef','source','SOLAS — Hospitality labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/hospitality/','government',null,1,'2026-08-11'),
  ('IE:chef','source','DETE — current Ineligible List and chef exceptions','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/ineligible-categories-of-employment/','government',null,2,'2026-08-11'),
  ('IE:chef','source','DETE — restaurant and take-away employment permit policy','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/restaurants-and-take-aways/','government',null,3,'2026-08-11'),
  ('IE:chef','entry_program','Generation Apprenticeship — Chef de Partie Level 7','https://www.apprenticeship.ie/career-seekers/get-started/next-steps/hospitality-food/chef-de-partie-l7','government',null,4,'2026-08-11'),
  ('IE:cook','source','SOLAS — Hospitality labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/hospitality/','government',null,1,'2026-08-11'),
  ('IE:cook','source','DETE — current Ineligible List','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/ineligible-categories-of-employment/','government',null,2,'2026-08-11'),
  ('IE:hotel-manager','source','SOLAS — Hospitality labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/hospitality/','government',null,1,'2026-08-11'),
  ('IE:hotel-manager','source','DETE — 2026 renewed hospitality-manager permit quota','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/latest-updates/','government',null,2,'2026-08-11'),
  ('IE:hotel-manager','entry_program','Fáilte Ireland — tourism careers and hospitality management progression','https://www.failteireland.ie/en/employer-excellence-programme/careers-growth-and-opportunity','government',null,3,'2026-08-11'),
  ('IE:restaurant-manager','source','SOLAS — Hospitality labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/hospitality/','government',null,1,'2026-08-11'),
  ('IE:restaurant-manager','source','DETE — 2026 renewed hospitality-manager permit quota','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/latest-updates/','government',null,2,'2026-08-11'),
  ('IE:restaurant-manager','source','DETE — restaurant and take-away employment permit policy','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/restaurants-and-take-aways/','government',null,3,'2026-08-11'),
  ('IE:baker','source','SOLAS — Hospitality labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/hospitality/','government',null,1,'2026-08-11'),
  ('IE:baker','source','DETE — current Ineligible List distinguishes Flour confectioner','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/ineligible-categories-of-employment/','government',null,2,'2026-08-11'),
  ('IE:baker','source','DETE — Baker removed from Ineligible List in 2023 expansion','https://enterprise.gov.ie/en/news-and-events/department-news/2023/december/20122023.html','government',null,3,'2026-08-11'),
  ('IE:tourism-manager','source','SOLAS — Arts, Sports and Tourism labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/arts-sports-and-tourism/','government',null,1,'2026-08-11'),
  ('IE:tourism-manager','source','DETE — current Ineligible List','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/ineligible-categories-of-employment/','government',null,2,'2026-08-11'),
  ('IE:tourism-manager','entry_program','Fáilte Ireland — learniFI tourism and management training','https://www.failteireland.ie/en/info/learnifi','government',null,3,'2026-08-11'),
  ('IE:event-planner','source','SOLAS — Arts, Sports and Tourism labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/arts-sports-and-tourism/','government',null,1,'2026-08-11'),
  ('IE:event-planner','source','DETE — current Ineligible List','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/ineligible-categories-of-employment/','government',null,2,'2026-08-11'),
  ('IE:event-planner','entry_program','Fáilte Ireland — learniFI tourism and event-sector training','https://www.failteireland.ie/en/info/learnifi','government',null,3,'2026-08-11'),
  ('IE:hospitality-supervisor','source','SOLAS — Hospitality labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/hospitality/','government',null,1,'2026-08-11'),
  ('IE:hospitality-supervisor','source','DETE — 2026 renewed catering and bar manager permit quota','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/latest-updates/','government',null,2,'2026-08-11'),
  ('IE:hospitality-supervisor','entry_program','Fáilte Ireland — workplace progression and hospitality leadership','https://www.failteireland.ie/en/employer-excellence-programme/careers-growth-and-opportunity','government',null,3,'2026-08-11');

delete from public.country_occupation_program_links where profile_key in ('IE:chef','IE:cook','IE:hotel-manager','IE:restaurant-manager','IE:baker','IE:tourism-manager','IE:event-planner','IE:hospitality-supervisor');;
