-- Japan Transport / Logistics occupation cohort.
-- Classification basis: 2022 revision of the Ministry of Health, Labour and Welfare occupation classification.

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('JP:truck-driver','JP','truck-driver','トラック運転手 — freight-truck class umbrella','MHLW Occupation Classification','2022',null,'JPY',true,'都道府県公安委員会 — vehicle-class driver licence','https://www.npa.go.jp/bureau/traffic/menkyo/index.html','profile_ready','2026-08-11',now()),
('JP:logistics-coordinator','JP','logistics-coordinator','物流コーディネーター — shipping/receiving and dispatch coordination umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-11',now()),
('JP:aircraft-maintenance-technician','JP','aircraft-maintenance-technician','航空整備士・航空機整備技術者','MHLW Occupation Classification','2022','075-04','JPY',true,'国土交通省 航空局 — 航空従事者技能証明（航空整備士）','https://www.mlit.go.jp/koku/15_bf_000299.html','profile_ready','2026-08-11',now()),
('JP:commercial-pilot','JP','commercial-pilot','航空機操縦士 — commercial pilot scope','MHLW Occupation Classification','2022','087-04','JPY',true,'国土交通省 航空局 — 航空従事者技能証明（事業用・定期運送用操縦士）','https://www.mlit.go.jp/koku/15_bf_000299.html','profile_ready','2026-08-11',now()),
('JP:marine-engineer','JP','marine-engineer','船舶機関士','MHLW Occupation Classification','2022','087-03','JPY',true,'国土交通省 海事局 — 海技士（機関）','https://www.mlit.go.jp/maritime/maritime_tk10_000006.html','profile_ready','2026-08-11',now()),
('JP:deck-officer','JP','deck-officer','航海士','MHLW Occupation Classification','2022','087-02','JPY',true,'国土交通省 海事局 — 海技士（航海）','https://www.mlit.go.jp/maritime/maritime_tk10_000006.html','profile_ready','2026-08-11',now()),
('JP:warehouse-manager','JP','warehouse-manager','倉庫管理者 — management/warehouse-administration/operations umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-11',now()),
('JP:automotive-service-technician','JP','automotive-service-technician','自動車整備・修理工','MHLW Occupation Classification','2022','075-03','JPY',false,null,null,'profile_ready','2026-08-11',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at) values
('JP:truck-driver','2026-08-11',0,0,0,0,15,0,0,0,2,17,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','Truck Driver spans MHLW 083-01 large truck, 083-02 medium/small truck, 083-03 tractor-trailer, 083-04 dump truck and 083-99 other freight-truck driving rather than one exact small classification.','entry_level_basis','This is primarily a vehicle-licence and employer-training pathway rather than an academic occupation.','qualification_note','Driving requires the licence class appropriate to the vehicle. Higher truck classes and articulated vehicles can require staged licence experience and a separate towing licence.','market_scope','The freight-truck classes are preserved separately and are not merged into one fabricated exact market series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('JP:logistics-coordinator','2026-08-11',0,0,0,0,15,0,0,0,5,20,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','Logistics Coordinator spans 039-02 shipping/receiving and warehouse administration plus 042-02 transport-operation dispatch/coordination where vehicle scheduling is central.','entry_level_basis','Operations, logistics or supply-chain study can help, but many roles are entered through shipping, warehouse or transport-office experience; the one reviewed Japanese programme is related.','qualification_note','No universal statutory Logistics Coordinator licence applies. Regulated transport-operation-manager duties are narrower than the canonical role and are not promoted into a blanket requirement.','market_scope','Administrative shipping/receiving and transport dispatch classifications are not merged into an exact logistics-coordinator market series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('JP:aircraft-maintenance-technician','2026-08-11',0,0,0,0,10,0,0,0,1,11,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','MHLW 075-04 includes aircraft maintenance and repair work within transport-equipment maintenance excluding automobiles.','entry_level_basis','Aviation-maintenance vocational or technical study plus practical experience is the common route; one approved Japanese aircraft-maintenance programme is direct.','qualification_note','MHLW job tag states that the national aircraft-maintenance qualification under the Civil Aeronautics Act is required for the 航空整備士 occupation, with licence class and aircraft-category limitations.','market_scope','075-04 also covers other non-automotive transport equipment, so its group statistics are not treated as exact aircraft-maintenance observations.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('JP:commercial-pilot','2026-08-11',0,0,0,0,8,0,0,0,1,9,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','MHLW 087-04 directly classifies aircraft pilots and includes airline and other professional aircraft-operation scopes.','entry_level_basis','Commercial flying requires structured flight training, aeronautical experience, examinations, flight testing and medical fitness; there are currently no approved Japan programme links in the reviewed programme staging for this canonical career.','qualification_note','Paid commercial aircraft operation requires the applicable MLIT aviation personnel skill certificate; airline command requires the higher airline transport pilot qualification and pilots also face medical-certificate requirements.','market_scope','Pilot market evidence is deferred even though current official sources publish occupation information, to keep scoring comparable with the later cross-country enrichment phase.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('JP:marine-engineer','2026-08-11',0,0,0,0,8,0,0,0,1,9,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','MHLW 087-03 directly covers ship chief engineers and engineer officers on non-fishing vessels.','entry_level_basis','Maritime engineering education, approved training and documented sea service lead toward engineer-officer work; the reviewed Osaka maritime programme is retained as related rather than automatic licence qualification.','qualification_note','Serving as a ship engineer officer requires the applicable 海技士（機関） certificate under Japan maritime qualification law, with class and vessel-duty limits.','market_scope','No market score is assigned in this foundation phase despite available maritime-industry context.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('JP:deck-officer','2026-08-11',0,0,0,0,8,0,0,0,1,9,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','MHLW 087-02 directly covers masters, deck/navigation officers and operations officers on non-fishing vessels, plus pilots; CampCareer restricts this canonical profile to deck/navigation officer scope.','entry_level_basis','Nautical education, approved training and documented sea service are standard foundations for deck-officer qualification; no reviewed Japan programme link is currently approved for this canonical career.','qualification_note','Serving as a deck/navigation officer requires the applicable 海技士（航海） certificate under Japan maritime qualification law, with grade and vessel-duty limits.','market_scope','The official classification also contains masters and maritime pilots, so group-level data are not treated as exact Deck Officer observations.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('JP:warehouse-manager','2026-08-11',0,0,0,0,10,0,0,0,5,15,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','Warehouse Manager has no single MHLW small code: higher organisational management can fall under 002-01, warehouse administration and inventory control under 039-02, and hands-on warehouse operations under 095-03.','entry_level_basis','Warehouse management is commonly reached through logistics or warehouse operations experience plus supervisory responsibility; the one reviewed Japanese programme is related.','qualification_note','No universal personal Warehouse Manager licence applies. 倉庫管理主任者 and other designated credentials can apply to particular warehousing businesses or responsibilities without licensing the entire occupation.','market_scope','Management, warehouse administration and physical warehouse work are not aggregated into one fabricated exact market series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('JP:automotive-service-technician','2026-08-11',0,0,0,0,12,0,0,0,4,16,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','MHLW 075-03 directly covers automotive inspection, servicing and repair work including mechanics and automotive electrical repair.','entry_level_basis','Automotive vocational study is common, but MHLW job tag explicitly notes that employment at a repair workshop is possible before obtaining the national automotive-mechanic qualification; three reviewed university automotive programmes are related rather than trade-qualification pathways.','qualification_note','The national 自動車整備士 qualification is valuable and required for specified higher-responsibility work, but it is not a universal personal licence required merely to enter every automotive service technician job.','market_scope','075-03 is a strong occupational match, but market and salary components remain deferred for consistency with the common enrichment phase.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11')
on conflict (profile_key,as_of_date) do update set shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('JP:truck-driver','083-01','大型トラック運転手',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-11'),
('JP:truck-driver','083-02','中型・小型トラック運転手',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-11'),
('JP:truck-driver','083-03','トレーラートラック運転手',null,null,false,3,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-11'),
('JP:truck-driver','083-04','ダンプカー運転手',null,null,false,4,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-11'),
('JP:truck-driver','083-99','その他の貨物自動車運転の職業',null,null,false,5,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-11'),
('JP:logistics-coordinator','039-02','出荷・受荷係事務員 — shipping/receiving and warehouse coordination scope',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-11'),
('JP:logistics-coordinator','042-02','運行管理事務員 — dispatch/transport coordination scope',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-11'),
('JP:aircraft-maintenance-technician','075-04','輸送用機械器具整備・修理工（自動車を除く） — aircraft maintenance scope',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-11'),
('JP:commercial-pilot','087-04','航空機操縦士',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-11'),
('JP:marine-engineer','087-03','船舶機関長・機関士（漁労船を除く） — marine engineer scope',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-11'),
('JP:deck-officer','087-02','船長・航海士・運航士（漁労船を除く）、水先人 — deck officer scope',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-11'),
('JP:warehouse-manager','002-01','会社管理職員 — warehouse organisational-management scope',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-11'),
('JP:warehouse-manager','039-02','出荷・受荷係事務員 — warehouse administration/inventory scope',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-11'),
('JP:warehouse-manager','095-03','倉庫作業員 — warehouse operations reference',null,null,false,3,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-11'),
('JP:automotive-service-technician','075-03','自動車整備・修理工',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-11')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'job_search','Hello Work job search','https://www.hellowork.mhlw.go.jp/kensaku/GECA110010.do','government',10,'2026-08-11' from public.country_occupation_profiles p where p.country_code='JP' and p.canonical_career_id in ('truck-driver','logistics-coordinator','aircraft-maintenance-technician','commercial-pilot','marine-engineer','deck-officer','warehouse-manager','automotive-service-technician')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'source','MHLW 2022 occupation classification','https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','government',20,'2026-08-11' from public.country_occupation_profiles p where p.country_code='JP' and p.canonical_career_id in ('truck-driver','logistics-coordinator','aircraft-maintenance-technician','commercial-pilot','marine-engineer','deck-officer','warehouse-manager','automotive-service-technician')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'JP:'||o.canonical_career_id,c.source_program_key,case when o.relation_type='direct' then 'direct' else 'related' end,coalesce(o.source_checked_at,'2026-08-11'::date)
from public.program_occupation_jp_staging o join public.program_catalog_jp_staging c on c.id=o.program_catalog_id
where o.review_status='approved' and o.canonical_career_id in ('truck-driver','logistics-coordinator','aircraft-maintenance-technician','commercial-pilot','marine-engineer','deck-officer','warehouse-manager','automotive-service-technician')
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;;
