-- Publish verified Netherlands country metrics through the shared evidence layer.

insert into core.countries (code, name, default_currency, active, updated_at)
values ('NL', 'Netherlands', 'EUR', true, now())
on conflict (code) do update set name=excluded.name, default_currency=excluded.default_currency, active=true, updated_at=now();

with incoming(source_key, organisation_name, source_name, source_type, source_url, data_as_of, metadata) as (values
('nl_cbs_employment_wages_2025','Statistics Netherlands','Employment, wages and working hours, 2025 provisional','government_dataset','https://www.cbs.nl/en-gb/figures/detail/81462ENG',date '2025-12-31','{"table_updated":"2026-04-21","published_values_rounded":true,"national_total_jobs_thousands":9167,"national_part_time_jobs_thousands":5152,"national_total_average_annual_wage_eur":47360,"national_part_time_average_annual_wage_eur":30270}'::jsonb),
('nl_study_in_nl_living_2026','Nuffic','Daily student expenses and cost of living in the Netherlands','provider','https://www.studyinnl.org/finances/daily-student-expenses-and-cost-of-living-in-the-netherlands',date '2026-08-06','{"ind_2026_study_norm_monthly_eur":1130.77,"ind_source_url":"https://ind.nl/en/required-amounts-income-requirements"}'::jsonb),
('nl_study_in_nl_tuition_2026','Nuffic','Tuition fees','provider','https://www.studyinnl.org/finances/tuition-fees',date '2026-08-06','{"student_type":"non-EU/EEA","study_level":"bachelor"}'::jsonb),
('nl_minimum_wage_july_2026','Government of the Netherlands','Minimum wage amounts','regulator','https://www.government.nl/themes/work/minimum-wage/minimum-wage-amounts',date '2026-07-01','{"age_basis":"21 and older"}'::jsonb),
('nl_ind_study_fee_2026','Immigration and Naturalisation Service','Fees: costs of an application','regulator','https://ind.nl/en/fees-costs-of-an-application',date '2026-01-01','{"application_type":"Study, all education levels"}'::jsonb),
('nl_ind_student_work_2026','Immigration and Naturalisation Service','Student residence permit for university or higher professional education','regulator','https://ind.nl/en/residence-permits/study/student-residence-permit-for-university-or-higher-professional-education',date '2026-08-06','{"employment_permit_required":true,"permit_type":"TWV"}'::jsonb)
)
insert into evidence.sources (source_key, organisation_name, source_name, source_type, canonical_url, country_code, active, updated_at)
select source_key, organisation_name, source_name, source_type, source_url, 'NL', true, now() from incoming
on conflict (source_key) do update set organisation_name=excluded.organisation_name, source_name=excluded.source_name, source_type=excluded.source_type, canonical_url=excluded.canonical_url, country_code='NL', active=true, updated_at=now();

with incoming(source_key, organisation_name, source_name, source_type, source_url, data_as_of, metadata) as (values
('nl_cbs_employment_wages_2025','Statistics Netherlands','Employment, wages and working hours, 2025 provisional','government_dataset','https://www.cbs.nl/en-gb/figures/detail/81462ENG',date '2025-12-31','{"table_updated":"2026-04-21","published_values_rounded":true,"national_total_jobs_thousands":9167,"national_part_time_jobs_thousands":5152,"national_total_average_annual_wage_eur":47360,"national_part_time_average_annual_wage_eur":30270}'::jsonb),
('nl_study_in_nl_living_2026','Nuffic','Daily student expenses and cost of living in the Netherlands','provider','https://www.studyinnl.org/finances/daily-student-expenses-and-cost-of-living-in-the-netherlands',date '2026-08-06','{"ind_2026_study_norm_monthly_eur":1130.77,"ind_source_url":"https://ind.nl/en/required-amounts-income-requirements"}'::jsonb),
('nl_study_in_nl_tuition_2026','Nuffic','Tuition fees','provider','https://www.studyinnl.org/finances/tuition-fees',date '2026-08-06','{"student_type":"non-EU/EEA","study_level":"bachelor"}'::jsonb),
('nl_minimum_wage_july_2026','Government of the Netherlands','Minimum wage amounts','regulator','https://www.government.nl/themes/work/minimum-wage/minimum-wage-amounts',date '2026-07-01','{"age_basis":"21 and older"}'::jsonb),
('nl_ind_study_fee_2026','Immigration and Naturalisation Service','Fees: costs of an application','regulator','https://ind.nl/en/fees-costs-of-an-application',date '2026-01-01','{"application_type":"Study, all education levels"}'::jsonb),
('nl_ind_student_work_2026','Immigration and Naturalisation Service','Student residence permit for university or higher professional education','regulator','https://ind.nl/en/residence-permits/study/student-residence-permit-for-university-or-higher-professional-education',date '2026-08-06','{"employment_permit_required":true,"permit_type":"TWV"}'::jsonb)
)
insert into evidence.source_snapshots (source_id, source_url, data_as_of, retrieved_at, snapshot_status, metadata)
select s.id, i.source_url, i.data_as_of, now(), 'captured', i.metadata
from incoming i join evidence.sources s on s.source_key=i.source_key
where not exists (select 1 from evidence.source_snapshots x where x.source_id=s.id and x.source_url=i.source_url and x.data_as_of=i.data_as_of);

delete from evidence.metric_observations where scope_type='country' and scope_id='NL' and metric_key in ('full_time_annual_earnings_range','average_annual_salary','student_living_cost_monthly_range','tuition_annual_low','tuition_annual_high','national_minimum_hourly_wage','visa_application_fee','student_work_hours_limit');

with incoming(metric_key, source_key, value, unit, evidence_kind, confidence, methodology, assumptions, effective_from, reviewer_note) as (values
('full_time_annual_earnings_range','nl_cbs_employment_wages_2025','{"low":62730,"high":72950,"ranking_value":69290,"currency":"EUR","basis":"derived_full_time_average_annual_wage_by_employer_size","population":"full-time employee jobs across three employer-size groups","measure_type":"employer_size_average_range","includes_bonuses":true}'::jsonb,'EUR/year','calculated','medium','Full-time averages are derived from CBS total-job and part-time-job counts and average annual wages using weighted subtraction. The displayed bounds are the minimum and maximum derived averages across 0–9, 10–99 and 100+ employee organisations.','{"not_individual_worker_distribution":true,"rounded_source_aggregates":true,"source_estimates_provisional":true}'::jsonb,date '2025-12-31','Verified approximate full-time employer-size salary range for the Netherlands dashboard.'),
('average_annual_salary','nl_cbs_employment_wages_2025','{"amount":69290,"currency":"EUR","basis":"derived_national_full_time_average_annual_wage","statistic_type":"mean","population":"full-time employee jobs","includes_bonuses":true}'::jsonb,'EUR/year','calculated','medium','Approximate national full-time annual wage derived from CBS total and part-time aggregate job counts and annual wages.','{"job_based_not_person_based":true,"rounded_source_aggregates":true,"source_estimates_provisional":true}'::jsonb,date '2025-12-31','Verified approximate national full-time annual earnings benchmark.'),
('student_living_cost_monthly_range','nl_study_in_nl_living_2026','{"low":1000,"high":1500,"ranking_value":1250,"currency":"EUR","basis":"published_student_monthly_spending_range","scenario":"one student; housing, food, transport and personal costs; tuition excluded","measure_type":"national_planning_range","ind_2026_study_norm_monthly":1130.77}'::jsonb,'EUR/month','observed','medium','Study in NL publishes a broad average monthly student-cost range. The IND study norm is stored as a secondary official financial-requirement reference.','{"tuition_excluded":true,"city_and_housing_variation_material":true,"ind_requirement_is_not_spending_forecast":true}'::jsonb,date '2026-08-06','Verified current national student planning range.'),
('tuition_annual_low','nl_study_in_nl_tuition_2026','{"amount":9000,"currency":"EUR","basis":"published_average_non_eu_bachelor_range","study_level":"bachelor","student_type":"non-EU/EEA"}'::jsonb,'EUR/year','observed','medium','Lower bound of the Study in NL average tuition range for non-EU/EEA bachelor programmes.','{"course_specific_fee_required_for_decision":true}'::jsonb,date '2026-08-06','Verified national planning lower bound.'),
('tuition_annual_high','nl_study_in_nl_tuition_2026','{"amount":20000,"currency":"EUR","basis":"published_average_non_eu_bachelor_range","study_level":"bachelor","student_type":"non-EU/EEA"}'::jsonb,'EUR/year','observed','medium','Upper bound of the Study in NL average tuition range for non-EU/EEA bachelor programmes.','{"course_specific_fee_required_for_decision":true}'::jsonb,date '2026-08-06','Verified national planning upper bound.'),
('national_minimum_hourly_wage','nl_minimum_wage_july_2026','{"amount":14.99,"currency":"EUR","employee_basis":"statutory_minimum_wage_age_21_and_older"}'::jsonb,'EUR/hour','observed','high','Statutory minimum hourly wage for employees aged 21 and older from 1 July 2026.','{"younger_worker_rates_differ":true}'::jsonb,date '2026-07-01','Verified current adult statutory hourly floor.'),
('visa_application_fee','nl_ind_study_fee_2026','{"amount":254,"currency":"EUR","fee_type":"first_study_residence_permit_application","visa_type":"Study, all education levels"}'::jsonb,'EUR','observed','high','IND fee for a first study residence permit application or change of purpose in 2026.','{"institution_service_fees_excluded":true}'::jsonb,date '2026-01-01','Verified current study residence permit application fee.'),
('student_work_hours_limit','nl_ind_student_work_2026','{"hours":16,"period":"week","visa_type":"study residence permit","applies_during":"chosen weekly employment option","summer_full_time_months":["June","July","August"],"employment_permit_required":true,"employment_permit_type":"TWV"}'::jsonb,'hours/week','observed','high','Non-EEA students working as employees choose either up to 16 hours per week or full-time work in June, July and August. The employer must hold a TWV.','{"eu_eea_swiss_rules_differ":true,"self_employment_rules_differ":true,"visa_conditions_control":true}'::jsonb,date '2026-08-06','Verified current employee-work limit for study residence permit holders.')
), latest_snapshots as (
  select distinct on (s.source_key) s.source_key, ss.id
  from evidence.sources s join evidence.source_snapshots ss on ss.source_id=s.id
  where s.source_key in (select source_key from incoming)
  order by s.source_key, ss.retrieved_at desc
)
insert into evidence.metric_observations (metric_key, scope_type, scope_id, value, unit, source_snapshot_id, evidence_kind, confidence, methodology, assumptions, effective_from, review_status, reviewed_at, reviewer_note)
select i.metric_key, 'country', 'NL', i.value, i.unit, l.id, i.evidence_kind, i.confidence, i.methodology, i.assumptions, i.effective_from, 'verified', now(), i.reviewer_note
from incoming i join latest_snapshots l on l.source_key=i.source_key;

delete from public.report_metric_evidence_country where scope_type='country' and scope_id='NL' and metric_key in ('full_time_annual_earnings_range','average_annual_salary','student_living_cost_monthly_range','tuition_annual_low','tuition_annual_high','national_minimum_hourly_wage','visa_application_fee','student_work_hours_limit');

insert into public.report_metric_evidence_country (scope_type, scope_id, metric_key, value, source_name, source_url, data_as_of, last_verified_at, confidence, evidence_kind, review_status, created_at, updated_at)
select o.scope_type, o.scope_id, o.metric_key, o.value, s.source_name, ss.source_url, coalesce(ss.data_as_of,o.effective_from,current_date), coalesce(o.reviewed_at,o.updated_at,now()), o.confidence, o.evidence_kind, o.review_status, o.created_at, o.updated_at
from evidence.metric_observations o
join evidence.source_snapshots ss on ss.id=o.source_snapshot_id
join evidence.sources s on s.id=ss.source_id
where o.scope_type='country' and o.scope_id='NL' and o.review_status='verified' and o.metric_key in ('full_time_annual_earnings_range','average_annual_salary','student_living_cost_monthly_range','tuition_annual_low','tuition_annual_high','national_minimum_hourly_wage','visa_application_fee','student_work_hours_limit');;
