insert into public.country_occupation_profiles (
  profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,
  official_unit_group_code,currency,registration_required,registration_authority,registration_url,
  publication_status,source_checked_at,updated_at
) values
  ('IE:environmental-scientist','IE','environmental-scientist','Environment professionals — environmental scientist scope','SOC','SOC 2010','2142','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:agronomist','IE','agronomist','Biological scientists and biochemists — Agronomist','SOC','SOC 2010','2112','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:farm-manager','IE','farm-manager','Managers and proprietors in agriculture and horticulture — farm manager scope','SOC','SOC 2010','1211','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:forestry-technician','IE','forestry-technician','Other agricultural and fishing trades n.e.c. — speciality forestry harvesting technician scope','SOC','SOC 2010','5119','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:food-technologist','IE','food-technologist','Engineering professionals n.e.c. — Food Technologist scope','SOC','SOC 2010','2129','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:sustainability-specialist','IE','sustainability-specialist','Environment professionals — sustainability specialist scope','SOC','SOC 2010','2142','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:horticulturist','IE','horticulturist','Horticultural trades — practical horticulturist scope','SOC','SOC 2010','5112','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:animal-science-technician','IE','animal-science-technician','Laboratory technicians — animal-science / laboratory animal-technician scope','SOC','SOC 2010','3111','EUR',false,null,null,'profile_ready','2026-08-11',now())
on conflict (profile_key) do update set
  official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,
  official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,
  registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,
  source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (
  profile_key,as_of_date,employment_total,median_hourly_earnings,annualised_median_salary,
  shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,
  entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,
  opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at
) values
  ('IE:environmental-scientist','2026-08-11',null,null,null,0,0,0,0,8,0,0,6,5,19,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 2142 Environment professionals, constrained to environmental-scientist work.','shortage_note','SOLAS 2025 reports strong green-transition demand for scientists and engineers but does not publish an exact Environmental Scientist shortage in the reviewed summary; 0/20.','visa_basis','SOC 2142 is not explicitly on the current Critical Skills list and was not identified on the current Ineligible list; ordinary GEP access may apply subject to employer and permit conditions; 6/10.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_basis','Degree-level environmental science or related science routes are common; 8/15.','entry_burden_basis','No universal statutory personal registration requirement is applied to the broad occupation; 5/5.'),'2026-08-11'),
  ('IE:agronomist','2026-08-11',null,null,null,20,0,0,0,8,0,0,10,5,43,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 2112 Biological scientists and biochemists, exact Agronomist employment.','shortage_note','Agronomist was added to the Critical Skills Occupations List following the 2026 employment-permit occupations review addressing current skills shortages; exact direct shortage credit 20/20.','visa_basis','Agronomist is explicitly listed under SOC 2112 on the current Critical Skills Occupations List effective 13 May 2026; 10/10.','scope_boundary','The exact Agronomist employment is used; broader biological-scientist or food-manufacturing scientist specialisms are not substituted.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_basis','Agricultural-science/agronomy degree and professional experience routes are typical; 8/15.','entry_burden_basis','No universal statutory personal registration is required for the broad Agronomist occupation; 5/5.'),'2026-08-11'),
  ('IE:farm-manager','2026-08-11',null,null,null,0,0,0,0,12,0,0,6,5,23,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 1211 Managers and proprietors in agriculture and horticulture, constrained to farm-management duties.','shortage_note','SOLAS 2025 reports low recent employment growth across Agriculture & Animal Care and does not publish an exact Farm Manager shortage in the reviewed summary; 0/20.','visa_basis','Professional/managerial SOC 1211 is kept separate from hands-on Farmers SOC 5111, which is on the Ineligible List except Pig Manager. SOC 1211 is not explicitly Critical Skills or ineligible, so ordinary GEP access may apply subject to conditions; 6/10.','entry_basis','Teagasc operates a current Level 7 Farm Manager Apprenticeship with paid employment through a SOLAS-approved employer; 12/15.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_burden_basis','No universal statutory personal registration; 5/5.'),'2026-08-11'),
  ('IE:forestry-technician','2026-08-11',null,null,null,0,0,0,0,12,0,0,6,5,23,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 5119 skilled agricultural/forestry trade scope, specifically the current speciality forestry harvesting technician permit exception.','shortage_note','No exact current SOLAS Forestry Technician shortage finding is used; 0/20.','visa_basis','SOC 5119 is generally ineligible, but the current Ineligible List explicitly excepts speciality forestry harvesting technician. This exact exception scope receives ordinary GEP accessibility 6/10; generic forestry work is not treated as eligible by default.','csep_boundary','Professional Forester under SOC 1213 is a separate current Critical Skills employment and is not borrowed by the canonical Forestry Technician.','entry_basis','Teagasc Level 5 Certificate in Forestry plus Level 6 Advanced Certificate in Forestry is a direct structured pathway into forestry employment/supervision; 12/15.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_burden_basis','No universal statutory personal registration for this technician scope; 5/5.'),'2026-08-11'),
  ('IE:food-technologist','2026-08-11',null,null,null,0,0,0,0,8,0,0,6,5,19,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 2129 Engineering professionals n.e.c., Food Technologist scope.','shortage_note','SOLAS 2025 identifies analytical/process scientists and selected engineering shortages, but the reviewed summary does not publish an exact Food Technologist shortage; 0/20.','visa_basis','The current CSEP list has specialist 2112 food-manufacturing biological scientists and specified 2129 employments, but does not name generic Food Technologist. The canonical 2129 Food Technologist therefore receives ordinary GEP access rather than borrowed CSEP credit; 6/10.','scope_boundary','Food Technologist is not silently reclassified as a 2112 manufacturing biological scientist solely to gain Critical Skills treatment.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_basis','Degree-level food science/technology and related industry routes are common; 8/15.','entry_burden_basis','No universal statutory personal registration for the broad occupation; 5/5.'),'2026-08-11'),
  ('IE:sustainability-specialist','2026-08-11',null,null,null,0,0,0,0,8,0,0,6,5,19,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 2142 Environment professionals, sustainability-specialist scope.','shortage_note','SOLAS expects the green agenda to sustain demand for science/engineering capability, but this is contextual demand and not an exact Sustainability Specialist shortage finding; 0/20.','visa_basis','SOC 2142 is not explicitly on the current Critical Skills list and was not identified on the current Ineligible list; ordinary GEP access may apply subject to conditions; 6/10.','scope_boundary','Broad ESG, environmental-management and sustainability duties are not promoted to Professional Forester, engineer or other CSEP codes without matching duties.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_basis','Degree/postgraduate routes in sustainability, environment, business or engineering plus applied experience are common; 8/15.','entry_burden_basis','No universal statutory personal registration; 5/5.'),'2026-08-11'),
  ('IE:horticulturist','2026-08-11',null,null,null,0,0,0,0,12,0,0,0,5,17,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 5112 Horticultural trades, practical horticulturist scope.','shortage_note','SOLAS 2025 Agriculture & Animal Care reports job churn but almost no employment growth since 2023 and does not publish an exact Horticulturist shortage in the reviewed summary; 0/20.','visa_basis','SOC 5112 Horticultural trades is on the current Ineligible List effective 13 May 2026; 0/10.','scope_boundary','The practical canonical Horticulturist is not promoted to the professional biological-scientist classification simply to obtain a different permit outcome.','entry_basis','Teagasc operates a current Horticulturist Apprenticeship at NFQ Level 6 and Level 5/6 horticulture programmes; 12/15.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_burden_basis','No universal statutory personal registration; 5/5.'),'2026-08-11'),
  ('IE:animal-science-technician','2026-08-11',null,null,null,10,0,0,0,10,0,0,6,5,31,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 3111 Laboratory technicians, constrained to animal-science / laboratory animal technical work rather than general animal care.','shortage_note','SOLAS 2025 directly identifies lab technicians among current Science & Engineering shortages. Because the canonical Animal Science Technician is narrower than the published lab-technician group, partial credit 10/20 is used.','visa_basis','SOC 3111 is not explicitly on the current Critical Skills list and was not identified on the current Ineligible list; ordinary GEP access may apply subject to conditions; 6/10.','scope_boundary','General animal-care, veterinary-nursing and farm-worker roles are not rolled into this laboratory/research technical profile.','entry_basis','SOLAS Laboratory Assistant traineeship is a verified related technical route with food chemistry, microbiology and soil science; it is not labelled an exact Animal Science Technician apprenticeship; 10/15.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_burden_basis','No universal statutory personal registration for this non-clinical technical scope; 5/5.'),'2026-08-11')
on conflict (profile_key,as_of_date) do update set
  employment_total=excluded.employment_total,median_hourly_earnings=excluded.median_hourly_earnings,annualised_median_salary=excluded.annualised_median_salary,
  shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,
  entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,
  opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (
  profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at
) values
  ('IE:environmental-scientist','2142','Environment professionals — environmental scientist scope',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','2026-08-11'),
  ('IE:agronomist','2112','Agronomist',20,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','2026-08-11'),
  ('IE:farm-manager','1211','Managers and proprietors in agriculture and horticulture — farm manager scope',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','2026-08-11'),
  ('IE:forestry-technician','5119','Speciality forestry harvesting technician — explicit permit exception scope',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/ineligible-categories-of-employment/','2026-08-11'),
  ('IE:food-technologist','2129','Engineering professionals n.e.c. — Food Technologist scope',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','2026-08-11'),
  ('IE:sustainability-specialist','2142','Environment professionals — sustainability specialist scope',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','2026-08-11'),
  ('IE:horticulturist','5112','Horticultural trades — practical horticulturist scope',null,false,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/ineligible-categories-of-employment/','2026-08-11'),
  ('IE:animal-science-technician','3111','Laboratory technicians — animal-science / laboratory animal-technician scope',10,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','2026-08-11')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,shortage_rating=excluded.shortage_rating,visa_eligible=excluded.visa_eligible,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (
  profile_key,link_type,label,url,provider_type,region_code,sort_order,source_checked_at
) values
  ('IE:environmental-scientist','source','SOLAS — Science and Engineering labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/science-and-engineering/','government',null,1,'2026-08-11'),
  ('IE:environmental-scientist','source','DETE — employment-permit occupation classification','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','government',null,2,'2026-08-11'),
  ('IE:agronomist','source','SOLAS — Agriculture and Animal Care labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/agriculture-and-animal-care/','government',null,1,'2026-08-11'),
  ('IE:agronomist','source','DETE — Critical Skills Occupations List','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','government',null,2,'2026-08-11'),
  ('IE:agronomist','source','DETE — 2026 occupations-list review announcement','https://enterprise.gov.ie/en/news-and-events/department-news/2026/may/20260528.html','government',null,3,'2026-08-11'),
  ('IE:farm-manager','source','SOLAS — Agriculture and Animal Care labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/agriculture-and-animal-care/','government',null,1,'2026-08-11'),
  ('IE:farm-manager','source','DETE — Ineligible List farmer boundary','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/ineligible-categories-of-employment/','government',null,2,'2026-08-11'),
  ('IE:farm-manager','entry_program','Teagasc — Farm Manager Apprenticeship','https://teagasc.ie/education/apprenticeships/farm-manager/','government',null,3,'2026-08-11'),
  ('IE:forestry-technician','source','SOLAS — Agriculture and Animal Care labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/agriculture-and-animal-care/','government',null,1,'2026-08-11'),
  ('IE:forestry-technician','source','DETE — speciality forestry harvesting technician permit exception','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/ineligible-categories-of-employment/','government',null,2,'2026-08-11'),
  ('IE:forestry-technician','entry_program','Teagasc — Level 5 + Level 6 Forestry pathway','https://teagasc.ie/education/courses/forestry','government',null,3,'2026-08-11'),
  ('IE:food-technologist','source','SOLAS — Science and Engineering labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/science-and-engineering/','government',null,1,'2026-08-11'),
  ('IE:food-technologist','source','DETE — Critical Skills specialist-scope boundary','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','government',null,2,'2026-08-11'),
  ('IE:sustainability-specialist','source','SOLAS — green-demand context within Science and Engineering','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/science-and-engineering/','government',null,1,'2026-08-11'),
  ('IE:sustainability-specialist','source','DETE — employment-permit occupation classification','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','government',null,2,'2026-08-11'),
  ('IE:horticulturist','source','SOLAS — Agriculture and Animal Care labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/agriculture-and-animal-care/','government',null,1,'2026-08-11'),
  ('IE:horticulturist','source','DETE — Horticultural trades on current Ineligible List','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/ineligible-categories-of-employment/','government',null,2,'2026-08-11'),
  ('IE:horticulturist','entry_program','Teagasc — Horticulturist Apprenticeship and land-based pathways','https://teagasc.ie/education/apprenticeships/','government',null,3,'2026-08-11'),
  ('IE:animal-science-technician','source','SOLAS — Science and Engineering lab-technician shortage evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/science-and-engineering/','government',null,1,'2026-08-11'),
  ('IE:animal-science-technician','source','DETE — employment-permit occupation classification','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','government',null,2,'2026-08-11'),
  ('IE:animal-science-technician','entry_program','SOLAS — Laboratory Assistant traineeship (related technical route)','https://www.solas.ie/programmes/traineeship/','government',null,3,'2026-08-11')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,region_code=excluded.region_code,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;;
