-- Canada Programs Phase 3: normalize current university admission windows for USask Chemical Engineering / Special Education, Waterloo Architecture and University of Alberta BEd teacher-education pathways.

update public.program_catalog_ca_staging
set official_program_url='https://grad.usask.ca/programs/chemical-and-biological-engineering.php',source_status='official_graduate_program_verified_international_spring_2027_open',source_as_of=date '2026-08-08'
where institution_name='University of Saskatchewan' and title='Chemical Engineering' and credential_type in ('Master of Engineering','Master of Science','Doctor of Philosophy');
update public.program_pgwp_ca_staging p
set international_students_eligible=true,international_program_admission_status='official_graduate_international_spring_2027_open_deadline_2026_11_30',source_url='https://grad.usask.ca/programs/chemical-and-biological-engineering.php',source_as_of=date '2026-08-08',verified_at=now(),rule_notes=concat_ws(' ',nullif(p.rule_notes,''),'USask Chemical and Biological Engineering graduate page checked 2026-08-08: Spring/May international applications are due November 30, so the Spring 2027 application window is currently open.')
from public.program_catalog_ca_staging c where p.program_catalog_id=c.id and c.institution_name='University of Saskatchewan' and c.title='Chemical Engineering' and c.credential_type in ('Master of Engineering','Master of Science','Doctor of Philosophy');

update public.program_catalog_ca_staging
set official_program_url='https://admissions.usask.ca/engineering.php',source_status='official_undergraduate_program_verified_fall_2026_application_closed',source_as_of=date '2026-08-08'
where institution_name='University of Saskatchewan' and title='Chemical Engineering' and credential_type='Bachelor of Engineering';
update public.program_pgwp_ca_staging p
set international_students_eligible=true,international_program_admission_status='international_fall_2026_application_closed_deadline_2026_02_15_next_cycle_not_yet_verified',source_url='https://admissions.usask.ca/engineering.php',source_as_of=date '2026-08-08',verified_at=now(),rule_notes=concat_ws(' ',nullif(p.rule_notes,''),'USask undergraduate Engineering admissions checked 2026-08-08: the program starts in September and the published Fall 2026 international application deadline was February 15. The next cycle is not inferred until officially published.')
from public.program_catalog_ca_staging c where p.program_catalog_id=c.id and c.institution_name='University of Saskatchewan' and c.title='Chemical Engineering' and c.credential_type='Bachelor of Engineering';

update public.program_catalog_ca_staging
set official_program_url='https://education.usask.ca/departments/educational-psychology-and-special-education/special-education-certificate.php',source_status='official_current_program_spring_2026_intake_closed_one_intake_per_academic_year',source_as_of=date '2026-08-08'
where institution_name='University of Saskatchewan' and title='Special Education Certificate' and credential_type='Post-Degree Certificate';
update public.program_pgwp_ca_staging p
set international_program_admission_status='current_spring_2026_intake_closed_next_intake_not_yet_verified',source_url='https://education.usask.ca/departments/educational-psychology-and-special-education/special-education-certificate.php',source_as_of=date '2026-08-08',verified_at=now(),rule_notes=concat_ws(' ',nullif(p.rule_notes,''),'USask Special Education Certificate page checked 2026-08-08: Spring 2026 applications are closed, there is one Spring intake per academic year, and applicants require a valid Canadian provincial/territorial teaching certificate plus classroom experience. Do not infer the next intake until published.')
from public.program_catalog_ca_staging c where p.program_catalog_id=c.id and c.institution_name='University of Saskatchewan' and c.title='Special Education Certificate' and c.credential_type='Post-Degree Certificate';

update public.program_catalog_ca_staging
set official_program_url='https://www.ualberta.ca/en/education/programs/undergraduate-programs/index.html',source_status='official_bed_program_verified_fall_2026_application_closed_next_cycle_opens_2026_10_01',source_as_of=date '2026-08-08'
where institution_name='University of Alberta' and (title ilike '%Elementary Education%' or title ilike '%Secondary Education%') and exists (select 1 from public.program_occupation_ca_staging o where o.program_catalog_id=program_catalog_ca_staging.id and o.review_status='approved' and o.canonical_career_id in ('primary-school-teacher','secondary-school-teacher'));
update public.program_pgwp_ca_staging p
set international_program_admission_status='fall_2026_application_cycle_closed_next_fall_cycle_opens_2026_10_01',source_url='https://www.ualberta.ca/en/education/programs/undergraduate-programs/index.html',source_as_of=date '2026-08-08',verified_at=now(),rule_notes=concat_ws(' ',nullif(p.rule_notes,''),'University of Alberta Faculty of Education current guidance checked 2026-08-08: applications open October 1 for the next Fall intake and close March 1. Fall 2026 applications are closed; the next Fall cycle is not open until October 1, 2026.')
from public.program_catalog_ca_staging c where p.program_catalog_id=c.id and c.institution_name='University of Alberta' and (c.title ilike '%Elementary Education%' or c.title ilike '%Secondary Education%') and exists (select 1 from public.program_occupation_ca_staging o where o.program_catalog_id=c.id and o.review_status='approved' and o.canonical_career_id in ('primary-school-teacher','secondary-school-teacher'));

update public.program_catalog_ca_staging
set official_program_url=case when credential_type='Master of Architecture' then 'https://uwaterloo.ca/architecture/future-students/future-graduate-students/how-apply' else 'https://uwaterloo.ca/architecture/future-students/undergraduate' end,source_status='official_architecture_program_verified_next_fall_cycle_not_yet_open_2026_08_08',source_as_of=date '2026-08-08'
where institution_name='University of Waterloo' and title='Architecture' and credential_type in ('Bachelor of Architectural Studies','Master of Architecture');
update public.program_pgwp_ca_staging p
set international_program_admission_status=case when c.credential_type='Master of Architecture' then 'current_application_cycle_closed_next_fall_cycle_not_yet_open_deadline_january_15' else 'fall_2027_application_cycle_not_yet_open_opens_mid_september_2026' end,source_url=case when c.credential_type='Master of Architecture' then 'https://uwaterloo.ca/architecture/future-students/future-graduate-students/how-apply' else 'https://uwaterloo.ca/architecture/future-students/undergraduate' end,source_as_of=date '2026-08-08',verified_at=now(),rule_notes=concat_ws(' ',nullif(p.rule_notes,''),case when c.credential_type='Master of Architecture' then 'Waterloo Architecture MArch admissions checked 2026-08-08: September entry uses a January 15 application deadline; the current cycle is closed and the next cycle is not yet verified open.' else 'Waterloo undergraduate Architecture admissions checked 2026-08-08: Fall 2027 applications open in mid-September 2026, so the next cycle is not yet open.' end)
from public.program_catalog_ca_staging c where p.program_catalog_id=c.id and c.institution_name='University of Waterloo' and c.title='Architecture' and c.credential_type in ('Bachelor of Architectural Studies','Master of Architecture');;
