-- Japan Construction / Trades occupation cohort.
-- Classification basis: 2022 revision of the Ministry of Health, Labour and Welfare occupation classification.

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('JP:carpenter','JP','carpenter','大工','MHLW Occupation Classification','2022','091-01','JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:electrician','JP','electrician','電気工事作業員','MHLW Occupation Classification','2022','094-05','JPY',true,'経済産業省 — 電気工事士','https://www.meti.go.jp/information/license/c_text24.html','profile_ready','2026-08-10',now()),
('JP:plumber','JP','plumber','配管工','MHLW Occupation Classification','2022','091-06','JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:wall-floor-tiler','JP','wall-floor-tiler','ブロック積工、タイル張工 — tile scope','MHLW Occupation Classification','2022','091-02','JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:welder','JP','welder','金属溶接・溶断工','MHLW Occupation Classification','2022','071-13','JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:bricklayer','JP','bricklayer','ブロック積工、タイル張工 — brick/block masonry scope','MHLW Occupation Classification','2022','091-02','JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:hvac-technician','JP','hvac-technician','冷凍・空調設備技術者 — installation/maintenance umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:construction-manager','JP','construction-manager','建築施工管理技術者','MHLW Occupation Classification','2022','008-02','JPY',false,null,null,'profile_ready','2026-08-10',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at) values
('JP:carpenter','2026-08-10',0,0,0,0,15,0,0,0,5,20,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','2022 MHLW 091-01 大工 directly covers building carpentry and apprentices.','entry_level_basis','Vocational, employer and supervised site training support practical entry.','market_scope','No exact recurring cross-country-comparable 091-01 market series has been normalised.','visa_scope','No occupation-specific visa credit is assigned.','score_scope','Entry accessibility and low universal licensing burden only.'),'2026-08-10'),
('JP:electrician','2026-08-10',0,0,0,0,12,0,0,0,1,13,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','2022 MHLW 094-05 電気工事作業員 is the direct building-electrical trade anchor.','entry_level_basis','Vocational electrical training and supervised practical experience support entry.','qualification_note','Statutory electrical work requires the applicable 電気工事士 qualification; education alone is insufficient.','market_scope','Exact recurring comparable 094-05 market evidence is not yet normalised.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:plumber','2026-08-10',0,0,0,0,15,0,0,0,4,19,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','2022 MHLW 091-06 配管工 directly covers water, gas, steam and air-conditioning piping.','entry_level_basis','Vocational and supervised practical routes support entry.','qualification_note','Regulated water-supply installation uses the designated-contractor and 給水装置工事主任技術者 framework, but the full plumber occupation is not universally licensed.','market_scope','Broad utility and construction observations are not substituted for exact plumber evidence.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:wall-floor-tiler','2026-08-10',0,0,0,0,15,0,0,0,5,20,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','Tile work is a restricted subset of 2022 MHLW 091-02 ブロック積工、タイル張工.','entry_level_basis','Practical vocational and site-based entry is accessible.','market_scope','Whole-group masonry/tile observations are not treated as tile-only evidence.','visa_scope','No occupation-specific visa credit is assigned.','score_scope','Entry accessibility and low universal licensing burden only.'),'2026-08-10'),
('JP:welder','2026-08-10',0,0,0,0,15,0,0,0,3,18,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','2022 MHLW 071-13 金属溶接・溶断工 directly covers welding and thermal cutting work.','entry_level_basis','Practical process training is central to entry.','qualification_note','Gas welding requires prescribed skills training and arc-welding work requires statutory special education; this is process-specific rather than one universal welder licence.','market_scope','Construction and manufacturing demand are not blended into a fabricated welder-only score.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:bricklayer','2026-08-10',0,0,0,0,15,0,0,0,5,20,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','Brick and block masonry are a restricted subset of 2022 MHLW 091-02 ブロック積工、タイル張工.','entry_level_basis','Practical vocational and supervised site entry is accessible.','market_scope','Whole-group tile/masonry observations are not treated as bricklayer-only evidence.','visa_scope','No occupation-specific visa credit is assigned.','score_scope','Entry accessibility and low universal licensing burden only.'),'2026-08-10'),
('JP:hvac-technician','2026-08-10',0,0,0,0,12,0,0,0,4,16,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','The canonical HVAC technician spans 075-01 commercial HVAC/refrigeration repair, 075-02 household AC repair, 091-06 HVAC piping and 094-05 household AC electrical installation.','entry_level_basis','Technical training and supervised installation/maintenance experience support entry.','qualification_note','Electrical, refrigerant, piping and facility responsibilities can carry separate requirements; no single universal HVAC licence covers the whole umbrella.','market_scope','Incompatible source groups are not merged into one fabricated HVAC market series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:construction-manager','2026-08-10',0,0,0,0,10,0,0,0,3,13,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','2022 MHLW 008-02 建築施工管理技術者 directly covers building construction management and site supervision.','entry_level_basis','Architecture/civil study is relevant, but progression is experience-sensitive; five approved Japanese programmes are retained only as related pathways.','qualification_note','No particular qualification is required merely to enter the occupation, while legally designated 主任技術者/監理技術者 appointments can require recognised qualifications or experience.','market_scope','Current job-tag figures are not yet normalised for cross-country scoring.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10')
on conflict (profile_key,as_of_date) do update set shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('JP:carpenter','091-01','大工',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:electrician','094-05','電気工事作業員',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:plumber','091-06','配管工',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:wall-floor-tiler','091-02','ブロック積工、タイル張工 — tile scope',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:welder','071-13','金属溶接・溶断工',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:bricklayer','091-02','ブロック積工、タイル張工 — brick/block masonry scope',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:hvac-technician','075-01','業務用空調機器・冷凍装置の整備・修理 scope',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:hvac-technician','075-02','家庭用エアコン修理 scope',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:hvac-technician','091-06','空調配管工 scope',null,null,false,3,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:hvac-technician','094-05','エアコン取付作業員（家庭用） electrical-installation scope',null,null,false,4,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:construction-manager','008-02','建築施工管理技術者',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'job_search','Hello Work job search','https://www.hellowork.mhlw.go.jp/kensaku/GECA110010.do','government',10,'2026-08-10' from public.country_occupation_profiles p where p.country_code='JP' and p.canonical_career_id in ('carpenter','electrician','plumber','wall-floor-tiler','welder','bricklayer','hvac-technician','construction-manager')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'source','2022 MHLW occupation classification','https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','government',20,'2026-08-10' from public.country_occupation_profiles p where p.country_code='JP' and p.canonical_career_id in ('carpenter','electrician','plumber','wall-floor-tiler','welder','bricklayer','hvac-technician','construction-manager')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at) values
('JP:electrician','source','Electrician licence — METI','https://www.meti.go.jp/information/license/c_text24.html','government',30,'2026-08-10'),
('JP:plumber','source','Designated water-supply contractor framework','https://www.mlit.go.jp/mizukokudo/watersupply/topics_bukyoku_kenkou_suido_kyusui_02.html','government',30,'2026-08-10'),
('JP:welder','source','Arc-welding special education','https://www.mhlw.go.jp/web/t_doc?dataId=74085000','government',30,'2026-08-10'),
('JP:welder','source','Gas-welding skills training','https://www.mhlw.go.jp/web/t_doc?dataId=74141000&dataType=0&pageNo=1','government',31,'2026-08-10'),
('JP:construction-manager','source','MHLW job tag — 建築施工管理技術者','https://shigoto.mhlw.go.jp/User/Occupation/Detail?occupationId=21','government',30,'2026-08-10')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'JP:'||o.canonical_career_id,c.source_program_key,case when o.relation_type='direct' then 'direct' else 'related' end,coalesce(o.source_checked_at,'2026-08-10'::date)
from public.program_occupation_jp_staging o
join public.program_catalog_jp_staging c on c.id=o.program_catalog_id
where o.review_status='approved'
  and o.canonical_career_id in ('carpenter','electrician','plumber','wall-floor-tiler','welder','bricklayer','hvac-technician','construction-manager')
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;;
