-- Australia Hospitality Supervisor profile.
-- Canonical umbrella maps to current OSCA Unit Group 4715 Hospitality Supervisors, not to a fabricated single six-digit occupation.

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('AU:hospitality-supervisor','AU','hospitality-supervisor','Hospitality Supervisors','OSCA','2024 v1.0','4715','AUD',false,'No universal registration; migration coverage is mixed across the five current OSCA occupations, with legacy ANZSCO 431411 Hotel Service Manager assessed by VETASSESS for relevant accommodation-supervisor pathways','https://www.vetassess.com.au/check-my-occupation/professional-occupations/hotel-service-manager','profile_ready','2026-08-09',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,employment_total,median_weekly_earnings,median_hourly_earnings,annualised_median_salary,all_occupations_median_weekly,part_time_share_pct,female_share_pct,median_age,average_full_time_hours,vacancies_three_month_avg,vacancy_period,vacancy_yoy_pct,employment_growth_5y_pct,employment_growth_10y_pct,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at) values
('AU:hospitality-supervisor','2026-05-01',null,null,null,null,1852,null,null,null,null,null,null,null,null,null,0,0,5,0,13,0,5,5,5,33,'career-opportunity-v1','provisional',jsonb_build_object(
'classification_scope','CampCareer maps Hospitality Supervisor to current OSCA Unit Group 4715 Hospitality Supervisors. The umbrella contains five distinct six-digit occupations and no single six-digit code is presented as the canonical occupation.',
'mapping_relation','unit_group_rollup',
'included_current_occupations',jsonb_build_array('471531 Bar Supervisor','471532 Cafe or Restaurant Supervisor','471533 Front Office Supervisor (Accommodation)','471534 Gaming Supervisor','471535 Housekeeping Supervisor'),
'labour_scope','Primary employment, demographics and earnings remain null because the five current occupations do not share one exact six-digit labour profile. Legacy 431111 Bar Attendant context is not substituted for the umbrella.',
'vacancy_scope','Primary national and regional vacancy values remain null because relevant legacy vacancy series span different unit groups and cannot be validly summed into an exact current OSCA 4715 observation.',
'projection_scope','Relevant broader legacy hospitality-service groups show positive 2030 and 2035 projections; only partial growth credit is assigned without manufacturing a single roll-up percentage.',
'shortage_note','JSA 2025 OSL records all five current OSCA 4715 occupations as No Shortage nationally.',
'visa_basis','Migration coverage is mixed. Front Office Supervisor (Accommodation) and Housekeeping Supervisor map in the current ingest to legacy ANZSCO 431411 Hotel Service Manager, which is on the current skilled occupation instrument with VETASSESS. Other supervisor occupations in the umbrella do not have the same verified pathway, so visa credit is partial.',
'entry_level_basis','TAFE NSW Diploma of Hospitality Management 112061M provides a direct supervisory/management route; UQ Bachelor of Tourism, Hospitality and Event Management 103168H provides broader hospitality-management education.',
'entry_burden_basis','No universal occupational licence applies, but venue-specific responsible-service, gaming or other credentials can apply and supervisory roles normally require frontline experience.',
'score_note','The umbrella avoids fake aggregation: no primary employment, salary or vacancy values are invented and migration receives only partial credit.'
),'2026-08-09')
on conflict (profile_key,as_of_date) do update set employment_total=excluded.employment_total,median_weekly_earnings=excluded.median_weekly_earnings,median_hourly_earnings=excluded.median_hourly_earnings,annualised_median_salary=excluded.annualised_median_salary,all_occupations_median_weekly=excluded.all_occupations_median_weekly,part_time_share_pct=excluded.part_time_share_pct,female_share_pct=excluded.female_share_pct,median_age=excluded.median_age,average_full_time_hours=excluded.average_full_time_hours,vacancies_three_month_avg=excluded.vacancies_three_month_avg,vacancy_period=excluded.vacancy_period,vacancy_yoy_pct=excluded.vacancy_yoy_pct,employment_growth_5y_pct=excluded.employment_growth_5y_pct,employment_growth_10y_pct=excluded.employment_growth_10y_pct,shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,legacy_code_system,legacy_code_version,legacy_code,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('AU:hospitality-supervisor','471531','Bar Supervisor','ANZSCO','2022','431111',null,false,true,1,'https://www.abs.gov.au/statistics/classifications/osca-occupation-standard-classification-australia/2024-version-1-0/browse-classification/4/47/471/4715/471531','2026-08-09'),
('AU:hospitality-supervisor','471532','Cafe or Restaurant Supervisor','ANZSCO','2022','431211',null,false,true,2,'https://www.abs.gov.au/statistics/classifications/osca-occupation-standard-classification-australia/2024-version-1-0/browse-classification/4/47/471/4715/471532','2026-08-09'),
('AU:hospitality-supervisor','471533','Front Office Supervisor (Accommodation)','ANZSCO','2022','431411',null,true,true,3,'https://www.abs.gov.au/statistics/classifications/osca-occupation-standard-classification-australia/2024-version-1-0/browse-classification/4/47/471/4715/471533','2026-08-09'),
('AU:hospitality-supervisor','471534','Gaming Supervisor','ANZSCO','2022',null,null,false,true,4,'https://www.abs.gov.au/statistics/classifications/osca-occupation-standard-classification-australia/2024-version-1-0/browse-classification/4/47/471/4715/471534','2026-08-09'),
('AU:hospitality-supervisor','471535','Housekeeping Supervisor','ANZSCO','2022','431411',null,true,true,5,'https://www.abs.gov.au/statistics/classifications/osca-occupation-standard-classification-australia/2024-version-1-0/browse-classification/4/47/471/4715/471535','2026-08-09')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,legacy_code_system=excluded.legacy_code_system,legacy_code_version=excluded.legacy_code_version,legacy_code=excluded.legacy_code,shortage_rating=excluded.shortage_rating,visa_eligible=excluded.visa_eligible,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_region_metrics (profile_key,region_code,as_of_date,shortage_rating,vacancy_count,source_url) values
('AU:hospitality-supervisor','ACT','2026-05-01',null,null,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:hospitality-supervisor','NSW','2026-05-01',null,null,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:hospitality-supervisor','NT','2026-05-01',null,null,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:hospitality-supervisor','QLD','2026-05-01',null,null,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:hospitality-supervisor','SA','2026-05-01',null,null,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:hospitality-supervisor','TAS','2026-05-01',null,null,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:hospitality-supervisor','VIC','2026-05-01',null,null,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:hospitality-supervisor','WA','2026-05-01',null,null,'https://www.jobsandskills.gov.au/data/internet-vacancy-index')
on conflict (profile_key,region_code,as_of_date) do update set shortage_rating=excluded.shortage_rating,vacancy_count=excluded.vacancy_count,source_url=excluded.source_url;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,region_code,sort_order,source_checked_at) values
('AU:hospitality-supervisor','employer','Accor Careers','https://careers.accor.com/','hotel_hospitality',null,1,'2026-08-09'),('AU:hospitality-supervisor','employer','Marriott Careers','https://careers.marriott.com/','hotel_hospitality',null,2,'2026-08-09'),('AU:hospitality-supervisor','employer','Hilton Careers','https://jobs.hilton.com/','hotel_hospitality',null,3,'2026-08-09'),('AU:hospitality-supervisor','employer','Crown Careers','https://www.crownresorts.com.au/careers','integrated_resort',null,4,'2026-08-09'),('AU:hospitality-supervisor','employer','Compass Group Australia Careers','https://www.compass-group.com.au/careers/','contract_hospitality',null,5,'2026-08-09'),
('AU:hospitality-supervisor','entry_program','TAFE NSW — Diploma of Hospitality Management','https://www.tafensw.edu.au/international/courses/Diploma-of-Hospitality-Management--SIT50422','tafe',null,1,'2026-08-09'),('AU:hospitality-supervisor','entry_program','UQ — Bachelor of Tourism, Hospitality and Event Management','https://study.uq.edu.au/study-options/programs/bachelor-tourism-hospitality-and-event-management-2473?year=2026','university',null,2,'2026-08-09'),
('AU:hospitality-supervisor','source','ABS — OSCA 4715 Hospitality Supervisors','https://www.abs.gov.au/statistics/classifications/osca-occupation-standard-classification-australia/2024-version-1-0/browse-classification/4/47/471/4715','official_classification',null,1,'2026-08-09'),('AU:hospitality-supervisor','source','JSA — 2025 Occupation Shortage List','https://www.jobsandskills.gov.au/data/occupation-shortage-analysis/occupation-shortage-list','official_shortage',null,2,'2026-08-09'),('AU:hospitality-supervisor','source','VETASSESS — Hotel Service Manager','https://www.vetassess.com.au/check-my-occupation/professional-occupations/hotel-service-manager','official_skills_assessment',null,3,'2026-08-09')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,region_code=excluded.region_code,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'AU:hospitality-supervisor','au-program:'||id::text,case when course_code='112061M' then 'direct' else 'related' end,'2026-08-09' from public.courses_au where (institution_id='tafe-nsw' and course_code='112061M') or (institution_id='the-university-of-queensland' and course_code='103168H')
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;;
