-- Standardise source-backed dashboards for the 16 generic launch countries.

insert into core.countries (code, name, default_currency, active, updated_at) values
  ('IE', 'Ireland', 'EUR', true, now()),
  ('DE', 'Germany', 'EUR', true, now()),
  ('NL', 'Netherlands', 'EUR', true, now()),
  ('BE', 'Belgium', 'EUR', true, now()),
  ('FR', 'France', 'EUR', true, now()),
  ('ES', 'Spain', 'EUR', true, now()),
  ('SG', 'Singapore', 'SGD', true, now()),
  ('KR', 'South Korea', 'KRW', true, now()),
  ('JP', 'Japan', 'JPY', true, now()),
  ('NZ', 'New Zealand', 'NZD', true, now()),
  ('NO', 'Norway', 'NOK', true, now()),
  ('SE', 'Sweden', 'SEK', true, now()),
  ('DK', 'Denmark', 'DKK', true, now()),
  ('FI', 'Finland', 'EUR', true, now()),
  ('CH', 'Switzerland', 'CHF', true, now()),
  ('AE', 'United Arab Emirates', 'AED', true, now())
on conflict (code) do update set name=excluded.name, default_currency=excluded.default_currency, active=true, updated_at=now();

do $$
declare source_row record; source_id_value uuid; snapshot_id_value uuid;
begin
  for source_row in select * from (values
    ('cc_ie_c628c4d1d445', 'Earnings and Labour Costs Q1 2026 preliminary estimates', 'Earnings and Labour Costs Q1 2026 preliminary estimates', 'government_dataset', 'https://www.cso.ie/en/releasesandpublications/ep/p-elcq/earningsandlabourcostsq42025finalq12026preliminaryestimates/', 'IE', date '2026-03-31', '{"country_code":"IE","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_ie_f73609aad8c1', 'Information on Student Finances', 'Information on Student Finances', 'provider', 'https://www.irishimmigration.ie/coming-to-study-in-ireland/what-are-my-study-options/a-fee-paying-private-primary-or-secondary-school/information-on-student-finances/', 'IE', date '2025-06-30', '{"country_code":"IE","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_ie_63e18072799d', 'Undergraduate tuition fees 2025/26', 'Undergraduate tuition fees 2025/26', 'provider', 'https://www.educationinireland.com/en/plan-your-study-abroad/undergraduate-tuition-fees', 'IE', date '2025-09-01', '{"country_code":"IE","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_ie_52400e923ca9', 'National Minimum Wage increase on 1 January 2026', 'National Minimum Wage increase on 1 January 2026', 'government_dataset', 'https://www.gov.ie/en/publication/1786c-national-minimum-wage-increase-1-january/', 'IE', date '2026-01-01', '{"country_code":"IE","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_ie_e3fc0db2f062', 'Preclearance and entry visas fees', 'Preclearance and entry visas fees', 'regulator', 'https://www.irishimmigration.ie/preclearance-and-entry-visas-fees/', 'IE', date '2026-08-05', '{"country_code":"IE","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_ie_10c4d97c440c', 'Immigration permission stamps — Stamp 2', 'Immigration permission stamps — Stamp 2', 'regulator', 'https://www.irishimmigration.ie/registering-your-immigration-permission/information-on-registering/immigration-permission-stamps/', 'IE', date '2026-08-05', '{"country_code":"IE","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_de_a3fa77ddd243', 'Earnings Survey 2025', 'Earnings Survey 2025', 'government_dataset', 'https://www.destatis.de/DE/Presse/Pressemitteilungen/2026/04/PD26_113_621.html', 'DE', date '2025-12-31', '{"country_code":"DE","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_de_7f921597577a', 'Student finance and living-cost guidance', 'Student finance and living-cost guidance', 'provider', 'https://www.make-it-in-germany.com/en/visa-residence/types/studying', 'DE', date '2026-01-01', '{"country_code":"DE","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_de_574013029138', 'Costs of education and living', 'Costs of education and living', 'provider', 'https://www.daad.de/en/studying-in-germany/living-in-germany/finances/', 'DE', date '2026-08-05', '{"country_code":"DE","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_de_a301294ae2a0', 'Statutory minimum wage', 'Statutory minimum wage', 'government_dataset', 'https://www.bmas.de/EN/Labour/Minimum-Wage/the-minimum-wage-questions-and-answers.html', 'DE', date '2026-01-01', '{"country_code":"DE","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_de_578f8a6c4959', 'Visa fees for long-term stays', 'Visa fees for long-term stays', 'regulator', 'https://www.auswaertiges-amt.de/en/visa-service/215870-215870', 'DE', date '2026-08-05', '{"country_code":"DE","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_de_38f7080e9051', 'Study and work rules for international students', 'Study and work rules for international students', 'regulator', 'https://www.make-it-in-germany.com/en/study-vocational-training/studies-in-germany/work', 'DE', date '2026-08-05', '{"country_code":"DE","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_nl_fb7a006e30af', 'Employment, wages and working hours, 2025 provisional', 'Employment, wages and working hours, 2025 provisional', 'government_dataset', 'https://www.cbs.nl/en-gb/figures/detail/81462ENG', 'NL', date '2025-12-31', '{"country_code":"NL","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_nl_e10a82d598bf', 'Daily student expenses and cost of living in the Netherlands', 'Daily student expenses and cost of living in the Netherlands', 'provider', 'https://www.studyinnl.org/finances/daily-student-expenses-and-cost-of-living-in-the-netherlands', 'NL', date '2026-08-06', '{"country_code":"NL","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_nl_c4340459b2ef', 'Tuition fees', 'Tuition fees', 'provider', 'https://www.studyinnl.org/finances/tuition-fees', 'NL', date '2026-08-06', '{"country_code":"NL","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_nl_c9472afaa572', 'Minimum wage amounts', 'Minimum wage amounts', 'government_dataset', 'https://www.government.nl/themes/work/minimum-wage/minimum-wage-amounts', 'NL', date '2026-07-01', '{"country_code":"NL","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_nl_106b6c6a23e2', 'Fees: costs of an application', 'Fees: costs of an application', 'regulator', 'https://ind.nl/en/fees-costs-of-an-application', 'NL', date '2026-01-01', '{"country_code":"NL","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_nl_70f02174fefa', 'Student residence permit for university or higher professional education', 'Student residence permit for university or higher professional education', 'regulator', 'https://ind.nl/en/residence-permits/study/student-residence-permit-for-university-or-higher-professional-education', 'NL', date '2026-08-06', '{"country_code":"NL","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_be_33c5273421a8', 'Belgian wages and salaries', 'Belgian wages and salaries', 'government_dataset', 'https://statbel.fgov.be/en/themes/work-training/wages-and-labourcost/overview-belgian-wages-and-salaries', 'BE', date '2022-12-31', '{"country_code":"BE","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_be_bee88adb43db', 'Cost of living and sufficient means', 'Cost of living and sufficient means', 'provider', 'https://www.studyinflanders.be/practical-information/cost-of-living', 'BE', date '2026-08-06', '{"country_code":"BE","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_be_c257a91341f7', 'Tuition fees', 'Tuition fees', 'provider', 'https://www.studyinflanders.be/practical-information/tuition-fees', 'BE', date '2026-09-01', '{"country_code":"BE","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_be_2890c5d1457d', 'Student employment minimum remuneration', 'Student employment minimum remuneration', 'government_dataset', 'https://employment.belgium.be/en/node/4096', 'BE', date '2026-07-01', '{"country_code":"BE","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_be_fa123ddbcce9', 'Work and study', 'Work and study', 'regulator', 'https://www.studyinflanders.be/practical-information/work-and-study', 'BE', date '2026-08-06', '{"country_code":"BE","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_fr_66881288fe25', 'Private-sector salaries 2024', 'Private-sector salaries 2024', 'government_dataset', 'https://www.insee.fr/fr/statistiques/8657156', 'FR', date '2024-12-31', '{"country_code":"FR","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_fr_63f1f741eb89', 'Preparing your student budget', 'Preparing your student budget', 'provider', 'https://www.campusfrance.org/en/preparing-budget-student-France', 'FR', date '2026-08-06', '{"country_code":"FR","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_fr_479efffa7f17', 'Tuition fees in France', 'Tuition fees in France', 'provider', 'https://www.campusfrance.org/en/tuition-fees-France', 'FR', date '2026-09-01', '{"country_code":"FR","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_fr_901b846def26', 'SMIC', 'SMIC', 'government_dataset', 'https://www.insee.fr/fr/statistiques/1375188?lang=en', 'FR', date '2026-01-01', '{"country_code":"FR","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_fr_f96a8a1b3fc8', 'Working while studying in France', 'Working while studying in France', 'regulator', 'https://www.campusfrance.org/en/working-student', 'FR', date '2026-08-06', '{"country_code":"FR","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_es_b981c15fe415', 'Wage Structure Survey 2024', 'Wage Structure Survey 2024', 'government_dataset', 'https://www.ine.es/dyngs/Prensa/en/EAES2024.htm', 'ES', date '2024-12-31', '{"country_code":"ES","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_es_b995324711d5', 'Study in Spain', 'Study in Spain', 'provider', 'https://studyinspain.info/en/', 'ES', date '2026-08-06', '{"country_code":"ES","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_es_338313b6e22a', 'Stay for study purposes', 'Stay for study purposes', 'regulator', 'https://www.inclusion.gob.es/web/migraciones/w/estancia-por-estudios', 'ES', date '2026-08-06', '{"country_code":"ES","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_sg_996890efbd52', 'Income of full-time employed PMEs', 'Income of full-time employed PMEs', 'government_dataset', 'https://www.mom.gov.sg/newsroom/parliament-questions-and-replies/2026/0407-oral-answer-to-pq-on-income-of-pme', 'SG', date '2025-12-31', '{"country_code":"SG","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_sg_c2f03f3a4a67', 'Living expenses', 'Living expenses', 'provider', 'https://www.nus.edu.sg/oam/financial-aid/living-expenses', 'SG', date '2026-08-06', '{"country_code":"SG","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_sg_7e6181a20237', 'Student Pass', 'Student Pass', 'regulator', 'https://www.ica.gov.sg/reside/STP/apply', 'SG', date '2026-08-06', '{"country_code":"SG","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_sg_e3d13cdfaa1e', 'Work pass exemption for foreign students', 'Work pass exemption for foreign students', 'regulator', 'https://www.mom.gov.sg/passes-and-permits/work-pass-exemption-for-foreign-students', 'SG', date '2026-08-06', '{"country_code":"SG","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_kr_b8f5700528c5', 'Labour statistics', 'Labour statistics', 'government_dataset', 'https://laborstat.moel.go.kr/', 'KR', date '2025-12-31', '{"country_code":"KR","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_kr_1e21ed2b8390', 'Study expenses in Korea', 'Study expenses in Korea', 'provider', 'https://www.studyinkorea.go.kr/en/plan/abroadExpenses.do', 'KR', date '2026-08-06', '{"country_code":"KR","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_kr_bd779bddcd23', '2026 minimum wage', '2026 minimum wage', 'government_dataset', 'https://www.moel.go.kr/news/enews/report/enewsView.do?news_seq=18144', 'KR', date '2026-01-01', '{"country_code":"KR","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_kr_84a965b3eb73', 'Part-time work for international students', 'Part-time work for international students', 'regulator', 'https://www.studyinkorea.go.kr/en/work/aboutKoreaEmployment.do', 'KR', date '2026-08-06', '{"country_code":"KR","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_jp_7ef459d58e06', 'Monthly Labour Survey', 'Monthly Labour Survey', 'government_dataset', 'https://www.mhlw.go.jp/english/database/db-l/monthly-labour.html', 'JP', date '2025-12-31', '{"country_code":"JP","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_jp_f0af00e37387', 'Living Costs and Expenses', 'Living Costs and Expenses', 'provider', 'https://www.studyinjapan.go.jp/en/life/cost-of-living/', 'JP', date '2025-12-31', '{"country_code":"JP","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_jp_81b1f26cc40e', 'Academic fees', 'Academic fees', 'provider', 'https://www.studyinjapan.go.jp/en/planning/academic-fees/', 'JP', date '2026-08-06', '{"country_code":"JP","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_jp_6aa1bdd58d2e', 'Part-time work', 'Part-time work', 'regulator', 'https://www.studyinjapan.go.jp/en/job/parttime-works/', 'JP', date '2026-08-06', '{"country_code":"JP","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_nz_eaf54247823e', 'Fee Paying Student Visa', 'Fee Paying Student Visa', 'provider', 'https://www.immigration.govt.nz/visas/fee-paying-student-visa/', 'NZ', date '2026-08-06', '{"country_code":"NZ","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_nz_e08645f00895', 'Minimum wage rates', 'Minimum wage rates', 'government_dataset', 'https://www.employment.govt.nz/pay-and-hours/pay-and-wages/minimum-wage/', 'NZ', date '2026-04-01', '{"country_code":"NZ","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_no_94563868de68', 'Earnings statistics', 'Earnings statistics', 'government_dataset', 'https://www.ssb.no/en/arbeid-og-lonn/lonn-og-arbeidskraftkostnader/statistikk/lonn', 'NO', date '2025-12-31', '{"country_code":"NO","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_no_33508346a21c', 'Students budget and permit finance requirement', 'Students budget and permit finance requirement', 'provider', 'https://www.ssb.no/en/utdanning/hoyere-utdanning/artikler/students-budget', 'NO', date '2026-08-06', '{"country_code":"NO","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_no_95414b48d411', 'Cost and requirements', 'Cost and requirements', 'regulator', 'https://studyinnorway.no/cost-and-requirements', 'NO', date '2026-08-06', '{"country_code":"NO","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_se_6a2973c0ae0a', 'National median salary', 'National median salary', 'government_dataset', 'https://www.migrationsverket.se/en/employers/news-archive-for-employers/news/2026-06-16-new-median-salary-affects-the-salary-requirement-for-work-permits.html', 'SE', date '2026-06-16', '{"country_code":"SE","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_se_05210578cf03', 'Higher education residence permit', 'Higher education residence permit', 'provider', 'https://www.migrationsverket.se/en/you-want-to-apply/study/higher-education.html', 'SE', date '2026-01-01', '{"country_code":"SE","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_se_8989f52c4175', 'Fees and costs', 'Fees and costs', 'provider', 'https://studyinsweden.se/plan-your-studies/fees-costs/', 'SE', date '2026-08-06', '{"country_code":"SE","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_dk_a74deaa02709', 'Higher education permit', 'Higher education permit', 'provider', 'https://www.nyidanmark.dk/en-GB/You-want-to-apply/Study/Higher-education', 'DK', date '2026-01-01', '{"country_code":"DK","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_dk_661e72c9fa65', 'Tuition fees and scholarships', 'Tuition fees and scholarships', 'provider', 'https://studyindenmark.dk/study-options/tuition-fees-and-scholarships', 'DK', date '2026-08-06', '{"country_code":"DK","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_dk_27547da3a09d', 'New fee rates 2026', 'New fee rates 2026', 'regulator', 'https://nyidanmark.dk/en-GB/News-Front-Page/2026/01/New-fee-rates-2026', 'DK', date '2026-01-01', '{"country_code":"DK","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_fi_c39fc3978473', 'Structure of earnings 2024', 'Structure of earnings 2024', 'government_dataset', 'https://stat.fi/en/publication/cmfzekguk478y07uqsyc5xfpt', 'FI', date '2024-12-31', '{"country_code":"FI","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_fi_7c240dc9c797', 'Structure of earnings 2024', 'Structure of earnings 2024', 'government_dataset', 'https://stat.fi/en/publication/cm1ks981cdm5107w7zeme1ot7', 'FI', date '2024-12-31', '{"country_code":"FI","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_fi_adfb6af384ae', 'Fees and costs', 'Fees and costs', 'provider', 'https://www.studyinfinland.fi/admissions/fees-and-costs', 'FI', date '2026-08-06', '{"country_code":"FI","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_fi_b0778fd0ae0f', 'Studying in Finland', 'Studying in Finland', 'regulator', 'https://migri.fi/en/studying-in-finland', 'FI', date '2026-08-06', '{"country_code":"FI","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_ch_b1bd29658400', 'Swiss Earnings Structure Survey 2024', 'Swiss Earnings Structure Survey 2024', 'government_dataset', 'https://www.bfs.admin.ch/bfs/en/home/statistics/work-income/wages-income-employment-labour-costs/structure-wages.html', 'CH', date '2024-12-31', '{"country_code":"CH","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_ch_1d70240b880e', 'Studying in Switzerland', 'Studying in Switzerland', 'provider', 'https://www.swissuniversities.ch/en/topics/studying', 'CH', date '2026-08-06', '{"country_code":"CH","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_ch_d79f6dcc696f', 'Foreign students and employment', 'Foreign students and employment', 'regulator', 'https://www.sem.admin.ch/sem/en/home/themen/arbeit/nicht-eu_efta-angehoerige/hochschulabgaenger.html', 'CH', date '2026-08-06', '{"country_code":"CH","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_ae_0ae8eb9d16e3', 'International student cost guidance', 'International student cost guidance', 'provider', 'https://www.ku.ac.ae/graduate-admissions/tuition-fees', 'AE', date '2026-08-06', '{"country_code":"AE","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_ae_60ad1e9beee7', 'University tuition guidance', 'University tuition guidance', 'provider', 'https://www.uaeu.ac.ae/en/admission/undergraduate_tuition.shtml', 'AE', date '2026-08-06', '{"country_code":"AE","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_ae_60206a672827', 'Khalifa University tuition fees', 'Khalifa University tuition fees', 'provider', 'https://www.ku.ac.ae/undergraduate-tuition-fees', 'AE', date '2026-08-06', '{"country_code":"AE","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb),
    ('cc_ae_c99610a75275', 'Residence visa for studying in the UAE', 'Residence visa for studying in the UAE', 'regulator', 'https://u.ae/en/information-and-services/visa-and-emirates-id/residence-visas/residence-visa-for-studying-in-the-uae', 'AE', date '2026-02-18', '{"country_code":"AE","captured_for":"country_dashboard_batch_2026_08_06"}'::jsonb)
  ) as v(source_key, organisation_name, source_name, source_type, source_url, country_code, data_as_of, metadata)
  loop
    insert into evidence.sources (source_key, organisation_name, source_name, source_type, canonical_url, country_code, active, updated_at)
    values (source_row.source_key, source_row.organisation_name, source_row.source_name, source_row.source_type, source_row.source_url, source_row.country_code, true, now())
    on conflict (source_key) do update set organisation_name=excluded.organisation_name, source_name=excluded.source_name, source_type=excluded.source_type, canonical_url=excluded.canonical_url, country_code=excluded.country_code, active=true, updated_at=now()
    returning id into source_id_value;

    select id into snapshot_id_value from evidence.source_snapshots
    where source_id=source_id_value and source_url=source_row.source_url and data_as_of=source_row.data_as_of
    order by retrieved_at desc limit 1;
    if snapshot_id_value is null then
      insert into evidence.source_snapshots (source_id, source_url, data_as_of, retrieved_at, snapshot_status, metadata)
      values (source_id_value, source_row.source_url, source_row.data_as_of, now(), 'captured', source_row.metadata);
    end if;
  end loop;
end $$;

delete from evidence.metric_observations where scope_type='country' and scope_id in ('IE', 'DE', 'NL', 'BE', 'FR', 'ES', 'SG', 'KR', 'JP', 'NZ', 'NO', 'SE', 'DK', 'FI', 'CH', 'AE') and metric_key in ('full_time_annual_earnings_range', 'average_annual_salary', 'student_living_cost_monthly_range', 'tuition_annual_low', 'tuition_annual_high', 'national_minimum_hourly_wage', 'visa_application_fee', 'student_work_hours_limit');
do $$
declare metric_row record; snapshot_id_value uuid;
begin
  for metric_row in select * from (values
    ('IE', 'full_time_annual_earnings_range', 'cc_ie_c628c4d1d445', '{"low":44130,"high":66381,"ranking_value":53427,"currency":"EUR","basis":"interquartile_range_of_annualised_sector_average_weekly_earnings","population":"13 NACE economic sectors"}'::jsonb, 'EUR/year', 'calculated', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-03-31', 'Verified for the Ireland country dashboard.'),
    ('IE', 'average_annual_salary', 'cc_ie_c628c4d1d445', '{"amount":55930,"currency":"EUR","basis":"annualised_all_sector_average_weekly_earnings","statistic_type":"mean","weekly_amount":1075.58}'::jsonb, 'EUR/year', 'calculated', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-03-31', 'Verified for the Ireland country dashboard.'),
    ('IE', 'student_living_cost_monthly_range', 'cc_ie_f73609aad8c1', '{"low":833,"high":1340,"ranking_value":1340,"currency":"EUR","basis":"immigration_finance_minimum_to_observed_student_average","scenario":"one higher-education student; tuition excluded"}'::jsonb, 'EUR/month', 'calculated', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2025-06-30', 'Verified for the Ireland country dashboard.'),
    ('IE', 'tuition_annual_low', 'cc_ie_63e18072799d', '{"amount":10300,"currency":"EUR","basis":"mainstream_non_eu_undergraduate_published_range","student_type":"non-EU international"}'::jsonb, 'EUR/year', 'observed', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2025-09-01', 'Verified for the Ireland country dashboard.'),
    ('IE', 'tuition_annual_high', 'cc_ie_63e18072799d', '{"amount":29000,"currency":"EUR","basis":"mainstream_non_eu_undergraduate_published_range","student_type":"non-EU international","medicine_health_excluded":true}'::jsonb, 'EUR/year', 'observed', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2025-09-01', 'Verified for the Ireland country dashboard.'),
    ('IE', 'national_minimum_hourly_wage', 'cc_ie_52400e923ca9', '{"amount":14.15,"currency":"EUR","basis":"national_minimum_wage_age_20_and_over"}'::jsonb, 'EUR/hour', 'observed', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-01-01', 'Verified for the Ireland country dashboard.'),
    ('IE', 'visa_application_fee', 'cc_ie_e3fc0db2f062', '{"amount":60,"currency":"EUR","basis":"single_entry_long_stay_study_visa","stamp_2_registration_fee_excluded":300}'::jsonb, 'EUR', 'observed', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-05', 'Verified for the Ireland country dashboard.'),
    ('IE', 'student_work_hours_limit', 'cc_ie_10c4d97c440c', '{"hours":20,"period":"week","holiday_hours":40,"applies_during":"term_time"}'::jsonb, 'hours/week', 'observed', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-05', 'Verified for the Ireland country dashboard.'),
    ('DE', 'full_time_annual_earnings_range', 'cc_de_a3fa77ddd243', '{"low":54066,"high":64441,"ranking_value":54066,"currency":"EUR","basis":"national_median_to_arithmetic_mean_gross_annual_earnings"}'::jsonb, 'EUR/year', 'observed', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2025-12-31', 'Verified for the Germany country dashboard.'),
    ('DE', 'average_annual_salary', 'cc_de_a3fa77ddd243', '{"amount":64441,"currency":"EUR","basis":"national_arithmetic_mean_gross_annual_earnings","statistic_type":"mean"}'::jsonb, 'EUR/year', 'observed', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2025-12-31', 'Verified for the Germany country dashboard.'),
    ('DE', 'student_living_cost_monthly_range', 'cc_de_7f921597577a', '{"low":992,"high":1200,"ranking_value":1096,"currency":"EUR","basis":"student_visa_funding_requirement_to_daad_planning_upper_bound","scenario":"one higher-education student; tuition excluded","annual_funding_requirement":11904}'::jsonb, 'EUR/month', 'calculated', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-01-01', 'Verified for the Germany country dashboard.'),
    ('DE', 'tuition_annual_low', 'cc_de_574013029138', '{"amount":0,"currency":"EUR","basis":"standard_public_university_tuition","institution_type":"public"}'::jsonb, 'EUR/year', 'observed', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-05', 'Verified for the Germany country dashboard.'),
    ('DE', 'tuition_annual_high', 'cc_de_574013029138', '{"amount":3000,"currency":"EUR","basis":"baden_wuerttemberg_non_eu_public_tuition_annualised","institution_type":"public"}'::jsonb, 'EUR/year', 'calculated', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-05', 'Verified for the Germany country dashboard.'),
    ('DE', 'national_minimum_hourly_wage', 'cc_de_a301294ae2a0', '{"amount":13.9,"currency":"EUR","basis":"general_statutory_minimum_wage"}'::jsonb, 'EUR/hour', 'observed', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-01-01', 'Verified for the Germany country dashboard.'),
    ('DE', 'visa_application_fee', 'cc_de_578f8a6c4959', '{"amount":75,"currency":"EUR","basis":"adult_national_visa_processing_fee"}'::jsonb, 'EUR', 'observed', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-05', 'Verified for the Germany country dashboard.'),
    ('DE', 'student_work_hours_limit', 'cc_de_38f7080e9051', '{"hours":20,"period":"week","annual_full_day_alternative":140,"annual_half_day_alternative":280}'::jsonb, 'hours/week', 'observed', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-05', 'Verified for the Germany country dashboard.'),
    ('NL', 'full_time_annual_earnings_range', 'cc_nl_fb7a006e30af', '{"low":62730,"high":72950,"ranking_value":69290,"currency":"EUR","basis":"derived_full_time_average_annual_wage_by_employer_size","population":"full-time employee jobs across employer-size groups"}'::jsonb, 'EUR/year', 'calculated', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2025-12-31', 'Verified for the Netherlands country dashboard.'),
    ('NL', 'average_annual_salary', 'cc_nl_fb7a006e30af', '{"amount":69290,"currency":"EUR","basis":"derived_national_full_time_average_annual_wage","statistic_type":"mean"}'::jsonb, 'EUR/year', 'calculated', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2025-12-31', 'Verified for the Netherlands country dashboard.'),
    ('NL', 'student_living_cost_monthly_range', 'cc_nl_e10a82d598bf', '{"low":1000,"high":1500,"ranking_value":1250,"currency":"EUR","basis":"published_student_monthly_spending_range","scenario":"one higher-education student; tuition excluded","ind_2026_study_norm_monthly":1130.77}'::jsonb, 'EUR/month', 'calculated', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the Netherlands country dashboard.'),
    ('NL', 'tuition_annual_low', 'cc_nl_c4340459b2ef', '{"amount":9000,"currency":"EUR","basis":"published_average_non_eu_bachelor_range","student_type":"non-EU/EEA"}'::jsonb, 'EUR/year', 'observed', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the Netherlands country dashboard.'),
    ('NL', 'tuition_annual_high', 'cc_nl_c4340459b2ef', '{"amount":20000,"currency":"EUR","basis":"published_average_non_eu_bachelor_range","student_type":"non-EU/EEA"}'::jsonb, 'EUR/year', 'observed', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the Netherlands country dashboard.'),
    ('NL', 'national_minimum_hourly_wage', 'cc_nl_c9472afaa572', '{"amount":14.99,"currency":"EUR","basis":"statutory_minimum_wage_age_21_and_older"}'::jsonb, 'EUR/hour', 'observed', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-07-01', 'Verified for the Netherlands country dashboard.'),
    ('NL', 'visa_application_fee', 'cc_nl_106b6c6a23e2', '{"amount":254,"currency":"EUR","basis":"first_study_residence_permit_application"}'::jsonb, 'EUR', 'observed', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-01-01', 'Verified for the Netherlands country dashboard.'),
    ('NL', 'student_work_hours_limit', 'cc_nl_70f02174fefa', '{"hours":16,"period":"week","employment_permit_type":"TWV","summer_full_time_months":["June","July","August"]}'::jsonb, 'hours/week', 'observed', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the Netherlands country dashboard.'),
    ('BE', 'full_time_annual_earnings_range', 'cc_be_33c5273421a8', '{"low":44736,"high":48912,"ranking_value":44736,"currency":"EUR","basis":"annualised_full_time_median_to_mean_gross_monthly_wage"}'::jsonb, 'EUR/year', 'calculated', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2022-12-31', 'Verified for the Belgium country dashboard.'),
    ('BE', 'average_annual_salary', 'cc_be_33c5273421a8', '{"amount":48912,"currency":"EUR","basis":"annualised_full_time_mean_gross_monthly_wage","statistic_type":"mean"}'::jsonb, 'EUR/year', 'calculated', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2022-12-31', 'Verified for the Belgium country dashboard.'),
    ('BE', 'student_living_cost_monthly_range', 'cc_be_bee88adb43db', '{"low":800,"high":1062,"ranking_value":1000,"currency":"EUR","basis":"study_in_flanders_average_to_immigration_finance_requirement","scenario":"one higher-education student; tuition excluded","official_immigration_requirement":1062}'::jsonb, 'EUR/month', 'calculated', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the Belgium country dashboard.'),
    ('BE', 'tuition_annual_low', 'cc_be_c257a91341f7', '{"amount":2300,"currency":"EUR","basis":"non_eu_eea_full_time_degree_guideline","student_type":"non-EU/EEA"}'::jsonb, 'EUR/year', 'observed', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-09-01', 'Verified for the Belgium country dashboard.'),
    ('BE', 'tuition_annual_high', 'cc_be_c257a91341f7', '{"amount":9500,"currency":"EUR","basis":"non_eu_eea_full_time_degree_guideline","student_type":"non-EU/EEA"}'::jsonb, 'EUR/year', 'observed', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-09-01', 'Verified for the Belgium country dashboard.'),
    ('BE', 'national_minimum_hourly_wage', 'cc_be_2890c5d1457d', '{"amount":13.5644,"currency":"EUR","basis":"interprofessional_minimum_hourly_equivalent_38_hours","sector_collective_agreements_may_be_higher":true}'::jsonb, 'EUR/hour', 'observed', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-07-01', 'Verified for the Belgium country dashboard.'),
    ('BE', 'student_work_hours_limit', 'cc_be_fa123ddbcce9', '{"hours":20,"period":"week","applies_during":"academic_year","school_holiday_work":"unlimited_subject_to_conditions"}'::jsonb, 'hours/week', 'observed', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the Belgium country dashboard.'),
    ('FR', 'full_time_annual_earnings_range', 'cc_fr_66881288fe25', '{"low":26280,"high":32796,"ranking_value":26280,"currency":"EUR","basis":"annualised_private_sector_net_monthly_median_to_mean"}'::jsonb, 'EUR/year', 'calculated', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2024-12-31', 'Verified for the France country dashboard.'),
    ('FR', 'average_annual_salary', 'cc_fr_66881288fe25', '{"amount":32796,"currency":"EUR","basis":"annualised_private_sector_net_monthly_mean","statistic_type":"mean_net"}'::jsonb, 'EUR/year', 'calculated', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2024-12-31', 'Verified for the France country dashboard.'),
    ('FR', 'student_living_cost_monthly_range', 'cc_fr_63f1f741eb89', '{"low":800,"high":1350,"ranking_value":1075,"currency":"EUR","basis":"campus_france_student_budget_planning_range","scenario":"one higher-education student; tuition excluded"}'::jsonb, 'EUR/month', 'calculated', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the France country dashboard.'),
    ('FR', 'tuition_annual_low', 'cc_fr_479efffa7f17', '{"amount":2902,"currency":"EUR","basis":"differentiated_public_bachelor_fee_non_eu","study_level":"bachelor","student_type":"non-EU"}'::jsonb, 'EUR/year', 'observed', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-09-01', 'Verified for the France country dashboard.'),
    ('FR', 'tuition_annual_high', 'cc_fr_479efffa7f17', '{"amount":3950,"currency":"EUR","basis":"differentiated_public_master_fee_non_eu","study_level":"master","student_type":"non-EU"}'::jsonb, 'EUR/year', 'observed', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-09-01', 'Verified for the France country dashboard.'),
    ('FR', 'national_minimum_hourly_wage', 'cc_fr_901b846def26', '{"amount":12.02,"currency":"EUR","basis":"gross_hourly_smic"}'::jsonb, 'EUR/hour', 'observed', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-01-01', 'Verified for the France country dashboard.'),
    ('FR', 'student_work_hours_limit', 'cc_fr_f96a8a1b3fc8', '{"hours":18.54,"period":"week","annual_legal_limit_hours":964,"comparison_conversion":"964/52"}'::jsonb, 'hours/week', 'observed', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the France country dashboard.'),
    ('ES', 'full_time_annual_earnings_range', 'cc_es_b981c15fe415', '{"low":24016.8,"high":29540.26,"ranking_value":24016.8,"currency":"EUR","basis":"annualised_main_job_median_to_average_annual_salary"}'::jsonb, 'EUR/year', 'calculated', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2024-12-31', 'Verified for the Spain country dashboard.'),
    ('ES', 'average_annual_salary', 'cc_es_b981c15fe415', '{"amount":29540.26,"currency":"EUR","basis":"average_annual_salary_per_worker","statistic_type":"mean"}'::jsonb, 'EUR/year', 'observed', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2024-12-31', 'Verified for the Spain country dashboard.'),
    ('ES', 'student_living_cost_monthly_range', 'cc_es_b995324711d5', '{"low":700,"high":1200,"ranking_value":950,"currency":"EUR","basis":"national_student_planning_range","scenario":"one higher-education student; tuition excluded"}'::jsonb, 'EUR/month', 'calculated', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the Spain country dashboard.'),
    ('ES', 'student_work_hours_limit', 'cc_es_338313b6e22a', '{"hours":30,"period":"week","work_must_be_compatible_with_studies":true}'::jsonb, 'hours/week', 'observed', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the Spain country dashboard.'),
    ('SG', 'full_time_annual_earnings_range', 'cc_sg_996890efbd52', '{"low":64800,"high":166800,"ranking_value":100800,"currency":"SGD","basis":"annualised_p20_to_p80_gross_monthly_income_full_time_resident_pmes","population":"resident PMEs excluding APTs"}'::jsonb, 'SGD/year', 'calculated', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2025-12-31', 'Verified for the Singapore country dashboard.'),
    ('SG', 'average_annual_salary', 'cc_sg_996890efbd52', '{"amount":100800,"currency":"SGD","basis":"annualised_median_gross_monthly_income_full_time_resident_pmes","statistic_type":"median","population":"resident PMEs excluding APTs"}'::jsonb, 'SGD/year', 'calculated', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2025-12-31', 'Verified for the Singapore country dashboard.'),
    ('SG', 'student_living_cost_monthly_range', 'cc_sg_c2f03f3a4a67', '{"low":1267,"high":2000,"ranking_value":1600,"currency":"SGD","basis":"representative_official_university_student_budget","scenario":"one higher-education student; tuition excluded"}'::jsonb, 'SGD/month', 'calculated', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the Singapore country dashboard.'),
    ('SG', 'visa_application_fee', 'cc_sg_7e6181a20237', '{"amount":105,"currency":"SGD","basis":"student_pass_processing_plus_issuance_fee","processing_fee":45,"issuance_fee":60,"multiple_journey_visa_excluded":true}'::jsonb, 'SGD', 'calculated', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the Singapore country dashboard.'),
    ('SG', 'student_work_hours_limit', 'cc_sg_e3d13cdfaa1e', '{"hours":16,"period":"week","eligible_institutions_only":true,"applies_during":"school_term"}'::jsonb, 'hours/week', 'observed', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the Singapore country dashboard.'),
    ('KR', 'average_annual_salary', 'cc_kr_b8f5700528c5', '{"amount":50460000,"currency":"KRW","basis":"annualised_average_monthly_total_wage","statistic_type":"mean","monthly_amount":4205000}'::jsonb, 'KRW/year', 'calculated', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2025-12-31', 'Verified for the South Korea country dashboard.'),
    ('KR', 'student_living_cost_monthly_range', 'cc_kr_1e21ed2b8390', '{"low":750000,"high":1000000,"ranking_value":875000,"currency":"KRW","basis":"official_international_student_monthly_planning_range","scenario":"one higher-education student; tuition excluded"}'::jsonb, 'KRW/month', 'calculated', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the South Korea country dashboard.'),
    ('KR', 'tuition_annual_low', 'cc_kr_1e21ed2b8390', '{"amount":5640585,"currency":"KRW","basis":"official_published_average_tuition_benchmark","student_type":"international"}'::jsonb, 'KRW/year', 'observed', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2025-12-31', 'Verified for the South Korea country dashboard.'),
    ('KR', 'tuition_annual_high', 'cc_kr_1e21ed2b8390', '{"amount":7654030,"currency":"KRW","basis":"official_published_average_tuition_benchmark","student_type":"international"}'::jsonb, 'KRW/year', 'observed', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2025-12-31', 'Verified for the South Korea country dashboard.'),
    ('KR', 'national_minimum_hourly_wage', 'cc_kr_bd779bddcd23', '{"amount":10320,"currency":"KRW","basis":"national_minimum_wage"}'::jsonb, 'KRW/hour', 'observed', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-01-01', 'Verified for the South Korea country dashboard.'),
    ('KR', 'student_work_hours_limit', 'cc_kr_84a965b3eb73', '{"hours":30,"period":"week","basis":"common_qualified_undergraduate_maximum","permission_and_language_requirements_apply":true}'::jsonb, 'hours/week', 'observed', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the South Korea country dashboard.'),
    ('JP', 'average_annual_salary', 'cc_jp_7ef459d58e06', '{"amount":4271028,"currency":"JPY","basis":"annualised_average_monthly_cash_earnings","statistic_type":"mean","monthly_amount":355919}'::jsonb, 'JPY/year', 'calculated', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2025-12-31', 'Verified for the Japan country dashboard.'),
    ('JP', 'student_living_cost_monthly_range', 'cc_jp_f0af00e37387', '{"low":105000,"high":121000,"ranking_value":105000,"currency":"JPY","basis":"official_international_student_national_average_to_high_cost_city_planning","scenario":"one higher-education student; tuition excluded","national_average":105000}'::jsonb, 'JPY/month', 'calculated', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2025-12-31', 'Verified for the Japan country dashboard.'),
    ('JP', 'tuition_annual_low', 'cc_jp_81b1f26cc40e', '{"amount":820000,"currency":"JPY","basis":"representative_first_year_national_university_cost","study_level":"undergraduate"}'::jsonb, 'JPY/year', 'observed', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the Japan country dashboard.'),
    ('JP', 'tuition_annual_high', 'cc_jp_81b1f26cc40e', '{"amount":1300000,"currency":"JPY","basis":"representative_private_non_medical_first_year_cost","study_level":"undergraduate","medical_programmes_excluded":true}'::jsonb, 'JPY/year', 'observed', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the Japan country dashboard.'),
    ('JP', 'student_work_hours_limit', 'cc_jp_6aa1bdd58d2e', '{"hours":28,"period":"week","permission_for_activity_outside_status_required":true,"holiday_daily_limit_hours":8}'::jsonb, 'hours/week', 'observed', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the Japan country dashboard.'),
    ('NZ', 'student_living_cost_monthly_range', 'cc_nz_eaf54247823e', '{"low":1667,"high":2100,"ranking_value":1667,"currency":"NZD","basis":"student_visa_fund_requirement_to_planning_upper_bound","scenario":"one higher-education student; tuition excluded","annual_fund_requirement":20000}'::jsonb, 'NZD/month', 'calculated', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the New Zealand country dashboard.'),
    ('NZ', 'national_minimum_hourly_wage', 'cc_nz_e08645f00895', '{"amount":23.95,"currency":"NZD","basis":"adult_minimum_wage"}'::jsonb, 'NZD/hour', 'observed', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-04-01', 'Verified for the New Zealand country dashboard.'),
    ('NZ', 'visa_application_fee', 'cc_nz_eaf54247823e', '{"amount":850,"currency":"NZD","basis":"fee_paying_student_visa_online_cost_from"}'::jsonb, 'NZD', 'observed', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the New Zealand country dashboard.'),
    ('NZ', 'student_work_hours_limit', 'cc_nz_eaf54247823e', '{"hours":25,"period":"week","full_time_holiday_work_subject_to_conditions":true,"effective_change_date":"2025-11-03"}'::jsonb, 'hours/week', 'observed', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the New Zealand country dashboard.'),
    ('NO', 'average_annual_salary', 'cc_no_94563868de68', '{"amount":744840,"currency":"NOK","basis":"annualised_average_monthly_earnings_all_sectors","statistic_type":"mean","monthly_amount":62070}'::jsonb, 'NOK/year', 'calculated', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2025-12-31', 'Verified for the Norway country dashboard.'),
    ('NO', 'student_living_cost_monthly_range', 'cc_no_33508346a21c', '{"low":14700,"high":15488,"ranking_value":15488,"currency":"NOK","basis":"observed_student_average_to_official_permit_requirement","scenario":"one higher-education student; tuition excluded","permit_requirement_source":"https://studyinnorway.no/cost-and-requirements"}'::jsonb, 'NOK/month', 'calculated', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the Norway country dashboard.'),
    ('NO', 'student_work_hours_limit', 'cc_no_95414b48d411', '{"hours":20,"period":"week","full_time_holiday_work":true}'::jsonb, 'hours/week', 'observed', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the Norway country dashboard.'),
    ('SE', 'average_annual_salary', 'cc_se_6a2973c0ae0a', '{"amount":459600,"currency":"SEK","basis":"annualised_national_median_salary","statistic_type":"median","monthly_amount":38300}'::jsonb, 'SEK/year', 'calculated', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-06-16', 'Verified for the Sweden country dashboard.'),
    ('SE', 'student_living_cost_monthly_range', 'cc_se_05210578cf03', '{"low":10656,"high":13000,"ranking_value":10656,"currency":"SEK","basis":"official_maintenance_requirement_to_planning_upper_bound","scenario":"one higher-education student; tuition excluded"}'::jsonb, 'SEK/month', 'calculated', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-01-01', 'Verified for the Sweden country dashboard.'),
    ('SE', 'tuition_annual_low', 'cc_se_8989f52c4175', '{"amount":80000,"currency":"SEK","basis":"published_non_eu_tuition_planning_range","student_type":"non-EU/EEA"}'::jsonb, 'SEK/year', 'observed', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the Sweden country dashboard.'),
    ('SE', 'tuition_annual_high', 'cc_se_8989f52c4175', '{"amount":295000,"currency":"SEK","basis":"published_non_eu_tuition_planning_range","student_type":"non-EU/EEA"}'::jsonb, 'SEK/year', 'observed', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the Sweden country dashboard.'),
    ('SE', 'student_work_hours_limit', 'cc_se_05210578cf03', '{"hours":15,"period":"week","applies_to":"bachelor_master_permits_granted_on_or_after_effective_date","summer_months_unrestricted":["June","July","August"]}'::jsonb, 'hours/week', 'observed', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-06-11', 'Verified for the Sweden country dashboard.'),
    ('DK', 'student_living_cost_monthly_range', 'cc_dk_a74deaa02709', '{"low":7426,"high":9000,"ranking_value":7426,"currency":"DKK","basis":"official_support_requirement_to_student_budget_planning","scenario":"one higher-education student; tuition excluded"}'::jsonb, 'DKK/month', 'calculated', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-01-01', 'Verified for the Denmark country dashboard.'),
    ('DK', 'tuition_annual_low', 'cc_dk_661e72c9fa65', '{"amount":45000,"currency":"DKK","basis":"published_non_eu_eea_tuition_range","student_type":"non-EU/EEA"}'::jsonb, 'DKK/year', 'observed', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the Denmark country dashboard.'),
    ('DK', 'tuition_annual_high', 'cc_dk_661e72c9fa65', '{"amount":120000,"currency":"DKK","basis":"published_non_eu_eea_tuition_range","student_type":"non-EU/EEA"}'::jsonb, 'DKK/year', 'observed', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the Denmark country dashboard.'),
    ('DK', 'visa_application_fee', 'cc_dk_27547da3a09d', '{"amount":3060,"currency":"DKK","basis":"study_case_processing_fee"}'::jsonb, 'DKK', 'observed', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-01-01', 'Verified for the Denmark country dashboard.'),
    ('DK', 'student_work_hours_limit', 'cc_dk_a74deaa02709', '{"hours":20.77,"period":"week","monthly_limit_hours":90,"comparison_conversion":"90*12/52","applies_during":"September_to_May","summer_full_time_months":["June","July","August"]}'::jsonb, 'hours/week', 'observed', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the Denmark country dashboard.'),
    ('FI', 'full_time_annual_earnings_range', 'cc_fi_c39fc3978473', '{"low":43380,"high":48840,"ranking_value":43380,"currency":"EUR","basis":"annualised_full_time_median_to_average_total_earnings"}'::jsonb, 'EUR/year', 'calculated', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2024-12-31', 'Verified for the Finland country dashboard.'),
    ('FI', 'average_annual_salary', 'cc_fi_7c240dc9c797', '{"amount":48840,"currency":"EUR","basis":"annualised_average_total_earnings_full_time","statistic_type":"mean","monthly_amount":4070}'::jsonb, 'EUR/year', 'calculated', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2024-12-31', 'Verified for the Finland country dashboard.'),
    ('FI', 'student_living_cost_monthly_range', 'cc_fi_adfb6af384ae', '{"low":900,"high":1200,"ranking_value":1050,"currency":"EUR","basis":"official_student_monthly_planning_range","scenario":"one higher-education student; tuition excluded"}'::jsonb, 'EUR/month', 'calculated', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the Finland country dashboard.'),
    ('FI', 'tuition_annual_low', 'cc_fi_adfb6af384ae', '{"amount":8000,"currency":"EUR","basis":"published_non_eu_eea_tuition_range","student_type":"non-EU/EEA"}'::jsonb, 'EUR/year', 'observed', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the Finland country dashboard.'),
    ('FI', 'tuition_annual_high', 'cc_fi_adfb6af384ae', '{"amount":20000,"currency":"EUR","basis":"published_non_eu_eea_tuition_range","student_type":"non-EU/EEA"}'::jsonb, 'EUR/year', 'observed', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the Finland country dashboard.'),
    ('FI', 'visa_application_fee', 'cc_fi_b0778fd0ae0f', '{"amount":600,"currency":"EUR","basis":"online_first_student_residence_permit_fee"}'::jsonb, 'EUR', 'observed', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the Finland country dashboard.'),
    ('FI', 'student_work_hours_limit', 'cc_fi_b0778fd0ae0f', '{"hours":30,"period":"week","basis":"average_weekly_limit_over_calendar_year"}'::jsonb, 'hours/week', 'observed', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the Finland country dashboard.'),
    ('CH', 'average_annual_salary', 'cc_ch_b1bd29658400', '{"amount":84288,"currency":"CHF","basis":"annualised_gross_standardised_monthly_median","statistic_type":"median","monthly_amount":7024}'::jsonb, 'CHF/year', 'calculated', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2024-12-31', 'Verified for the Switzerland country dashboard.'),
    ('CH', 'student_living_cost_monthly_range', 'cc_ch_1d70240b880e', '{"low":1850,"high":2200,"ranking_value":2000,"currency":"CHF","basis":"official_university_student_budget_planning_range","scenario":"one higher-education student; tuition excluded"}'::jsonb, 'CHF/month', 'calculated', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the Switzerland country dashboard.'),
    ('CH', 'tuition_annual_low', 'cc_ch_1d70240b880e', '{"amount":870,"currency":"CHF","basis":"public_university_foreign_student_fee_range_annualised","institution_type":"public"}'::jsonb, 'CHF/year', 'observed', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the Switzerland country dashboard.'),
    ('CH', 'tuition_annual_high', 'cc_ch_1d70240b880e', '{"amount":8000,"currency":"CHF","basis":"public_university_foreign_student_fee_range_annualised","institution_type":"public"}'::jsonb, 'CHF/year', 'observed', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the Switzerland country dashboard.'),
    ('CH', 'student_work_hours_limit', 'cc_ch_d79f6dcc696f', '{"hours":15,"period":"week","authorisation_required":true,"waiting_period_may_apply":true}'::jsonb, 'hours/week', 'observed', 'high', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the Switzerland country dashboard.'),
    ('AE', 'student_living_cost_monthly_range', 'cc_ae_0ae8eb9d16e3', '{"low":6250,"high":7100,"ranking_value":6675,"currency":"AED","basis":"representative_official_university_on_to_off_campus_budget","scenario":"one higher-education student; tuition excluded","national_average":false}'::jsonb, 'AED/month', 'calculated', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the United Arab Emirates country dashboard.'),
    ('AE', 'tuition_annual_low', 'cc_ae_60ad1e9beee7', '{"amount":57600,"currency":"AED","basis":"representative_official_university_undergraduate_range","national_range":false}'::jsonb, 'AED/year', 'observed', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the United Arab Emirates country dashboard.'),
    ('AE', 'tuition_annual_high', 'cc_ae_60206a672827', '{"amount":90000,"currency":"AED","basis":"representative_official_university_undergraduate_range","national_range":false}'::jsonb, 'AED/year', 'observed', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-08-06', 'Verified for the United Arab Emirates country dashboard.'),
    ('AE', 'visa_application_fee', 'cc_ae_c99610a75275', '{"amount":300,"currency":"AED","basis":"base_residence_application_issuance_and_smart_service_planning","medical_emirates_id_insurance_and_university_fees_excluded":true}'::jsonb, 'AED', 'calculated', 'medium', 'Published official figure or transparent calculation from the cited official source.', '{}'::jsonb, date '2026-02-18', 'Verified for the United Arab Emirates country dashboard.')
  ) as v(scope_id, metric_key, source_key, value, unit, evidence_kind, confidence, methodology, assumptions, effective_from, reviewer_note)
  loop
    select ss.id into snapshot_id_value
    from evidence.sources s join evidence.source_snapshots ss on ss.source_id=s.id
    where s.source_key=metric_row.source_key order by ss.retrieved_at desc limit 1;
    if snapshot_id_value is null then raise exception 'Missing source snapshot for %', metric_row.source_key; end if;
    insert into evidence.metric_observations (metric_key, scope_type, scope_id, value, unit, source_snapshot_id, evidence_kind, confidence, methodology, assumptions, effective_from, review_status, reviewed_at, reviewer_note)
    values (metric_row.metric_key, 'country', metric_row.scope_id, metric_row.value, metric_row.unit, snapshot_id_value, metric_row.evidence_kind, metric_row.confidence, metric_row.methodology, metric_row.assumptions, metric_row.effective_from, 'verified', now(), metric_row.reviewer_note);
  end loop;
end $$;

delete from public.report_metric_evidence_country where scope_type='country' and scope_id in ('IE', 'DE', 'NL', 'BE', 'FR', 'ES', 'SG', 'KR', 'JP', 'NZ', 'NO', 'SE', 'DK', 'FI', 'CH', 'AE') and metric_key in ('full_time_annual_earnings_range', 'average_annual_salary', 'student_living_cost_monthly_range', 'tuition_annual_low', 'tuition_annual_high', 'national_minimum_hourly_wage', 'visa_application_fee', 'student_work_hours_limit');
insert into public.report_metric_evidence_country (scope_type, scope_id, metric_key, value, source_name, source_url, data_as_of, last_verified_at, confidence, evidence_kind, review_status, created_at, updated_at)
select o.scope_type, o.scope_id, o.metric_key, o.value, s.source_name, ss.source_url, coalesce(ss.data_as_of,o.effective_from,current_date), coalesce(o.reviewed_at,o.updated_at,now()), o.confidence, o.evidence_kind, o.review_status, o.created_at, o.updated_at
from evidence.metric_observations o
join evidence.source_snapshots ss on ss.id=o.source_snapshot_id
join evidence.sources s on s.id=ss.source_id
where o.scope_type='country' and o.scope_id in ('IE', 'DE', 'NL', 'BE', 'FR', 'ES', 'SG', 'KR', 'JP', 'NZ', 'NO', 'SE', 'DK', 'FI', 'CH', 'AE') and o.review_status='verified' and o.metric_key in ('full_time_annual_earnings_range', 'average_annual_salary', 'student_living_cost_monthly_range', 'tuition_annual_low', 'tuition_annual_high', 'national_minimum_hourly_wage', 'visa_application_fee', 'student_work_hours_limit');
;
