-- Japan Design / Creative occupation cohort.
-- Classification basis: 2022 revision of the Ministry of Health, Labour and Welfare occupation classification.

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('JP:graphic-designer','JP','graphic-designer','グラフィックデザイナー','MHLW Occupation Classification','2022','017-02','JPY',false,null,null,'profile_ready','2026-08-11',now()),
('JP:ux-designer','JP','ux-designer','UX/UIデザイナー','MHLW Occupation Classification','2022','009-99','JPY',false,null,null,'profile_ready','2026-08-11',now()),
('JP:multimedia-designer','JP','multimedia-designer','マルチメディアデザイナー — digital media/design-production umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-11',now()),
('JP:animator','JP','animator','アニメーター — 2D/3D animation umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-11',now()),
('JP:interior-designer','JP','interior-designer','インテリアデザイナー','MHLW Occupation Classification','2022','017-99','JPY',false,null,null,'profile_ready','2026-08-11',now()),
('JP:film-editor','JP','film-editor','映像編集者','MHLW Occupation Classification','2022','020-99','JPY',false,null,null,'profile_ready','2026-08-11',now()),
('JP:architect','JP','architect','建築設計技術者 — architect scope','MHLW Occupation Classification','2022','008-01','JPY',true,'国土交通省 / 都道府県 — 建築士免許','https://www.mlit.go.jp/jutakukentiku/build/architect.html','profile_ready','2026-08-11',now()),
('JP:web-designer','JP','web-designer','ウェブデザイナー','MHLW Occupation Classification','2022','017-01','JPY',false,null,null,'profile_ready','2026-08-11',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at) values
('JP:graphic-designer','2026-08-11',0,0,0,0,15,0,0,0,5,20,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','MHLW 017-02 directly classifies グラフィックデザイナー and examples such as advertising, sign and package designers.','entry_level_basis','Formal qualification is not universally required; portfolio quality and visual-design capability are central. Reviewed Japanese design programmes are retained as related study pathways.','qualification_note','No universal statutory Graphic Designer licence applies.','market_scope','No exact recurring comparable 017-02 market series is scored in the foundation phase.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('JP:ux-designer','2026-08-11',0,0,0,0,12,0,0,0,5,17,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','MHLW job tag maps UX/UIデザイナー to 009-99 その他の情報処理・通信技術者（ソフトウェア開発）. This is retained as the official current anchor even though the role is design-led.','entry_level_basis','Interaction design, visual communication, product design, psychology, information design and portfolio-based experience can lead into UX/UI work; the reviewed Japanese programme is related rather than an occupational qualification.','qualification_note','No universal statutory UX/UI Designer licence applies.','market_scope','The 009-99 group includes other software-development work, so group statistics are not treated as exact UX Designer observations.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('JP:multimedia-designer','2026-08-11',0,0,0,0,12,0,0,0,5,17,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','Japan does not publish one standalone Multimedia Designer small-classification code. The canonical role spans digital visual/CG design under 017-99 and broader media-content production under 020-99 depending on duties.','entry_level_basis','Digital media, visual communication, motion, interaction and media-production study can support entry; three reviewed programmes are retained as related pathways.','qualification_note','No universal statutory Multimedia Designer licence applies.','market_scope','017-99 and 020-99 are kept as non-rollup references rather than merged into an artificial multimedia labour series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('JP:animator','2026-08-11',0,0,0,0,15,0,0,0,5,20,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','MHLW job tag maps 2D アニメーター to 080-03 画工・看板制作工, while 3D/CG animation overlaps 017-99 CGデザイナー. CampCareer therefore keeps Animator as an umbrella.','entry_level_basis','No particular academic credential is universally required; animation studios commonly assess drawing, motion and digital-production portfolios. The reviewed media programme is related rather than an occupational qualification.','qualification_note','No universal statutory Animator licence applies.','market_scope','The official statistical anchors are broader than the canonical Animator role and are not merged into one exact market series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('JP:interior-designer','2026-08-11',0,0,0,0,12,0,0,0,5,17,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','MHLW 017-99 explicitly includes インテリアデザイナー, インテリアコーディネーター and インテリアプランナー.','entry_level_basis','Interior, spatial and residential design study plus portfolio work are common routes; the reviewed Japanese residential/interior programme is retained as a direct academic pathway.','qualification_note','No universal statutory Interior Designer licence applies. Interior design must be distinguished from architectural design or statutory building-design work that may require 建築士 qualification.','market_scope','017-99 contains many other design occupations, so shared market statistics are not treated as exact Interior Designer values.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('JP:film-editor','2026-08-11',0,0,0,0,15,0,0,0,5,20,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','MHLW job tag maps 映像編集者 / 動画編集者 to 020-99 他に分類されない法務・経営・文化芸術等の専門的職業.','entry_level_basis','Film, video, broadcasting and media-production study can support entry, but academic qualifications are not universally required; editing reels and production experience are central. The reviewed media programme is related.','qualification_note','No universal statutory Film Editor licence applies.','market_scope','020-99 is a broad residual professional group, so its statistics are not treated as exact Film Editor evidence.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('JP:architect','2026-08-11',0,0,0,0,8,0,0,0,1,9,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','MHLW 008-01 建築設計技術者 directly covers architectural design and construction-supervision technical work.','entry_level_basis','Architecture study is the direct academic foundation. One reviewed Japanese architecture programme is retained as direct and one residential/interior programme as related; programme completion alone is not a 建築士 licence.','qualification_note','Japan regulates the 建築士 profession. 一級建築士 requires passing the national examination and obtaining ministerial licence/registration; 二級建築士 and 木造建築士 are prefectural licences. Certain building design and construction-supervision work must be performed by an appropriately qualified architect.','market_scope','008-01 includes architectural-design technicians broadly, while statutory architect practice depends on licence class and building scope; the foundation phase does not score market demand.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('JP:web-designer','2026-08-11',0,0,0,0,15,0,0,0,5,20,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','MHLW 017-01 directly classifies ウェブデザイナー, Webクリエイター and homepage designers, while programming and HTML coding are separately classified under 009-03.','entry_level_basis','Visual/web design, interaction and front-end production study plus a portfolio are common routes; the reviewed Japanese communication-design programme is related rather than an occupational qualification.','qualification_note','No universal statutory Web Designer licence applies.','market_scope','Web programming is intentionally excluded from the 017-01 design scope and no broader IT series is substituted as exact Web Designer market evidence.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11')
on conflict (profile_key,as_of_date) do update set shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('JP:graphic-designer','017-02','グラフィックデザイナー',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1&pageNo=3','2026-08-11'),
('JP:ux-designer','009-99','UX/UIデザイナー — job tag official anchor',null,null,true,1,'https://shigoto.mhlw.go.jp/User/Occupation/Detail/552','2026-08-11'),
('JP:multimedia-designer','017-99','CG・デジタルビジュアルデザイン scope',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1&pageNo=3','2026-08-11'),
('JP:multimedia-designer','020-99','デジタルメディア制作 scope',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1&pageNo=3','2026-08-11'),
('JP:animator','080-03','画工・看板制作工 — 2D animator job-tag scope',null,null,false,1,'https://shigoto.mhlw.go.jp/User/Occupation/Detail/343','2026-08-11'),
('JP:animator','017-99','CGデザイナー — 3D/CG animation reference',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1&pageNo=3','2026-08-11'),
('JP:interior-designer','017-99','インテリアデザイナー',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1&pageNo=3','2026-08-11'),
('JP:film-editor','020-99','映像編集者・動画編集者',null,null,true,1,'https://shigoto.mhlw.go.jp/User/Occupation/Detail?occupationId=214','2026-08-11'),
('JP:architect','008-01','建築設計技術者 — architect/design scope',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-11'),
('JP:web-designer','017-01','ウェブデザイナー',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1&pageNo=3','2026-08-11')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'job_search','Hello Work job search','https://www.hellowork.mhlw.go.jp/kensaku/GECA110010.do','government',10,'2026-08-11' from public.country_occupation_profiles p where p.country_code='JP' and p.canonical_career_id in ('graphic-designer','ux-designer','multimedia-designer','animator','interior-designer','film-editor','architect','web-designer')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'source','MHLW 2022 occupation classification','https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','government',20,'2026-08-11' from public.country_occupation_profiles p where p.country_code='JP' and p.canonical_career_id in ('graphic-designer','ux-designer','multimedia-designer','animator','interior-designer','film-editor','architect','web-designer')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
values ('JP:architect','source','MLIT architect licensing','https://www.mlit.go.jp/jutakukentiku/build/architect.html','government',30,'2026-08-11')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'JP:'||o.canonical_career_id,c.source_program_key,case when o.relation_type='direct' then 'direct' else 'related' end,coalesce(o.source_checked_at,'2026-08-11'::date)
from public.program_occupation_jp_staging o
join public.program_catalog_jp_staging c on c.id=o.program_catalog_id
where o.review_status='approved'
  and o.canonical_career_id in ('graphic-designer','ux-designer','multimedia-designer','animator','interior-designer','film-editor','architect','web-designer')
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;;
