-- Australia Baker profile.
-- Current OSCA 322131 Baker is exact; Pastrycook remains separate.
-- Legacy ANZSCO 351111 labour data are exact context; broader 3511 IVI/projections remain contextual.

update public.courses_au set official_course_url='https://www.cdu.edu.au/study/course/fbp30521-certificate-iii-baking-fbp30521',official_url_status='verified',official_url_checked_at=now(),official_url_source='CDU current Certificate III in Baking page, CRICOS 107364E, verified 2026-08-09' where institution_id='charles-darwin-university' and course_code='107364E';
update public.courses_au set official_course_url='https://www.tafensw.edu.au/international/courses/certificate-iii-in-patisserie--SIT31021',official_url_status='verified',official_url_checked_at=now(),official_url_source='TAFE NSW International Certificate III in Patisserie page, CRICOS 109757E, verified 2026-08-09' where institution_id='tafe-nsw' and course_code='109757E';

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('AU:baker','AU','baker','Baker','OSCA','2024 v1.0','3221','AUD',false,'No universal statutory registration; Trades Recognition Australia assesses legacy ANZSCO 351111 Baker for migration','https://www.tradesrecognitionaustralia.gov.au/','profile_ready','2026-08-09',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,employment_total,median_weekly_earnings,median_hourly_earnings,annualised_median_salary,all_occupations_median_weekly,part_time_share_pct,female_share_pct,median_age,average_full_time_hours,vacancies_three_month_avg,vacancy_period,vacancy_yoy_pct,employment_growth_5y_pct,employment_growth_10y_pct,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at) values
('AU:baker','2026-05-01',18700,null,null,null,1852,34,28,36,43,424.66667,'2026-05-01',8.89,2.96,8.05,20,0,5,0,15,0,5,10,5,60,'career-opportunity-v1','provisional',jsonb_build_object(
'classification_scope','Current OSCA 322131 Baker is an exact canonical occupation. Pastrycook 322431 is separate.',
'labour_scope','JSA legacy ANZSCO 351111 provides exact contextual employment and demographics: 18,700 workers, 34% part-time, 28% female, median age 36 and 43 average full-time hours. Reviewed exact earnings are unavailable.',
'vacancy_scope','Broader ANZSCO 3511 vacancies were 424.66667 in May 2026 versus 390 in May 2025, about +8.89% year on year; vacancy intensity and trend receive zero credit because the series includes Pastrycooks.',
'projection_scope','Broader ANZSCO 3511 projections are +2.96% to 2030 and +8.05% to 2035; partial growth credit only.',
'shortage_note','JSA 2025 OSL records current OSCA 322131 Baker as a national Shortage occupation.',
'visa_basis','The current skilled occupation instrument includes legacy ANZSCO 351111 Baker with Trades Recognition Australia as assessing authority.',
'entry_level_basis','CDU Certificate III in Baking 107364E is a direct trade route; TAFE NSW Certificate III in Patisserie 109757E is a related pastry-focused route.',
'entry_burden_basis','No universal occupational licence applies, but trade competence and migration assessment require practical evidence under the applicable TRA pathway.',
'score_note','Exact employment context, national shortage, direct training and current migration evidence are retained; salary and broader vacancy signals remain unscored.'
),'2026-08-09')
on conflict (profile_key,as_of_date) do update set employment_total=excluded.employment_total,median_weekly_earnings=excluded.median_weekly_earnings,median_hourly_earnings=excluded.median_hourly_earnings,annualised_median_salary=excluded.annualised_median_salary,all_occupations_median_weekly=excluded.all_occupations_median_weekly,part_time_share_pct=excluded.part_time_share_pct,female_share_pct=excluded.female_share_pct,median_age=excluded.median_age,average_full_time_hours=excluded.average_full_time_hours,vacancies_three_month_avg=excluded.vacancies_three_month_avg,vacancy_period=excluded.vacancy_period,vacancy_yoy_pct=excluded.vacancy_yoy_pct,employment_growth_5y_pct=excluded.employment_growth_5y_pct,employment_growth_10y_pct=excluded.employment_growth_10y_pct,shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,legacy_code_system,legacy_code_version,legacy_code,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('AU:baker','322131','Baker','ANZSCO','2022','351111',null,true,true,1,'https://www.abs.gov.au/statistics/classifications/osca-occupation-standard-classification-australia/2024-version-1-0/browse-classification/3/32/322/3221/322131','2026-08-09')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,legacy_code_system=excluded.legacy_code_system,legacy_code_version=excluded.legacy_code_version,legacy_code=excluded.legacy_code,shortage_rating=excluded.shortage_rating,visa_eligible=excluded.visa_eligible,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_region_metrics (profile_key,region_code,as_of_date,shortage_rating,vacancy_count,source_url) values
('AU:baker','ACT','2026-05-01',null,5,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:baker','NSW','2026-05-01',null,116,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:baker','NT','2026-05-01',null,1,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:baker','QLD','2026-05-01',null,91.33333,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:baker','SA','2026-05-01',null,24.66667,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:baker','TAS','2026-05-01',null,14.33333,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:baker','VIC','2026-05-01',null,120,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:baker','WA','2026-05-01',null,52.33333,'https://www.jobsandskills.gov.au/data/internet-vacancy-index')
on conflict (profile_key,region_code,as_of_date) do update set shortage_rating=excluded.shortage_rating,vacancy_count=excluded.vacancy_count,source_url=excluded.source_url;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,region_code,sort_order,source_checked_at) values
('AU:baker','employer','Bakers Delight Careers','https://www.bakersdelight.com.au/careers/','bakery',null,1,'2026-08-09'),('AU:baker','employer','Woolworths Careers','https://www.wowcareers.com.au/','retail',null,2,'2026-08-09'),('AU:baker','employer','Coles Careers','https://colescareers.com.au/','retail',null,3,'2026-08-09'),('AU:baker','employer','Costco Australia Careers','https://www.costco.com.au/careers','retail',null,4,'2026-08-09'),('AU:baker','employer','Tip Top Careers','https://careers.gwf.com.au/','food_manufacturing',null,5,'2026-08-09'),
('AU:baker','entry_program','CDU — Certificate III in Baking','https://www.cdu.edu.au/study/course/fbp30521-certificate-iii-baking-fbp30521','university_vet',null,1,'2026-08-09'),('AU:baker','entry_program','TAFE NSW — Certificate III in Patisserie','https://www.tafensw.edu.au/international/courses/certificate-iii-in-patisserie--SIT31021','tafe',null,2,'2026-08-09'),
('AU:baker','source','ABS — OSCA 322131 Baker','https://www.abs.gov.au/statistics/classifications/osca-occupation-standard-classification-australia/2024-version-1-0/browse-classification/3/32/322/3221/322131','official_classification',null,1,'2026-08-09'),('AU:baker','source','JSA — 2025 Occupation Shortage List','https://www.jobsandskills.gov.au/data/occupation-shortage-analysis/occupation-shortage-list','official_shortage',null,2,'2026-08-09'),('AU:baker','source','Trades Recognition Australia','https://www.tradesrecognitionaustralia.gov.au/','official_skills_assessment',null,3,'2026-08-09')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,region_code=excluded.region_code,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'AU:baker','au-program:'||id::text,case when course_code='107364E' then 'direct' else 'related' end,'2026-08-09' from public.courses_au where (institution_id='charles-darwin-university' and course_code='107364E') or (institution_id='tafe-nsw' and course_code='109757E')
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;;
