-- Japan Business occupation cohort.
-- Classification basis: 2022 revision of the Ministry of Health, Labour and Welfare occupation classification.

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('JP:accountant','JP','accountant','経理事務員 — general employee-accounting scope','MHLW Occupation Classification','2022','038-03','JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:financial-analyst','JP','financial-analyst','経営・金融・保険の専門職 — financial/securities analyst scope','MHLW Occupation Classification','2022','013-99','JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:business-analyst','JP','business-analyst','ビジネスアナリスト — management consulting/planning umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:supply-chain-analyst','JP','supply-chain-analyst','サプライチェーンアナリスト — planning/logistics analysis umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:human-resources-specialist','JP','human-resources-specialist','人事事務員 — HR specialist scope','MHLW Occupation Classification','2022','033-02','JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:marketing-specialist','JP','marketing-specialist','企画・調査事務員 — marketing scope','MHLW Occupation Classification','2022','033-03','JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:auditor','JP','auditor','監査職 — external/internal audit umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:project-manager','JP','project-manager','プロジェクトマネージャ — cross-industry umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-10',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at) values
('JP:accountant','2026-08-10',0,0,0,0,15,0,0,0,5,20,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','MHLW 038-03 covers employee accounting work including ledgers, monthly/year-end statements and tax-document preparation, while excluding statutory CPA audit work.','entry_level_basis','Accounting, commerce and business study support entry; one reviewed Japanese accounting programme is retained as direct.','qualification_note','General employee accountants do not require the 公認会計士 credential merely to work in accounting.','market_scope','Market enrichment is deferred until all country occupation foundations are complete.','visa_scope','No occupation-specific visa credit is assigned in the foundation phase.'),'2026-08-10'),
('JP:financial-analyst','2026-08-10',0,0,0,0,10,0,0,0,5,15,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','MHLW 013-99 explicitly includes 証券アナリスト and professional financial-analysis work, used here only for the financial-analyst scope.','entry_level_basis','Finance, economics, accounting and quantitative business study are common foundations; five reviewed programmes remain related rather than job guarantees.','qualification_note','No single statutory personal licence covers every financial analyst role.','market_scope','Salary, vacancies, shortage and growth are intentionally unscored pending later market enrichment.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:business-analyst','2026-08-10',0,0,0,0,10,0,0,0,5,15,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','Non-ICT Business Analyst duties overlap MHLW 013-99 management-consulting work and 033-03 planning/research analysis; neither code alone represents the full canonical occupation.','entry_level_basis','Business, economics, analytics and management study can support entry; three approved programmes are retained as related pathways.','qualification_note','There is no universal statutory Business Analyst licence.','market_scope','No blended management-consulting/planning labour series is fabricated.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:supply-chain-analyst','2026-08-10',0,0,0,0,10,0,0,0,5,15,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','Japan has no standalone MHLW Supply Chain Analyst code; relevant planning, production/material planning and logistics-management administration appear across 033-03, 039-01 and 039-02.','entry_level_basis','Industrial engineering, logistics, operations, economics and business study are relevant; two approved programmes remain related.','qualification_note','No universal statutory Supply Chain Analyst licence applies.','market_scope','Operational logistics and production-office statistics are not merged into an analyst-only series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:human-resources-specialist','2026-08-10',0,0,0,0,15,0,0,0,5,20,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','MHLW 033-02 directly covers recruitment, evaluation, payroll, training, welfare and labour-management HR administration.','entry_level_basis','Business, HR, psychology and related study can support entry, alongside employer-based development.','qualification_note','No universal statutory HR specialist licence is required.','market_scope','Market data remain unscored until the common enrichment phase.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:marketing-specialist','2026-08-10',0,0,0,0,15,0,0,0,5,20,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','MHLW 033-03 explicitly includes marketers, marketing research, web marketing and sales-promotion planning, making it the direct planning/analysis anchor for the canonical Marketing Specialist.','entry_level_basis','Marketing, communications, business and analytics study plus campaign/project evidence support entry; two approved programmes remain related.','qualification_note','No universal statutory Marketing Specialist licence applies.','market_scope','Advertising-sales and general sales codes are not substituted for marketing-specialist market evidence.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:auditor','2026-08-10',0,0,0,0,10,0,0,0,2,12,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','The neutral Auditor career spans external statutory financial audit under 013-01 公認会計士 and internal audit under 033-01 内部監査員, so no single code is claimed.','entry_level_basis','Accounting and business study can lead toward audit work; the one approved accounting programme is related and does not confer CPA status.','qualification_note','Statutory CPA audit work requires the 公認会計士 qualification/registration framework, while internal audit does not have the same universal statutory registration.','market_scope','External and internal audit markets are not merged into a fabricated exact series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:project-manager','2026-08-10',0,0,0,0,10,0,0,0,3,13,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','MHLW has a specific 010-03 IT Project Manager and 035-99 PMO support role, but no one cross-industry Project Manager code matching the canonical career.','entry_level_basis','Project-management entry is sector dependent and usually combines domain knowledge with planning, coordination and delivery experience; five reviewed programmes remain related.','qualification_note','No universal statutory cross-industry Project Manager licence applies.','market_scope','IT project-management data are not presented as the generic cross-industry market.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10')
on conflict (profile_key,as_of_date) do update set shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('JP:accountant','038-03','経理事務員 — general employee-accounting scope',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:financial-analyst','013-99','その他の経営・金融・保険の専門的職業 — financial/securities analyst scope',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:business-analyst','013-99','経営コンサルタント scope',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:business-analyst','033-03','企画・調査事務員 — business planning/analysis scope',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:supply-chain-analyst','033-03','企画・調査事務員 — planning/analysis reference',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:supply-chain-analyst','039-01','生産現場事務員 — materials/production planning reference',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:supply-chain-analyst','039-02','出荷・受荷係事務員 — logistics/inventory administration reference',null,null,false,3,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:human-resources-specialist','033-02','人事事務員 — HR specialist scope',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:marketing-specialist','033-03','企画・調査事務員 — marketing planning/research scope',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:auditor','013-01','公認会計士 — statutory external-audit scope',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:auditor','033-01','内部監査員 — internal-audit scope',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:project-manager','010-03','ITプロジェクトマネージャ — sector-specific reference',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:project-manager','035-99','PMO事務員 — project-support reference',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'job_search','Hello Work job search','https://www.hellowork.mhlw.go.jp/kensaku/GECA110010.do','government',10,'2026-08-10' from public.country_occupation_profiles p where p.country_code='JP' and p.canonical_career_id in ('accountant','financial-analyst','business-analyst','supply-chain-analyst','human-resources-specialist','marketing-specialist','auditor','project-manager')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'source','2022 MHLW occupation classification','https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','government',20,'2026-08-10' from public.country_occupation_profiles p where p.country_code='JP' and p.canonical_career_id in ('accountant','financial-analyst','business-analyst','supply-chain-analyst','human-resources-specialist','marketing-specialist','auditor','project-manager')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at) values
('JP:auditor','source','FSA — CPA and audit system','https://www.fsa.go.jp/policy/kouninkaikeishi/index.html','government',30,'2026-08-10'),
('JP:auditor','source','CPAAOB — CPA registration requirements','https://www.fsa.go.jp/cpaaob/kouninkaikeishi-shiken/toroku.html','government',31,'2026-08-10')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'JP:'||o.canonical_career_id,c.source_program_key,case when o.relation_type='direct' then 'direct' else 'related' end,coalesce(o.source_checked_at,'2026-08-10'::date)
from public.program_occupation_jp_staging o
join public.program_catalog_jp_staging c on c.id=o.program_catalog_id
where o.review_status='approved'
  and o.canonical_career_id in ('accountant','financial-analyst','business-analyst','supply-chain-analyst','human-resources-specialist','marketing-specialist','auditor','project-manager')
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;;
