-- Japan Education / Social Services occupation cohort.
-- Classification basis: 2022 revision of the Ministry of Health, Labour and Welfare occupation classification.

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('JP:early-childhood-teacher','JP','early-childhood-teacher','幼稚園教員','MHLW Occupation Classification','2022','029-02','JPY',true,'都道府県教育委員会 — 幼稚園教諭免許状','https://www.mext.go.jp/a_menu/shotou/kyoin/daigaku/1286948.htm','profile_ready','2026-08-10',now()),
('JP:primary-school-teacher','JP','primary-school-teacher','小学校教員','MHLW Occupation Classification','2022','031-01','JPY',true,'都道府県教育委員会 — 小学校教諭免許状','https://www.mext.go.jp/a_menu/shotou/kyoin/daigaku/1286948.htm','profile_ready','2026-08-10',now()),
('JP:secondary-school-teacher','JP','secondary-school-teacher','中学校・高等学校教員 — secondary-teacher umbrella','MHLW Occupation Classification','2022',null,'JPY',true,'都道府県教育委員会 — 中学校・高等学校教諭免許状','https://www.mext.go.jp/a_menu/shotou/kyoin/daigaku/1286948.htm','profile_ready','2026-08-10',now()),
('JP:special-education-teacher','JP','special-education-teacher','特別支援学校教員','MHLW Occupation Classification','2022','031-06','JPY',true,'都道府県教育委員会 — 特別支援学校教諭免許状','https://www.mext.go.jp/a_menu/shotou/kyoin/main13_a2.htm','profile_ready','2026-08-10',now()),
('JP:social-worker','JP','social-worker','社会福祉士 — cross-setting social-work scope','MHLW Occupation Classification','2022',null,'JPY',true,'厚生労働省 — 社会福祉士','https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/hukushi_kaigo/seikatsuhogo/shakai-kaigo-fukushi1/index.html','profile_ready','2026-08-10',now()),
('JP:youth-worker','JP','youth-worker','児童・青少年支援員 — youth-support umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:community-worker','JP','community-worker','地域福祉活動専門員 — community-welfare scope','MHLW Occupation Classification','2022','049-99','JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:counsellor','JP','counsellor','カウンセラー — general non-medical/welfare scope','MHLW Occupation Classification','2022','019-03','JPY',false,null,null,'profile_ready','2026-08-10',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at) values
('JP:early-childhood-teacher','2026-08-10',0,0,0,0,10,0,0,0,1,11,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','2022 MHLW 029-02 directly classifies 幼稚園教員 and is kept separate from 保育士 029-01.','entry_level_basis','An approved Japanese child-education programme is retained as a direct study pathway where the institution offers the required teacher-training curriculum.','qualification_note','Teaching in a kindergarten requires the applicable 幼稚園教諭免許状; degree completion alone is not the licence.','market_scope','No exact recurring comparable 029-02 market series is scored in the foundation phase.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:primary-school-teacher','2026-08-10',0,0,0,0,10,0,0,0,1,11,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','2022 MHLW 031-01 directly classifies 小学校教員.','entry_level_basis','An approved child-education programme is retained as a direct academic pathway only where it supports the applicable teacher-training route.','qualification_note','A school teacher must hold the licence corresponding to the school type; public-school employment also normally requires the relevant hiring selection.','market_scope','No exact recurring comparable 031-01 market series is scored.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:secondary-school-teacher','2026-08-10',0,0,0,0,10,0,0,0,1,11,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','The canonical Secondary School Teacher spans 031-02 中学校教員, 031-04 高等学校教員 and 031-05 中等教育学校教員 rather than one exact small-classification code.','entry_level_basis','The currently reviewed Japanese programme link is retained only as related because a Japanese-language teaching programme is not automatically a Japanese middle/high-school teacher-licensing programme.','qualification_note','Middle and high school teaching requires the applicable school-type and subject teacher licence; programme title alone does not establish licensure.','market_scope','The three school-type classifications are not merged into a fabricated exact market series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:special-education-teacher','2026-08-10',0,0,0,0,8,0,0,0,1,9,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','2022 MHLW 031-06 directly classifies 特別支援学校教員.','entry_level_basis','The reviewed special-needs-education programme is retained as a direct academic pathway subject to the applicable Japanese teacher-licensing curriculum.','qualification_note','MEXT guidance requires a foundational kindergarten, elementary, middle or high-school teacher licence plus required special-support education credits and an application for the 特別支援学校教諭免許状.','market_scope','No exact recurring comparable 031-06 market series is scored.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:social-worker','2026-08-10',0,0,0,0,10,0,0,0,1,11,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','社会福祉士 work appears across 049-02 welfare consultation, 049-03 elder-welfare guidance, 049-04 disability-welfare guidance, 049-05 child-welfare guidance and 049-99 other professional welfare settings; no one setting is the complete canonical occupation.','entry_level_basis','The reviewed Japanese social-work programme is retained as a direct study pathway, while statutory subject and examination requirements still apply.','qualification_note','社会福祉士 is a protected national title requiring eligibility, the national examination and registration.','market_scope','Setting-specific welfare classifications are not merged into one unsupported exact social-worker market series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:youth-worker','2026-08-10',0,0,0,0,10,0,0,0,3,13,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','The broad Youth Worker career spans 030-02 児童館指導員 and 049-05 児童福祉施設指導専門員 youth-support scopes rather than one universal occupation code.','entry_level_basis','The reviewed social-work programme is retained only as related. Youth-support roles can be entered through social welfare, psychology, education or supervised child-welfare experience depending on the setting.','qualification_note','There is no single universal Youth Worker licence. Specific 児童指導員 positions require an appointment qualification and particular facilities can impose additional staffing standards.','market_scope','Child-center and child-welfare-facility classifications are not merged into a fabricated exact youth-worker market series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:community-worker','2026-08-10',0,0,0,0,15,0,0,0,5,20,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','2022 MHLW 049-99 explicitly includes 社会福祉協議会相談員 and 福祉活動専門員, which provide the closest community-welfare anchor for the canonical Community Worker role.','entry_level_basis','Social work and broader social/human studies can support entry; the four reviewed Japanese programme mappings remain related rather than occupational qualification.','qualification_note','No universal personal Community Worker licence applies. Some municipal or statutory welfare posts can require a 社会福祉主事 appointment qualification or other role-specific criteria.','market_scope','Community and statutory welfare roles vary by employer, so no broader welfare market data are scored as exact Community Worker evidence.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:counsellor','2026-08-10',0,0,0,0,12,0,0,0,4,16,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','2022 MHLW 019-03 directly covers counsellors outside medical and welfare facilities, including school, career, workplace and private-practice counselling; medical and welfare counselling is classified separately under 027-99 and 049-99.','entry_level_basis','Psychology and human-sciences study are relevant but the two reviewed Japanese programmes are retained only as related pathways.','qualification_note','Counsellor is not one universally licensed occupation. Specific protected titles such as 公認心理師 and キャリアコンサルタント require their own registration, and many school or clinical counselling posts expect recognised credentials.','market_scope','Medical, welfare and non-medical counselling classifications are not merged into a fabricated exact counsellor market series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10')
on conflict (profile_key,as_of_date) do update set shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('JP:early-childhood-teacher','029-02','幼稚園教員',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:primary-school-teacher','031-01','小学校教員',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:secondary-school-teacher','031-02','中学校教員',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:secondary-school-teacher','031-04','高等学校教員',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:secondary-school-teacher','031-05','中等教育学校教員',null,null,false,3,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:special-education-teacher','031-06','特別支援学校教員',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:social-worker','049-02','福祉相談・指導専門員 — 社会福祉士 scope',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:social-worker','049-03','老人福祉施設指導専門員 — 社会福祉士 scope',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:social-worker','049-04','障害者福祉施設指導専門員 — 社会福祉士 scope',null,null,false,3,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:social-worker','049-05','児童福祉施設指導専門員 — 社会福祉士 scope',null,null,false,4,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:social-worker','049-99','その他の福祉・介護の専門的職業 — 社会福祉士 scope',null,null,false,5,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:youth-worker','030-02','児童館指導員 — youth-support scope',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:youth-worker','049-05','児童福祉施設指導専門員 — youth-support scope',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:community-worker','049-99','その他の福祉・介護の専門的職業 — community-welfare scope',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:counsellor','019-03','カウンセラー（医療・福祉施設を除く）',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:counsellor','027-99','医療施設の心理相談 scope',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:counsellor','049-99','福祉施設の心理相談 scope',null,null,false,3,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'job_search','Hello Work job search','https://www.hellowork.mhlw.go.jp/kensaku/GECA110010.do','government',10,'2026-08-10' from public.country_occupation_profiles p where p.country_code='JP' and p.canonical_career_id in ('early-childhood-teacher','primary-school-teacher','secondary-school-teacher','special-education-teacher','social-worker','youth-worker','community-worker','counsellor')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'source','2022 MHLW occupation classification','https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','government',20,'2026-08-10' from public.country_occupation_profiles p where p.country_code='JP' and p.canonical_career_id in ('early-childhood-teacher','primary-school-teacher','secondary-school-teacher','special-education-teacher','social-worker','youth-worker','community-worker','counsellor')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at) values
('JP:early-childhood-teacher','source','MEXT teacher-licence programmes','https://www.mext.go.jp/a_menu/shotou/kyoin/daigaku/1286948.htm','government',30,'2026-08-10'),
('JP:primary-school-teacher','source','MEXT teacher-licence programmes','https://www.mext.go.jp/a_menu/shotou/kyoin/daigaku/1286948.htm','government',30,'2026-08-10'),
('JP:secondary-school-teacher','source','MEXT teacher-licence programmes','https://www.mext.go.jp/a_menu/shotou/kyoin/daigaku/1286948.htm','government',30,'2026-08-10'),
('JP:special-education-teacher','source','MEXT special-support teacher licence Q&A','https://www.mext.go.jp/a_menu/shotou/kyoin/main13_a2.htm','government',30,'2026-08-10'),
('JP:social-worker','source','MHLW social worker qualification','https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/hukushi_kaigo/seikatsuhogo/shakai-kaigo-fukushi1/index.html','government',30,'2026-08-10'),
('JP:youth-worker','source','MHLW job tag — 児童指導員','https://shigoto.mhlw.go.jp/User/Occupation/Detail/243','government',30,'2026-08-10'),
('JP:counsellor','source','MHLW public psychologist qualification','https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000116049.html','government',30,'2026-08-10')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'JP:'||o.canonical_career_id,c.source_program_key,case when o.relation_type='direct' then 'direct' else 'related' end,coalesce(o.source_checked_at,'2026-08-10'::date)
from public.program_occupation_jp_staging o
join public.program_catalog_jp_staging c on c.id=o.program_catalog_id
where o.review_status='approved'
  and o.canonical_career_id in ('early-childhood-teacher','primary-school-teacher','secondary-school-teacher','special-education-teacher','social-worker','youth-worker','community-worker','counsellor')
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;;
