insert into public.country_occupation_profiles (
  profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,
  official_unit_group_code,currency,registration_required,registration_authority,registration_url,
  publication_status,source_checked_at,updated_at
) values
  ('IE:truck-driver','IE','truck-driver','Large goods vehicle drivers — professional HGV driver scope','SOC','SOC 2010','8211','EUR',true,'Road Safety Authority','https://www.rsa.ie/services/professional-drivers/cpc','profile_ready','2026-08-11',now()),
  ('IE:logistics-coordinator','IE','logistics-coordinator','Transport and distribution clerks and assistants — logistics coordinator scope','SOC','SOC 2010','4134','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:aircraft-maintenance-technician','IE','aircraft-maintenance-technician','Aircraft maintenance and related trades — aircraft maintenance technician scope','SOC','SOC 2010','5235','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:commercial-pilot','IE','commercial-pilot','Aircraft pilots and flight engineers — commercial pilot scope','SOC','SOC 2010','3512','EUR',true,'Irish Aviation Authority','https://www.iaa.ie/personnel-licensing/pilot-licences-%28eu-regulations%29/commercial-pilot-license','profile_ready','2026-08-11',now()),
  ('IE:marine-engineer','IE','marine-engineer','Ship and hovercraft officers — marine engineering officer scope','SOC','SOC 2010','3513','EUR',true,'Department of Transport — Mercantile Marine Office','https://www.gov.ie/en/department-of-transport/organisation-information/seafarers/','profile_ready','2026-08-11',now()),
  ('IE:deck-officer','IE','deck-officer','Ship and hovercraft officers — deck/navigation officer scope','SOC','SOC 2010','3513','EUR',true,'Department of Transport — Mercantile Marine Office','https://www.gov.ie/en/department-of-transport/organisation-information/seafarers/','profile_ready','2026-08-11',now()),
  ('IE:warehouse-manager','IE','warehouse-manager','Managers and directors in storage and warehousing — warehouse manager scope','SOC','SOC 2010','1162','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:automotive-service-technician','IE','automotive-service-technician','Vehicle technicians, mechanics and electricians — automotive service technician scope','SOC','SOC 2010','5231','EUR',false,null,null,'profile_ready','2026-08-11',now())
on conflict (profile_key) do update set
  official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,
  official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,
  registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,
  source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (
  profile_key,as_of_date,employment_total,median_hourly_earnings,annualised_median_salary,
  shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,
  entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,
  opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at
) values
  ('IE:truck-driver','2026-08-11',null,null,null,20,0,0,0,12,0,0,6,0,38,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 8211 Large goods vehicle drivers, restricted to professional HGV driving rather than van/taxi/bus driving.','shortage_note','SOLAS National Skills Bulletin 2025 directly identifies HGV drivers as a current Transport and Logistics shortage; 20/20.','visa_basis','SOC 8211 is on the current Ineligible List except HGV drivers holding category CE or C1E, or an equivalent category recognised through an RSA mutual-recognition agreement. The qualifying exception is treated as conditional GEP access; 6/10.','entry_basis','Ireland has a structured RSA truck-licence and Driver CPC route; 12/15.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_burden_basis','Professional truck driving requires the applicable full licence and a valid Driver CPC card; regulated entry burden receives 0/5.'),'2026-08-11'),
  ('IE:logistics-coordinator','2026-08-11',null,null,null,0,0,0,0,10,0,0,6,5,21,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 4134 Transport and distribution clerks and assistants, logistics-coordinator scope.','shortage_note','SOLAS 2025 says shortage evidence for stock-control and transport/distribution administrative occupations is inconclusive because of small employment numbers; 0/20.','visa_basis','SOC 4134 is neither on the current Critical Skills List nor the current Ineligible List, so ordinary General Employment Permit treatment may apply subject to the Labour Market Needs Test and other requirements; 6/10.','entry_basis','FET, logistics/supply-chain training and workplace progression provide accessible routes; 10/15.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_burden_basis','No universal statutory personal registration requirement; 5/5.'),'2026-08-11'),
  ('IE:aircraft-maintenance-technician','2026-08-11',null,null,null,0,0,0,0,12,0,0,6,5,23,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 5235 Aircraft maintenance and related trades, aircraft-maintenance technician scope.','shortage_note','No exact aircraft-maintenance shortage is published in the reviewed SOLAS 2025 Transport and Logistics shortage summary; 0/20.','visa_basis','SOC 5235 is neither on the current Critical Skills List nor the current Ineligible List, so ordinary General Employment Permit treatment may apply subject to current requirements; 6/10.','entry_basis','Aircraft Mechanics is a current Irish craft apprenticeship, giving a direct structured work-based route; 12/15.','licensing_boundary','IAA Part-66 Aircraft Maintenance Licences are required for applicable certifying privileges, but the broader technician occupation also includes work performed under appropriately authorised certifying staff, so universal personal registration is not asserted.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_burden_basis','No universal personal licence across every technician function; 5/5.'),'2026-08-11'),
  ('IE:commercial-pilot','2026-08-11',null,null,null,0,0,0,0,4,0,0,6,0,10,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 3512 Aircraft pilots and flight engineers, restricted to commercial pilot employment.','shortage_note','SOLAS 2025 Transport and Logistics does not identify commercial pilots as a current shortage in the reviewed summary; 0/20.','visa_basis','SOC 3512 is neither on the current Critical Skills List nor the current Ineligible List, so ordinary General Employment Permit treatment may apply subject to current requirements; 6/10.','entry_basis','Commercial flying requires approved flight training and substantial licence-specific training; 4/15.','licensing_boundary','The IAA states that commercial flying requires a commercial-level licence, normally a CPL or ATPL with the applicable Class 1 medical standard.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_burden_basis','Mandatory flight crew licensing and medical fitness create a high regulated entry burden; 0/5.'),'2026-08-11'),
  ('IE:marine-engineer','2026-08-11',null,null,null,0,0,0,0,8,0,0,6,0,14,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 3513 Ship and hovercraft officers, restricted to marine engineering officer duties and kept separate from shore-based Mechanical Engineer 2122.','shortage_note','SOLAS 2025 Transport and Logistics does not publish an exact Marine Engineer shortage in the reviewed summary; 0/20.','visa_basis','SOC 3513 is neither on the current Critical Skills List nor the current Ineligible List, so ordinary General Employment Permit treatment may apply subject to current requirements; 6/10.','entry_basis','Maritime engineering education, approved sea service and certification form a structured professional route; 8/15.','licensing_boundary','The Department of Transport states that seafaring is strictly regulated and issues Certificates of Competency for service on merchant ships and fishing vessels.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_burden_basis','Applicable seagoing engineering officer duties require the appropriate Certificate of Competency; 0/5.'),'2026-08-11'),
  ('IE:deck-officer','2026-08-11',null,null,null,0,0,0,0,8,0,0,6,0,14,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 3513 Ship and hovercraft officers, restricted to deck/navigation officer duties.','shortage_note','SOLAS 2025 Transport and Logistics does not publish an exact Deck Officer shortage in the reviewed summary; 0/20.','visa_basis','SOC 3513 is neither on the current Critical Skills List nor the current Ineligible List, so ordinary General Employment Permit treatment may apply subject to current requirements; 6/10.','entry_basis','Approved maritime education, sea service and competency examinations form the professional route; 8/15.','licensing_boundary','The Department of Transport states that seafaring is strictly regulated and Certificates of Competency are issued for service on merchant ships and fishing vessels.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_burden_basis','Applicable deck/navigation officer duties require the appropriate Certificate of Competency; 0/5.'),'2026-08-11'),
  ('IE:warehouse-manager','2026-08-11',null,null,null,0,0,0,0,8,0,0,6,5,19,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 1162 Managers and directors in storage and warehousing, genuine warehouse-management scope rather than elementary storage 9260 or fork-lift driving 8222.','shortage_note','SOLAS 2025 Transport and Logistics reports replacement demand and churn but does not publish an exact Warehouse Manager shortage; 0/20.','visa_basis','SOC 1162 is neither on the current Critical Skills List nor the current Ineligible List, so ordinary General Employment Permit treatment may apply subject to the Labour Market Needs Test and other requirements; 6/10.','entry_basis','Warehouse operations, logistics/supply-chain study and progression from supervisory roles are common routes; 8/15.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_burden_basis','No universal statutory personal registration requirement; 5/5.'),'2026-08-11'),
  ('IE:automotive-service-technician','2026-08-11',null,null,null,0,0,0,0,12,0,0,6,5,23,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 5231 Vehicle technicians, mechanics and electricians, restricted to car/motor mechanic and vehicle-service technician work.','shortage_note','The 2026 employment-permit review renewed quota access for Car/Motor Mechanic, Auto Electrician and Vehicle Technician, but permit policy is not converted into an exact SOLAS shortage signal; 0/20.','visa_basis','The 2026 occupations review renewed a General Employment Permit quota for Car/Motor Mechanic, Auto Electrician and Vehicle Technician, subject to a fresh Labour Market Needs Test and current quota/permit conditions; 6/10.','entry_basis','Motor Mechanics is a current Irish craft apprenticeship and provides a direct structured work-based route; 12/15.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_burden_basis','No universal statutory personal occupational licence is asserted for the broad automotive service technician scope; 5/5.'),'2026-08-11')
on conflict (profile_key,as_of_date) do update set
  employment_total=excluded.employment_total,median_hourly_earnings=excluded.median_hourly_earnings,annualised_median_salary=excluded.annualised_median_salary,
  shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,
  entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,
  opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

delete from public.country_occupation_specialisations where profile_key in ('IE:truck-driver','IE:logistics-coordinator','IE:aircraft-maintenance-technician','IE:commercial-pilot','IE:marine-engineer','IE:deck-officer','IE:warehouse-manager','IE:automotive-service-technician');
insert into public.country_occupation_specialisations (profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
  ('IE:truck-driver','8211','Large goods vehicle drivers — HGV CE/C1E permit-exception scope',20,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/ineligible-categories-of-employment/','2026-08-11'),
  ('IE:logistics-coordinator','4134','Transport and distribution clerks and assistants — logistics coordinator scope',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','2026-08-11'),
  ('IE:aircraft-maintenance-technician','5235','Aircraft maintenance and related trades — technician scope',null,true,true,1,'https://www.iaa.ie/personnel-licensing/maintenance-engineer---amel-licensing','2026-08-11'),
  ('IE:commercial-pilot','3512','Aircraft pilots and flight engineers — commercial pilot scope',null,true,true,1,'https://www.iaa.ie/personnel-licensing/pilot-licences-%28eu-regulations%29/commercial-pilot-license','2026-08-11'),
  ('IE:marine-engineer','3513','Ship and hovercraft officers — marine engineering officer scope',null,true,true,1,'https://www.gov.ie/en/department-of-transport/organisation-information/seafarers/','2026-08-11'),
  ('IE:deck-officer','3513','Ship and hovercraft officers — deck/navigation officer scope',null,true,true,1,'https://www.gov.ie/en/department-of-transport/organisation-information/seafarers/','2026-08-11'),
  ('IE:warehouse-manager','1162','Managers and directors in storage and warehousing — warehouse manager scope',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','2026-08-11'),
  ('IE:automotive-service-technician','5231','Vehicle technicians, mechanics and electricians — automotive service scope',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/latest-updates/','2026-08-11');

delete from public.country_occupation_links where profile_key in ('IE:truck-driver','IE:logistics-coordinator','IE:aircraft-maintenance-technician','IE:commercial-pilot','IE:marine-engineer','IE:deck-officer','IE:warehouse-manager','IE:automotive-service-technician');
insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,region_code,sort_order,source_checked_at) values
  ('IE:truck-driver','source','SOLAS — Transport and Logistics labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/transport-and-logistics/','government',null,1,'2026-08-11'),
  ('IE:truck-driver','source','DETE — current Ineligible List and HGV exception','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/ineligible-categories-of-employment/','government',null,2,'2026-08-11'),
  ('IE:truck-driver','source','RSA — Driver CPC rules','https://www.rsa.ie/services/professional-drivers/cpc/regulations-for-driver-cpc','government',null,3,'2026-08-11'),
  ('IE:truck-driver','entry_program','RSA — professional truck Driver CPC route','https://www.rsa.ie/services/learner-drivers/get-qualified/cpc-driver---truck---c','government',null,4,'2026-08-11'),
  ('IE:logistics-coordinator','source','SOLAS — Transport and Logistics labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/transport-and-logistics/','government',null,1,'2026-08-11'),
  ('IE:logistics-coordinator','source','DETE — occupation-list classification and ordinary GEP rule','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','government',null,2,'2026-08-11'),
  ('IE:logistics-coordinator','entry_program','Generation Apprenticeship — Supply Chain Specialist','https://apprenticeship.ie/career-seekers/get-started/learn-more/logistics/supply-chain-specialist','government',null,3,'2026-08-11'),
  ('IE:aircraft-maintenance-technician','source','DETE — occupation-list classification and ordinary GEP rule','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','government',null,1,'2026-08-11'),
  ('IE:aircraft-maintenance-technician','source','IAA — Aircraft Maintenance Licence / Part-66','https://www.iaa.ie/personnel-licensing/maintenance-engineer---amel-licensing','government',null,2,'2026-08-11'),
  ('IE:aircraft-maintenance-technician','entry_program','Generation Apprenticeship — Aircraft Mechanics craft route','https://apprenticeship.ie/craft-apprenticeship-training-locations','government',null,3,'2026-08-11'),
  ('IE:commercial-pilot','source','DETE — occupation-list classification and ordinary GEP rule','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','government',null,1,'2026-08-11'),
  ('IE:commercial-pilot','source','IAA — Commercial Pilot Licence','https://www.iaa.ie/personnel-licensing/pilot-licences-%28eu-regulations%29/commercial-pilot-license','government',null,2,'2026-08-11'),
  ('IE:commercial-pilot','entry_program','IAA — How to become a pilot','https://www.iaa.ie/personnel-licensing/pilot-licences-%28eu-regulations%29/how-to-become-a-pilot','government',null,3,'2026-08-11'),
  ('IE:marine-engineer','source','DETE — occupation-list classification and ordinary GEP rule','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','government',null,1,'2026-08-11'),
  ('IE:marine-engineer','source','Department of Transport — Seafarer certification and Certificates of Competency','https://www.gov.ie/en/department-of-transport/organisation-information/seafarers/','government',null,2,'2026-08-11'),
  ('IE:marine-engineer','entry_program','Department of Transport — Maritime education, training and certification','https://www.gov.ie/en/department-of-transport/organisation-information/seafarers/','government',null,3,'2026-08-11'),
  ('IE:deck-officer','source','DETE — occupation-list classification and ordinary GEP rule','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','government',null,1,'2026-08-11'),
  ('IE:deck-officer','source','Department of Transport — Seafarer certification and Certificates of Competency','https://www.gov.ie/en/department-of-transport/organisation-information/seafarers/','government',null,2,'2026-08-11'),
  ('IE:deck-officer','entry_program','Department of Transport — Maritime education, training and certification','https://www.gov.ie/en/department-of-transport/organisation-information/seafarers/','government',null,3,'2026-08-11'),
  ('IE:warehouse-manager','source','SOLAS — Transport and Logistics labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/transport-and-logistics/','government',null,1,'2026-08-11'),
  ('IE:warehouse-manager','source','DETE — occupation-list classification and ordinary GEP rule','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','government',null,2,'2026-08-11'),
  ('IE:warehouse-manager','entry_program','Generation Apprenticeship — Supply Chain Manager Level 9','https://apprenticeship.ie/career-seekers/get-started/learn-more/logistics/supply-chain-manager-l9','government',null,3,'2026-08-11'),
  ('IE:automotive-service-technician','source','DETE — 2026 renewed vehicle-technician GEP quota','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/latest-updates/','government',null,1,'2026-08-11'),
  ('IE:automotive-service-technician','source','DETE — 2025 occupations-list review','https://enterprise.gov.ie/en/publications/employment-permits-occupations-lists-report-of-the-review-2025.html','government',null,2,'2026-08-11'),
  ('IE:automotive-service-technician','entry_program','Generation Apprenticeship — Motor Mechanics craft route','https://apprenticeship.ie/craft-apprenticeship-training-locations','government',null,3,'2026-08-11');

delete from public.country_occupation_program_links where profile_key in ('IE:truck-driver','IE:logistics-coordinator','IE:aircraft-maintenance-technician','IE:commercial-pilot','IE:marine-engineer','IE:deck-officer','IE:warehouse-manager','IE:automotive-service-technician');;
