-- Australia Hotel Manager profile.
-- Current OSCA 161431 Hotel or Motel Manager is exact.
-- Broader ANZSCO 1413 vacancy/projection data remain contextual.

update public.courses_au set official_course_url='https://study.uq.edu.au/study-options/programs/bachelor-tourism-hospitality-and-event-management-2473?year=2026',official_url_status='verified',official_url_checked_at=now(),official_url_source='UQ current 2026 Bachelor of Tourism, Hospitality and Event Management page, CRICOS 103168H, verified 2026-08-09' where institution_id='the-university-of-queensland' and course_code='103168H';
update public.courses_au set official_course_url='https://www.tafensw.edu.au/international/courses/Diploma-of-Hospitality-Management--SIT50422',official_url_status='verified',official_url_checked_at=now(),official_url_source='TAFE NSW International Diploma of Hospitality Management page, CRICOS 112061M, verified 2026-08-09' where institution_id='tafe-nsw' and course_code='112061M';

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('AU:hotel-manager','AU','hotel-manager','Hotel or Motel Manager','OSCA','2024 v1.0','1614','AUD',false,'No universal registration; VETASSESS assesses ANZSCO 141311 Hotel or Motel Manager as Group C','https://www.vetassess.com.au/check-my-occupation/professional-occupations/hotel-or-motel-manager','profile_ready','2026-08-09',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,employment_total,median_weekly_earnings,median_hourly_earnings,annualised_median_salary,all_occupations_median_weekly,part_time_share_pct,female_share_pct,median_age,average_full_time_hours,vacancies_three_month_avg,vacancy_period,vacancy_yoy_pct,employment_growth_5y_pct,employment_growth_10y_pct,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at) values
('AU:hotel-manager','2026-05-01',null,null,null,null,1852,null,null,null,null,572,'2026-05-01',-2.39,0.94,7.40,0,0,5,0,13,0,5,10,5,38,'career-opportunity-v1','provisional',jsonb_build_object(
'classification_scope','Current OSCA 161431 Hotel or Motel Manager is an exact canonical occupation.',
'labour_scope','Primary employment, demographics and earnings remain null because the reviewed ingest does not contain a clean exact six-digit profile for current OSCA 161431.',
'vacancy_scope','Broader ANZSCO 1413 vacancies were 572 in May 2026 versus 586 in May 2025, about -2.39% year on year; vacancy intensity and trend receive zero credit.',
'projection_scope','Broader ANZSCO 1413 projections are +0.94% to 2030 and +7.40% to 2035; partial growth credit only.',
'shortage_note','JSA 2025 OSL records current OSCA 161431 Hotel or Motel Manager as No Shortage nationally.',
'visa_basis','The current skilled occupation instrument includes ANZSCO 141311 Hotel or Motel Manager with VETASSESS. VETASSESS classifies it as Group C.',
'entry_level_basis','UQ 103168H offers a Hotel and Hospitality Management major; TAFE NSW Diploma of Hospitality Management 112061M is a direct vocational management route.',
'entry_burden_basis','Management roles generally require practical responsibility and relevant employment; venue-specific liquor or gaming licensing may also apply.',
'score_note','Exact current migration evidence receives credit, while shortage, broader vacancy signals and unavailable exact earnings remain unscored.'
),'2026-08-09')
on conflict (profile_key,as_of_date) do update set employment_total=excluded.employment_total,median_weekly_earnings=excluded.median_weekly_earnings,median_hourly_earnings=excluded.median_hourly_earnings,annualised_median_salary=excluded.annualised_median_salary,all_occupations_median_weekly=excluded.all_occupations_median_weekly,part_time_share_pct=excluded.part_time_share_pct,female_share_pct=excluded.female_share_pct,median_age=excluded.median_age,average_full_time_hours=excluded.average_full_time_hours,vacancies_three_month_avg=excluded.vacancies_three_month_avg,vacancy_period=excluded.vacancy_period,vacancy_yoy_pct=excluded.vacancy_yoy_pct,employment_growth_5y_pct=excluded.employment_growth_5y_pct,employment_growth_10y_pct=excluded.employment_growth_10y_pct,shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,legacy_code_system,legacy_code_version,legacy_code,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('AU:hotel-manager','161431','Hotel or Motel Manager','ANZSCO','2022','141311',null,true,true,1,'https://www.abs.gov.au/statistics/classifications/osca-occupation-standard-classification-australia/2024-version-1-0/browse-classification/1/16/161/1614/161431','2026-08-09')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,legacy_code_system=excluded.legacy_code_system,legacy_code_version=excluded.legacy_code_version,legacy_code=excluded.legacy_code,shortage_rating=excluded.shortage_rating,visa_eligible=excluded.visa_eligible,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_region_metrics (profile_key,region_code,as_of_date,shortage_rating,vacancy_count,source_url) values
('AU:hotel-manager','ACT','2026-05-01',null,7.66667,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:hotel-manager','NSW','2026-05-01',null,166.33333,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:hotel-manager','NT','2026-05-01',null,12.33333,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:hotel-manager','QLD','2026-05-01',null,167,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:hotel-manager','SA','2026-05-01',null,48.33333,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:hotel-manager','TAS','2026-05-01',null,11.33333,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:hotel-manager','VIC','2026-05-01',null,98.66667,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:hotel-manager','WA','2026-05-01',null,60.33333,'https://www.jobsandskills.gov.au/data/internet-vacancy-index')
on conflict (profile_key,region_code,as_of_date) do update set shortage_rating=excluded.shortage_rating,vacancy_count=excluded.vacancy_count,source_url=excluded.source_url;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,region_code,sort_order,source_checked_at) values
('AU:hotel-manager','employer','Accor Careers','https://careers.accor.com/','hotel',null,1,'2026-08-09'),('AU:hotel-manager','employer','Marriott Careers','https://careers.marriott.com/','hotel',null,2,'2026-08-09'),('AU:hotel-manager','employer','Hilton Careers','https://jobs.hilton.com/','hotel',null,3,'2026-08-09'),('AU:hotel-manager','employer','IHG Careers','https://careers.ihg.com/','hotel',null,4,'2026-08-09'),('AU:hotel-manager','employer','Crown Careers','https://www.crownresorts.com.au/careers','resort',null,5,'2026-08-09'),
('AU:hotel-manager','entry_program','UQ — Bachelor of Tourism, Hospitality and Event Management','https://study.uq.edu.au/study-options/programs/bachelor-tourism-hospitality-and-event-management-2473?year=2026','university',null,1,'2026-08-09'),('AU:hotel-manager','entry_program','TAFE NSW — Diploma of Hospitality Management','https://www.tafensw.edu.au/international/courses/Diploma-of-Hospitality-Management--SIT50422','tafe',null,2,'2026-08-09'),
('AU:hotel-manager','source','ABS — OSCA 161431 Hotel or Motel Manager','https://www.abs.gov.au/statistics/classifications/osca-occupation-standard-classification-australia/2024-version-1-0/browse-classification/1/16/161/1614/161431','official_classification',null,1,'2026-08-09'),('AU:hotel-manager','source','JSA — 2025 Occupation Shortage List','https://www.jobsandskills.gov.au/data/occupation-shortage-analysis/occupation-shortage-list','official_shortage',null,2,'2026-08-09'),('AU:hotel-manager','source','VETASSESS — Hotel or Motel Manager','https://www.vetassess.com.au/check-my-occupation/professional-occupations/hotel-or-motel-manager','official_skills_assessment',null,3,'2026-08-09')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,region_code=excluded.region_code,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'AU:hotel-manager','au-program:'||id::text,'direct','2026-08-09' from public.courses_au where (institution_id='the-university-of-queensland' and course_code='103168H') or (institution_id='tafe-nsw' and course_code='112061M')
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;;
