create table if not exists public.program_catalog_ae_staging (
  id bigint generated by default as identity primary key,
  source_name text not null,
  source_program_key text not null,
  institution_name text not null,
  institution_id uuid references catalog.institutions(id) on delete restrict,
  title text not null,
  programme_level text,
  credential_type text,
  education_level text,
  field_name text,
  emirate text,
  city text,
  duration_years numeric,
  tuition_fee_aed integer,
  program_code text,
  official_program_url text,
  caa_detail_url text,
  source_url text not null,
  source_as_of date,
  accreditation_status text not null default 'unknown',
  collection_status text not null default 'registry_listed',
  verification_tier text not null default 'C',
  collected_at timestamptz not null default now(),
  unique(source_name, source_program_key),
  check (duration_years is null or duration_years > 0),
  check (tuition_fee_aed is null or tuition_fee_aed >= 0),
  check (accreditation_status in ('active','inactive','administrative_reasons','unknown')),
  check (verification_tier in ('A','B','C'))
);

create index if not exists program_catalog_ae_staging_institution_idx on public.program_catalog_ae_staging(institution_id);
create index if not exists program_catalog_ae_staging_title_idx on public.program_catalog_ae_staging(lower(title));
create index if not exists program_catalog_ae_staging_tier_idx on public.program_catalog_ae_staging(verification_tier, accreditation_status);

create table if not exists public.program_occupation_ae_staging (
  program_catalog_id bigint not null references public.program_catalog_ae_staging(id) on delete cascade,
  canonical_career_id text not null,
  rule_version text not null,
  match_basis text not null default 'title',
  match_pattern text not null,
  review_status text not null default 'candidate',
  relation_type text,
  source_checked_at date,
  reviewer_note text,
  matched_at timestamptz not null default now(),
  reviewed_at timestamptz,
  primary key(program_catalog_id, canonical_career_id),
  check (review_status in ('candidate','approved','rejected')),
  check (relation_type is null or relation_type in ('direct','common_pathway','related'))
);

create index if not exists program_occupation_ae_staging_career_idx on public.program_occupation_ae_staging(canonical_career_id, review_status);

create table if not exists public.program_international_ae_staging (
  id bigint generated by default as identity primary key,
  program_catalog_id bigint not null unique references public.program_catalog_ae_staging(id) on delete cascade,
  international_students_eligible boolean,
  international_admission_status text not null default 'unknown',
  visa_sponsorship_available boolean,
  intake_label text,
  intake_start_date date,
  application_deadline date,
  admission_source_url text,
  visa_source_url text,
  source_as_of date,
  verification_status text not null default 'unverified',
  rule_notes text,
  verified_at timestamptz,
  collected_at timestamptz not null default now(),
  check (international_admission_status in ('open','closed','not_yet_open','restricted','eligible_schedule_unknown','unknown')),
  check (verification_status in ('unverified','verified','stale','rejected'))
);

alter table public.program_catalog_ae_staging enable row level security;
alter table public.program_occupation_ae_staging enable row level security;
alter table public.program_international_ae_staging enable row level security;

revoke all on public.program_catalog_ae_staging from public,anon,authenticated;
revoke all on public.program_occupation_ae_staging from public,anon,authenticated;
revoke all on public.program_international_ae_staging from public,anon,authenticated;
grant select,insert,update,delete on public.program_catalog_ae_staging to service_role;
grant select,insert,update,delete on public.program_occupation_ae_staging to service_role;
grant select,insert,update,delete on public.program_international_ae_staging to service_role;
grant usage,select on all sequences in schema public to service_role;

comment on table public.program_catalog_ae_staging is 'Internal UAE programme collection staging. CAA accreditation state is separate from institution admission/international eligibility.';
comment on table public.program_international_ae_staging is 'Internal UAE programme-level international admission and visa evidence; never inferred solely from CAA accreditation.';;
