insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('NZ:early-childhood-teacher','NZ','early-childhood-teacher','Early Childhood (Pre-primary School) Teacher — registered','ANZSCO','1.3','241111','NZD',true,'Teaching Council of Aotearoa New Zealand','https://teachingcouncil.nz/en/become-a-teacher/based-in-aotearoa-new-zealand/register-to-teach','profile_ready','2026-08-11',now()),
('NZ:primary-school-teacher','NZ','primary-school-teacher','Primary School Teacher','ANZSCO','1.3','241213','NZD',true,'Teaching Council of Aotearoa New Zealand','https://teachingcouncil.nz/en/become-a-teacher/based-in-aotearoa-new-zealand/register-to-teach','profile_ready','2026-08-11',now()),
('NZ:secondary-school-teacher','NZ','secondary-school-teacher','Secondary School Teacher','ANZSCO','1.3','241411','NZD',true,'Teaching Council of Aotearoa New Zealand','https://teachingcouncil.nz/en/become-a-teacher/based-in-aotearoa-new-zealand/register-to-teach','profile_ready','2026-08-11',now()),
('NZ:special-education-teacher','NZ','special-education-teacher','Special Education Teachers — roll-up','ANZSCO','1.3','2415','NZD',true,'Teaching Council of Aotearoa New Zealand','https://teachingcouncil.nz/en/become-a-teacher/based-in-aotearoa-new-zealand/register-to-teach','profile_ready','2026-08-11',now()),
('NZ:social-worker','NZ','social-worker','Social Worker','ANZSCO','1.3','272511','NZD',true,'Social Workers Registration Board','https://swrb.govt.nz/registration/','profile_ready','2026-08-11',now()),
('NZ:youth-worker','NZ','youth-worker','Youth Worker','ANZSCO','1.3','411716','NZD',false,null,null,'profile_ready','2026-08-11',now()),
('NZ:community-worker','NZ','community-worker','Community Worker','ANZSCO','1.3','411711','NZD',false,null,null,'profile_ready','2026-08-11',now()),
('NZ:counsellor','NZ','counsellor','Counsellors — non-addiction roll-up','ANZSCO','1.3','2721','NZD',false,null,null,'profile_ready','2026-08-11',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();;
