-- Australia Tourism Manager profile.
-- No exact current principal OSCA title exists; OSCA 161999 Hospitality, Tourism and Venue Managers nec is used as a related proxy because it includes Tour Operator.

update public.courses_au set official_course_url='https://www.tafensw.edu.au/international/courses/diploma-of-travel-and-tourism-management--SIT50122',official_url_status='verified',official_url_checked_at=now(),official_url_source='TAFE NSW International Diploma of Travel and Tourism Management page, CRICOS 112058F, verified 2026-08-09' where institution_id='tafe-nsw' and course_code='112058F';

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('AU:tourism-manager','AU','tourism-manager','Hospitality, Tourism and Venue Managers nec','OSCA','2024 v1.0','1619','AUD',false,'No universal registration; VETASSESS assesses related legacy ANZSCO 141999 Accommodation and Hospitality Managers nec as Group C','https://www.vetassess.com.au/check-my-occupation/professional-occupations/accommodation-and-hospitality-managers-nec','profile_ready','2026-08-09',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,employment_total,median_weekly_earnings,median_hourly_earnings,annualised_median_salary,all_occupations_median_weekly,part_time_share_pct,female_share_pct,median_age,average_full_time_hours,vacancies_three_month_avg,vacancy_period,vacancy_yoy_pct,employment_growth_5y_pct,employment_growth_10y_pct,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at) values
('AU:tourism-manager','2026-05-01',null,null,null,null,1852,null,null,null,null,99,'2026-05-01',-1.33,2.12,9.27,0,0,5,0,13,0,5,5,5,33,'career-opportunity-v1','provisional',jsonb_build_object(
'classification_scope','Current OSCA has no single principal six-digit occupation titled Tourism Manager. CampCareer uses OSCA 161999 Hospitality, Tourism and Venue Managers nec as a related proxy because the occupation explicitly includes Tour Operator.',
'mapping_relation','related_proxy',
'labour_scope','Primary employment, demographics and earnings remain null. Legacy ANZSCO 141999 context is 4,400 workers, 39% part-time, 57% female, median age 52 and 50 average full-time hours, but it is not treated as exact canonical labour data.',
'vacancy_scope','Broader ANZSCO 1419 vacancies were 99 in May 2026 versus 100.33333 in May 2025, about -1.33% year on year; vacancy intensity and trend receive zero credit.',
'projection_scope','Broader ANZSCO 1419 projections are +2.12% to 2030 and +9.27% to 2035; partial growth credit only.',
'shortage_note','JSA 2025 OSL records current OSCA 161999 Hospitality, Tourism and Venue Managers nec as No Shortage nationally.',
'visa_basis','The current skilled occupation instrument includes ANZSCO 141999 Accommodation and Hospitality Managers nec with VETASSESS, but the canonical Tourism Manager mapping is only a related proxy, so migration credit is partial.',
'entry_level_basis','UQ Bachelor of Tourism, Hospitality and Event Management 103168H offers a Tourism and Event Management major; TAFE NSW Diploma of Travel and Tourism Management 112058F is a direct vocational tourism-management route.',
'entry_burden_basis','No universal occupational licence applies, but management roles generally require practical responsibility and relevant sector experience.',
'score_note','The profile preserves the lack of an exact current title and reduces migration credit rather than presenting the 161999 proxy as exact.'
),'2026-08-09')
on conflict (profile_key,as_of_date) do update set employment_total=excluded.employment_total,median_weekly_earnings=excluded.median_weekly_earnings,median_hourly_earnings=excluded.median_hourly_earnings,annualised_median_salary=excluded.annualised_median_salary,all_occupations_median_weekly=excluded.all_occupations_median_weekly,part_time_share_pct=excluded.part_time_share_pct,female_share_pct=excluded.female_share_pct,median_age=excluded.median_age,average_full_time_hours=excluded.average_full_time_hours,vacancies_three_month_avg=excluded.vacancies_three_month_avg,vacancy_period=excluded.vacancy_period,vacancy_yoy_pct=excluded.vacancy_yoy_pct,employment_growth_5y_pct=excluded.employment_growth_5y_pct,employment_growth_10y_pct=excluded.employment_growth_10y_pct,shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,legacy_code_system,legacy_code_version,legacy_code,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('AU:tourism-manager','161999','Hospitality, Tourism and Venue Managers nec','ANZSCO','2022','141999',null,true,true,1,'https://www.abs.gov.au/statistics/classifications/osca-occupation-standard-classification-australia/2024-version-1-0/browse-classification/1/16/161/1619/161999','2026-08-09')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,legacy_code_system=excluded.legacy_code_system,legacy_code_version=excluded.legacy_code_version,legacy_code=excluded.legacy_code,shortage_rating=excluded.shortage_rating,visa_eligible=excluded.visa_eligible,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_region_metrics (profile_key,region_code,as_of_date,shortage_rating,vacancy_count,source_url) values
('AU:tourism-manager','ACT','2026-05-01',null,3,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:tourism-manager','NSW','2026-05-01',null,25,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:tourism-manager','NT','2026-05-01',null,1.66667,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:tourism-manager','QLD','2026-05-01',null,27.66667,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:tourism-manager','SA','2026-05-01',null,8,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:tourism-manager','TAS','2026-05-01',null,0,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:tourism-manager','VIC','2026-05-01',null,17,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:tourism-manager','WA','2026-05-01',null,16.66667,'https://www.jobsandskills.gov.au/data/internet-vacancy-index')
on conflict (profile_key,region_code,as_of_date) do update set shortage_rating=excluded.shortage_rating,vacancy_count=excluded.vacancy_count,source_url=excluded.source_url;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,region_code,sort_order,source_checked_at) values
('AU:tourism-manager','employer','Flight Centre Careers','https://www.fctgcareers.com/','travel',null,1,'2026-08-09'),('AU:tourism-manager','employer','Intrepid Travel Careers','https://www.intrepidtravel.com/au/careers','tour_operator',null,2,'2026-08-09'),('AU:tourism-manager','employer','Journey Beyond Careers','https://www.journeybeyond.com/careers/','tourism',null,3,'2026-08-09'),('AU:tourism-manager','employer','Tourism Australia Careers','https://www.australia.com/en/about/careers.html','destination_marketing',null,4,'2026-08-09'),('AU:tourism-manager','employer','Accor Careers','https://careers.accor.com/','hotel_tourism',null,5,'2026-08-09'),
('AU:tourism-manager','entry_program','UQ — Bachelor of Tourism, Hospitality and Event Management','https://study.uq.edu.au/study-options/programs/bachelor-tourism-hospitality-and-event-management-2473?year=2026','university',null,1,'2026-08-09'),('AU:tourism-manager','entry_program','TAFE NSW — Diploma of Travel and Tourism Management','https://www.tafensw.edu.au/international/courses/diploma-of-travel-and-tourism-management--SIT50122','tafe',null,2,'2026-08-09'),
('AU:tourism-manager','source','ABS — OSCA 161999 Hospitality, Tourism and Venue Managers nec','https://www.abs.gov.au/statistics/classifications/osca-occupation-standard-classification-australia/2024-version-1-0/browse-classification/1/16/161/1619/161999','official_classification',null,1,'2026-08-09'),('AU:tourism-manager','source','JSA — 2025 Occupation Shortage List','https://www.jobsandskills.gov.au/data/occupation-shortage-analysis/occupation-shortage-list','official_shortage',null,2,'2026-08-09'),('AU:tourism-manager','source','VETASSESS — Accommodation and Hospitality Managers nec','https://www.vetassess.com.au/check-my-occupation/professional-occupations/accommodation-and-hospitality-managers-nec','official_skills_assessment',null,3,'2026-08-09')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,region_code=excluded.region_code,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'AU:tourism-manager','au-program:'||id::text,case when course_code='112058F' then 'direct' else 'related' end,'2026-08-09' from public.courses_au where (institution_id='tafe-nsw' and course_code='112058F') or (institution_id='the-university-of-queensland' and course_code='103168H')
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;;
