insert into public.country_occupation_profiles (
  profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,
  official_unit_group_code,currency,registration_required,registration_authority,registration_url,
  publication_status,source_checked_at,updated_at
) values
  ('IE:graphic-designer','IE','graphic-designer','Graphic designers','SOC','SOC 2010','3421','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:ux-designer','IE','ux-designer','Web design and development professionals — UX/interface design scope','SOC','SOC 2010','2137','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:multimedia-designer','IE','multimedia-designer','Cross-SOC multimedia design scope — graphic/multimedia and web/digital design','SOC','SOC 2010',null,'EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:animator','IE','animator','Artists — animation artist scope','SOC','SOC 2010','3411','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:interior-designer','IE','interior-designer','Product, clothing and related designers — interior design scope','SOC','SOC 2010','3422','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:film-editor','IE','film-editor','Arts officers, producers and directors — film/video editor scope','SOC','SOC 2010','3416','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:architect','IE','architect','Architects and town planners — Architect','SOC','SOC 2010','2431','EUR',true,'Royal Institute of the Architects of Ireland — statutory Registration Body','https://www.riai.ie/join-the-riai/registering-as-an-architect/about-the-register','profile_ready','2026-08-11',now()),
  ('IE:web-designer','IE','web-designer','Web design and development professionals — web designer scope','SOC','SOC 2010','2137','EUR',false,null,null,'profile_ready','2026-08-11',now())
on conflict (profile_key) do update set
  official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,
  official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,
  registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,
  source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (
  profile_key,as_of_date,employment_total,median_hourly_earnings,annualised_median_salary,
  shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,
  entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,
  opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at
) values
  ('IE:graphic-designer','2026-08-11',null,null,null,0,0,0,0,8,0,0,6,5,19,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 3421 Graphic designers.','shortage_note','SOLAS 2025 Arts, Sports & Tourism reports below-average group growth and does not publish an exact Graphic Designer shortage; 0/20.','visa_basis','Generic Graphic Designer is not itself named on the current Critical Skills list. Specific 3421 animation design roles are CSEP-eligible, but that specialist treatment is not borrowed by generic graphic design. SOC 3421 was not found on the current Ineligible list, so ordinary GEP access may apply; 6/10.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_basis','Portfolio plus relevant design education or equivalent applied experience is a common entry pattern; 8/15.','entry_burden_basis','No universal statutory personal registration requirement; 5/5.'),'2026-08-11'),
  ('IE:ux-designer','2026-08-11',null,null,null,0,0,0,0,8,0,0,10,5,23,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 2137 Web design and development professionals, constrained to digital UX/interface design duties.','shortage_note','SOLAS 2025 ICT identifies software developers/engineers and IT analysts/engineers as shortages, not UX designers specifically; 0/20.','visa_basis','SOC 2137 Web design and development professionals is explicitly on the current Critical Skills Occupations List; 10/10.','scope_boundary','The score applies where the actual duties fit SOC 2137 digital/web UX design; broader user research or service-design jobs may classify differently.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_basis','Portfolio plus UX/product/design education or equivalent experience is a common route; 8/15.','entry_burden_basis','No universal statutory personal registration requirement; 5/5.'),'2026-08-11'),
  ('IE:multimedia-designer','2026-08-11',null,null,null,0,0,0,0,8,0,0,8,5,21,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','Cross-SOC canonical profile spanning SOC 3421 visual/multimedia design and SOC 2137 web/digital design where duties fit. No single primary code is forced.','shortage_note','No exact Multimedia Designer shortage is published in the reviewed SOLAS 2025 Arts or ICT summaries; 0/20.','visa_basis','SOC 2137 duties can qualify for CSEP, while generic SOC 3421 design is generally GEP-accessible unless the job matches one of the listed animation CSEP specialisms. Conditional mixed-scope credit 8/10.','scope_boundary','A multimedia title alone is not sufficient to claim SOC 2137 or animation-specialist CSEP treatment; actual duties control classification.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_basis','Portfolio plus multimedia/digital design education or applied experience is a common route; 8/15.','entry_burden_basis','No universal statutory personal registration requirement; 5/5.'),'2026-08-11'),
  ('IE:animator','2026-08-11',null,null,null,0,0,0,0,8,0,0,8,5,21,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 3411 Artists as the primary animation-artist scope, with related SOC 3421 animation-design specialisms retained separately.','shortage_note','SOLAS 2025 Arts, Sports & Tourism does not publish an occupation-wide Animator shortage; 0/20.','visa_basis','The current Critical Skills list names specific 2D/3D animation roles under SOC 3411 and 3421, generally with at least one year of role experience. Generic Animator is broader than those named employments, so conditional CSEP credit 8/10 is used rather than universal 10/10.','scope_boundary','Art Director 2473 and Games Rigger 3417 are separate occupations and are not rolled into the generic Animator profile.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_basis','Animation portfolio/reel plus relevant training, degree or production experience is a common entry pattern; 8/15.','entry_burden_basis','No universal statutory personal registration requirement; 5/5.'),'2026-08-11'),
  ('IE:interior-designer','2026-08-11',null,null,null,0,0,0,0,8,0,0,6,5,19,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 3422 Product, clothing and related designers, constrained to interior-design work.','shortage_note','SOLAS 2025 Arts, Sports & Tourism does not publish an exact Interior Designer shortage; 0/20.','visa_basis','The canonical Interior Designer scope is neither explicitly Critical Skills nor identified on the current Ineligible list; ordinary GEP access may apply subject to permit conditions; 6/10.','scope_boundary','Interior Designer is not promoted to Architect SOC 2431 and does not borrow architect CSEP or statutory registration treatment.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_basis','Portfolio plus interior/spatial design education or equivalent experience is a common route; 8/15.','entry_burden_basis','No universal statutory personal registration requirement for the Interior Designer title; 5/5.'),'2026-08-11'),
  ('IE:film-editor','2026-08-11',null,null,null,0,0,0,0,8,0,0,6,5,19,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 3416 Arts officers, producers and directors, constrained to film/video post-production editor duties.','shortage_note','SOLAS 2025 Arts, Sports & Tourism does not publish an exact Film Editor shortage; 0/20.','visa_basis','SOC 3416 is not explicitly on the current Critical Skills list and was not identified on the current Ineligible list; ordinary GEP access may apply subject to conditions; 6/10.','scope_boundary','Camera, audio-visual equipment and broadcasting-operator roles in SOC 3417 are not substituted for the editor scope.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_basis','Editing reel/portfolio plus film, broadcasting or digital-media education and production experience is a common route; 8/15.','entry_burden_basis','No universal statutory personal registration requirement; 5/5.'),'2026-08-11'),
  ('IE:architect','2026-08-11',null,null,null,0,0,0,0,4,0,0,10,1,15,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 2431 Architects and town planners, exact Architect employment.','shortage_note','Architect is on the current Critical Skills list, but SOLAS 2025 Construction does not publish Architect in its explicit shortage list; shortage and permit evidence are kept separate, so 0/20.','visa_basis','Architect is explicitly listed under SOC 2431 on the current Critical Skills Occupations List; 10/10.','registration_basis','The Building Control Act 2007 protects the title Architect in Ireland; only persons on the statutory Register of Architects may use it.','entry_basis','RIAI describes the typical Irish route as a prescribed five-year architecture qualification plus at least two years of approved postgraduate professional training and a Professional Practice Examination; 4/15.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_burden_basis','Protected title and lengthy statutory registration pathway create high entry burden; 1/5.'),'2026-08-11'),
  ('IE:web-designer','2026-08-11',null,null,null,0,0,0,0,8,0,0,10,5,23,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 2137 Web design and development professionals, web-designer scope.','shortage_note','SOLAS 2025 ICT shows strong sector demand but names software developers/engineers and IT analysts/engineers as shortages, not web designers specifically; 0/20.','visa_basis','SOC 2137 Web design and development professionals is explicitly on the current Critical Skills Occupations List; 10/10.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_basis','Portfolio plus web/design training or related higher education and practical front-end/design experience is a common route; 8/15.','entry_burden_basis','No universal statutory personal registration requirement; 5/5.'),'2026-08-11')
on conflict (profile_key,as_of_date) do update set
  employment_total=excluded.employment_total,median_hourly_earnings=excluded.median_hourly_earnings,annualised_median_salary=excluded.annualised_median_salary,
  shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,
  entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,
  opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

delete from public.country_occupation_specialisations where profile_key in ('IE:graphic-designer','IE:ux-designer','IE:multimedia-designer','IE:animator','IE:interior-designer','IE:film-editor','IE:architect','IE:web-designer');
insert into public.country_occupation_specialisations (profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
  ('IE:graphic-designer','3421','Graphic designers — generic graphic design scope',null,true,true,1,'https://www.cso.ie/en/releasesandpublications/ep/p-cp11eoi/cp11eoi/bgn/','2026-08-11'),
  ('IE:ux-designer','2137','Web design and development professionals — UX/interface design scope',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','2026-08-11'),
  ('IE:multimedia-designer','3421','Graphic designers — visual/multimedia design scope',null,true,true,1,'https://www.cso.ie/en/releasesandpublications/ep/p-cp11eoi/cp11eoi/bgn/','2026-08-11'),
  ('IE:multimedia-designer','2137','Web design and development professionals — web/digital multimedia scope',null,true,true,2,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','2026-08-11'),
  ('IE:animator','3411','Animation Background and Design Artist in 2D or 3D animation — conditional CSEP specialism',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','2026-08-11'),
  ('IE:animator','3421','Animation layout / character / location / prop design — conditional CSEP specialisms',null,true,true,2,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','2026-08-11'),
  ('IE:interior-designer','3422','Product, clothing and related designers — interior design scope',null,true,true,1,'https://www.cso.ie/en/releasesandpublications/ep/p-cp11eoi/cp11eoi/bgn/','2026-08-11'),
  ('IE:film-editor','3416','Arts officers, producers and directors — film/video editor scope',null,true,true,1,'https://www.cso.ie/en/releasesandpublications/ep/p-cp11eoi/cp11eoi/bgn/','2026-08-11'),
  ('IE:architect','2431','Architect',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','2026-08-11'),
  ('IE:web-designer','2137','Web design and development professionals — web designer scope',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','2026-08-11');

delete from public.country_occupation_links where profile_key in ('IE:graphic-designer','IE:ux-designer','IE:multimedia-designer','IE:animator','IE:interior-designer','IE:film-editor','IE:architect','IE:web-designer');
insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,region_code,sort_order,source_checked_at) values
  ('IE:graphic-designer','source','CSO — SOC 2010 detailed occupation classification','https://www.cso.ie/en/releasesandpublications/ep/p-cp11eoi/cp11eoi/bgn/','government',null,1,'2026-08-11'),
  ('IE:graphic-designer','source','SOLAS — Arts, Sports and Tourism labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/arts-sports-and-tourism/','government',null,2,'2026-08-11'),
  ('IE:graphic-designer','source','DETE — General Employment Permit','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/permit-types/general-employment-permit/','government',null,3,'2026-08-11'),
  ('IE:ux-designer','source','CSO — SOC 2010 detailed occupation classification','https://www.cso.ie/en/releasesandpublications/ep/p-cp11eoi/cp11eoi/bgn/','government',null,1,'2026-08-11'),
  ('IE:ux-designer','source','SOLAS — ICT labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/ict/','government',null,2,'2026-08-11'),
  ('IE:ux-designer','source','DETE — Critical Skills Occupations List','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','government',null,3,'2026-08-11'),
  ('IE:multimedia-designer','source','CSO — SOC 2010 detailed occupation classification','https://www.cso.ie/en/releasesandpublications/ep/p-cp11eoi/cp11eoi/bgn/','government',null,1,'2026-08-11'),
  ('IE:multimedia-designer','source','SOLAS — Arts, Sports and Tourism labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/arts-sports-and-tourism/','government',null,2,'2026-08-11'),
  ('IE:multimedia-designer','source','DETE — Critical Skills Occupations List','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','government',null,3,'2026-08-11'),
  ('IE:animator','source','CSO — SOC 2010 detailed occupation classification','https://www.cso.ie/en/releasesandpublications/ep/p-cp11eoi/cp11eoi/bgn/','government',null,1,'2026-08-11'),
  ('IE:animator','source','SOLAS — Arts, Sports and Tourism labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/arts-sports-and-tourism/','government',null,2,'2026-08-11'),
  ('IE:animator','source','DETE — Critical Skills animation specialisms','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','government',null,3,'2026-08-11'),
  ('IE:interior-designer','source','CSO — SOC 2010 detailed occupation classification','https://www.cso.ie/en/releasesandpublications/ep/p-cp11eoi/cp11eoi/bgn/','government',null,1,'2026-08-11'),
  ('IE:interior-designer','source','SOLAS — Arts, Sports and Tourism labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/arts-sports-and-tourism/','government',null,2,'2026-08-11'),
  ('IE:interior-designer','source','DETE — General Employment Permit','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/permit-types/general-employment-permit/','government',null,3,'2026-08-11'),
  ('IE:film-editor','source','CSO — SOC 2010 detailed occupation classification','https://www.cso.ie/en/releasesandpublications/ep/p-cp11eoi/cp11eoi/bgn/','government',null,1,'2026-08-11'),
  ('IE:film-editor','source','SOLAS — Arts, Sports and Tourism labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/arts-sports-and-tourism/','government',null,2,'2026-08-11'),
  ('IE:film-editor','source','DETE — General Employment Permit','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/permit-types/general-employment-permit/','government',null,3,'2026-08-11'),
  ('IE:architect','source','CSO — SOC 2010 detailed occupation classification','https://www.cso.ie/en/releasesandpublications/ep/p-cp11eoi/cp11eoi/bgn/','government',null,1,'2026-08-11'),
  ('IE:architect','source','DETE — Critical Skills Occupations List','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','government',null,2,'2026-08-11'),
  ('IE:architect','source','Government of Ireland — protected construction professional titles','https://www.gov.ie/en/department-of-housing-local-government-and-heritage/publications/building-control/','government',null,3,'2026-08-11'),
  ('IE:architect','entry_program','RIAI — route to Registration as an Architect','https://www.riai.ie/careers-in-architecture/how-to-become-an-architect','professional_body',null,4,'2026-08-11'),
  ('IE:web-designer','source','CSO — SOC 2010 detailed occupation classification','https://www.cso.ie/en/releasesandpublications/ep/p-cp11eoi/cp11eoi/bgn/','government',null,1,'2026-08-11'),
  ('IE:web-designer','source','SOLAS — ICT labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/ict/','government',null,2,'2026-08-11'),
  ('IE:web-designer','source','DETE — Critical Skills Occupations List','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','government',null,3,'2026-08-11');

delete from public.country_occupation_program_links where profile_key in ('IE:graphic-designer','IE:ux-designer','IE:multimedia-designer','IE:animator','IE:interior-designer','IE:film-editor','IE:architect','IE:web-designer');;
