insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('NZ:early-childhood-teacher','NZ','early-childhood-teacher','Early Childhood (Pre-primary School) Teacher — registered','ANZSCO','1.3','241111','NZD',true,'Teaching Council of Aotearoa New Zealand','https://teachingcouncil.nz/index.htm/become-a-teacher/based-in-aotearoa-new-zealand/register-to-teach','profile_ready','2026-08-11',now()),
('NZ:primary-school-teacher','NZ','primary-school-teacher','Primary School Teacher','ANZSCO','1.3','241213','NZD',true,'Teaching Council of Aotearoa New Zealand','https://teachingcouncil.nz/index.htm/become-a-teacher/based-in-aotearoa-new-zealand/register-to-teach','profile_ready','2026-08-11',now()),
('NZ:secondary-school-teacher','NZ','secondary-school-teacher','Secondary School Teacher','ANZSCO','1.3','241411','NZD',true,'Teaching Council of Aotearoa New Zealand','https://teachingcouncil.nz/index.htm/become-a-teacher/based-in-aotearoa-new-zealand/register-to-teach','profile_ready','2026-08-11',now()),
('NZ:special-education-teacher','NZ','special-education-teacher','Special Education Teachers (roll-up)','ANZSCO','1.3','2415','NZD',true,'Teaching Council of Aotearoa New Zealand','https://teachingcouncil.nz/index.htm/become-a-teacher/based-in-aotearoa-new-zealand/register-to-teach','profile_ready','2026-08-11',now()),
('NZ:social-worker','NZ','social-worker','Social Worker','ANZSCO','1.3','272511','NZD',true,'Social Workers Registration Board','https://swrb.govt.nz/registration/','profile_ready','2026-08-11',now()),
('NZ:youth-worker','NZ','youth-worker','Youth Worker','ANZSCO','1.3','411716','NZD',false,null,null,'profile_ready','2026-08-11',now()),
('NZ:community-worker','NZ','community-worker','Community Worker','ANZSCO','1.3','411711','NZD',false,null,null,'profile_ready','2026-08-11',now()),
('NZ:counsellor','NZ','counsellor','Counsellors — NZAC Green List scope roll-up','ANZSCO','1.3','2721','NZD',false,null,null,'profile_ready','2026-08-11',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,employment_total,median_hourly_earnings,annualised_median_salary,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at) values
('NZ:early-childhood-teacher','2026-08-11',null,39.66,82500,15,0,0,0,8,8,0,8,1,40,'career-opportunity-nz-v1','provisional',jsonb_build_object('classification_scope','ANZSCO 241111 Early Childhood (Pre-primary School) Teacher — registered.','shortage_note','Current Green List Tier 2 status is direct policy-demand evidence; 15/20.','visa_basis','Green List Tier 2 supports Work to Residence after the qualifying period when the Teaching Council registration/certification and other current requirements are met; 8/10.','salary_method','Midpoint of Tahatū current most-common Early Childhood Teacher annual pay range NZD 72,000-93,000; 8/10.','entry_basis','Teaching Council-approved ECE initial teacher education commonly requires about 3-4 years for direct undergraduate entry, with graduate-entry routes also available; 8/15.','entry_burden_basis','Teaching Council registration and a current practising certificate are required to officially teach; 1/5.'),'2026-08-11'),
('NZ:primary-school-teacher','2026-08-11',null,39.66,82500,20,0,0,0,8,8,0,10,1,47,'career-opportunity-nz-v1','provisional',jsonb_build_object('classification_scope','ANZSCO 241213 Primary School Teacher. Māori-medium and intermediate teacher codes are not rolled into this canonical primary profile.','shortage_note','Primary School Teacher 241213 is on current Green List Tier 1; 20/20.','visa_basis','Tier 1 Straight to Residence when Teaching Council registration, a provisional or full practising certificate and other Green List requirements are met; 10/10.','salary_method','Midpoint of Tahatū current most-common Primary School Teacher annual pay range NZD 72,000-93,000; 8/10.','entry_basis','Approved initial teacher education is required; direct bachelor and graduate-entry teaching routes are available; 8/15.','entry_burden_basis','Teaching Council registration and a current practising certificate are mandatory for official teaching; 1/5.'),'2026-08-11'),
('NZ:secondary-school-teacher','2026-08-11',null,39.66,82500,20,0,0,0,8,8,0,10,1,47,'career-opportunity-nz-v1','provisional',jsonb_build_object('classification_scope','ANZSCO 241411 Secondary School Teacher.','shortage_note','Secondary School Teacher 241411 is on current Green List Tier 1; 20/20.','visa_basis','Tier 1 Straight to Residence when Teaching Council registration, a provisional or full practising certificate and other current requirements are met; 10/10.','salary_method','Midpoint of Tahatū current most-common Secondary School Teacher annual pay range NZD 72,000-93,000; 8/10.','entry_basis','Teaching Council-approved secondary initial teacher education is required, often following or incorporating subject-degree study; 8/15.','entry_burden_basis','Teaching Council registration and a current practising certificate are mandatory for official teaching; 1/5.'),'2026-08-11'),
('NZ:special-education-teacher','2026-08-11',null,39.66,82500,15,0,0,0,8,8,0,8,1,40,'career-opportunity-nz-v1','provisional',jsonb_build_object('classification_scope','Roll-up of ANZSCO 241511 Special Needs Teacher, 241512 Teacher of the Hearing Impaired, 241513 Teacher of the Sight Impaired and 241599 Special Education Teachers nec. Teacher aides and learning-support assistants are excluded.','shortage_note','The four special-education teacher occupations are on current Green List Tier 2; 15/20.','visa_basis','Tier 2 Work to Residence when the registered-teacher and other current Green List requirements are satisfied; 8/10.','salary_method','No exact Tahatū Special Education Teacher pay page was used. Salary transparently uses the NZD 72,000-93,000 most-common range published for registered primary/secondary teachers as a representative teacher-pay proxy; 8/10.','entry_basis','A Teaching Council-approved ITE route and teacher registration are the professional foundation, with special-education expertise layered onto registered teaching; 8/15.','entry_burden_basis','Teaching Council registration and a current practising certificate are mandatory for the Green List teacher scope; 1/5.'),'2026-08-11'),
('NZ:social-worker','2026-08-11',null,46.63,97000,20,0,0,0,8,8,0,10,1,47,'career-opportunity-nz-v1','provisional',jsonb_build_object('classification_scope','ANZSCO 272511 Social Worker.','shortage_note','Social Worker 272511 is on current Green List Tier 1; 20/20.','visa_basis','Tier 1 Straight to Residence when SWRB registration and the listed qualification/current immigration requirements are met; 10/10.','salary_method','Midpoint of Tahatū current most-common Social Worker annual pay range NZD 87,000-107,000; 8/10.','entry_basis','A SWRB-recognised social-work qualification or accepted overseas/Australian qualification pathway is required. The former section 13 experience-only pathway closed to new applications on 28 February 2026; 8/15.','entry_burden_basis','SWRB registration and a current annual Practising Certificate are legally required to practise as a social worker; 1/5.'),'2026-08-11'),
('NZ:youth-worker','2026-08-11',null,32.69,68000,0,0,0,0,15,4,0,5,5,29,'career-opportunity-nz-v1','provisional',jsonb_build_object('classification_scope','ANZSCO 411716 Youth Worker.','shortage_note','No current Green List or recurring occupation-specific shortage credit is assigned.','visa_basis','Standard skilled-work treatment when the specific role and applicant meet current immigration requirements; 5/10.','salary_method','Midpoint of Tahatū current most-common Youth Worker annual pay range NZD 63,000-73,000; 4/10.','entry_basis','Tahatū describes 0-3 years of training, with youth-work/community qualifications useful rather than one mandatory statutory degree; 15/15.','entry_burden_basis','Youth work is not a statutorily registered occupation; police vetting and employer safeguarding requirements may apply; 5/5.'),'2026-08-11'),
('NZ:community-worker','2026-08-11',null,26.50,55120,0,0,0,0,15,2,0,5,5,27,'career-opportunity-nz-v1','provisional',jsonb_build_object('classification_scope','ANZSCO 411711 Community Worker. This community-development/support scope is distinct from Personal Care Assistant 423313 used by the Health Care Worker profile.','shortage_note','No current Green List or recurring occupation-specific shortage credit is assigned.','visa_basis','Standard skilled-work treatment when a specific community-worker role meets current classification and immigration requirements; 5/10.','salary_method','Tahatū does not provide a clean exact Community Worker pay page in the reviewed layer; midpoint of Support Worker most-common hourly pay NZD 25-28, annualised at 2,080 hours, is used as the closest transparent community-support proxy; 2/10.','entry_basis','Community/support work can be entered through on-the-job experience and certificate-level community or social-service study; 15/15.','entry_burden_basis','No statutory occupational registration applies to generic Community Worker 411711; 5/5.'),'2026-08-11'),
('NZ:counsellor','2026-08-11',null,46.63,97000,20,0,0,0,10,8,0,10,3,51,'career-opportunity-nz-v1','provisional',jsonb_build_object('classification_scope','Green List-aligned roll-up of ANZSCO 272111 Careers Counsellor, 272113 Family and Marriage Counsellor, 272114 Rehabilitation Counsellor, 272115 Student Counsellor and 272199 Counsellors nec. Drug and Alcohol Counsellor 272112 is excluded because the current Green List treats addiction practice under a separate DAPAANZ registration pathway.','shortage_note','The NZAC-membership counsellor group is on current Green List Tier 1; 20/20.','visa_basis','Tier 1 Straight to Residence when the applicable NZ Association of Counsellors membership and qualification requirements are met; 10/10.','salary_method','Midpoint of Tahatū current most-common Counsellor annual pay range NZD 87,000-107,000; 8/10.','entry_basis','Bachelor-level counselling or another listed professional degree plus the applicable NZAC-accredited pathway is common for Green List eligibility; 10/15.','entry_burden_basis','Counselling is not represented here as a universal statutory-register profession, but Green List access for this roll-up depends on NZAC membership and qualifying study; 3/5.'),'2026-08-11')
on conflict (profile_key,as_of_date) do update set employment_total=excluded.employment_total,median_hourly_earnings=excluded.median_hourly_earnings,annualised_median_salary=excluded.annualised_median_salary,shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('NZ:early-childhood-teacher','241111','Early Childhood (Pre-primary School) Teacher — registered',null,true,true,1,'https://www.immigration.govt.nz/opsmanual/89117.htm','2026-08-11'),
('NZ:primary-school-teacher','241213','Primary School Teacher',null,true,true,1,'https://www.immigration.govt.nz/opsmanual/89117.htm','2026-08-11'),
('NZ:secondary-school-teacher','241411','Secondary School Teacher',null,true,true,1,'https://www.immigration.govt.nz/opsmanual/89117.htm','2026-08-11'),
('NZ:special-education-teacher','241511','Special Needs Teacher',null,true,true,1,'https://www.immigration.govt.nz/opsmanual/89117.htm','2026-08-11'),
('NZ:special-education-teacher','241512','Teacher of the Hearing Impaired',null,true,true,2,'https://www.immigration.govt.nz/opsmanual/89117.htm','2026-08-11'),
('NZ:special-education-teacher','241513','Teacher of the Sight Impaired',null,true,true,3,'https://www.immigration.govt.nz/opsmanual/89117.htm','2026-08-11'),
('NZ:special-education-teacher','241599','Special Education Teachers nec',null,true,true,4,'https://www.immigration.govt.nz/opsmanual/89117.htm','2026-08-11'),
('NZ:social-worker','272511','Social Worker',null,true,true,1,'https://www.immigration.govt.nz/opsmanual/89117.htm','2026-08-11'),
('NZ:youth-worker','411716','Youth Worker',null,true,true,1,'https://www.abs.gov.au/ausstats/abs%40.nsf/Latestproducts/1220.0~2013%2C%2BVersion%2B1.3~Chapter~UNIT%2BGROUP%2B4117%2BWelfare%2BSupport%2BWorkers','2026-08-11'),
('NZ:community-worker','411711','Community Worker',null,true,true,1,'https://www.abs.gov.au/ausstats/abs%40.nsf/Latestproducts/1220.0~2013%2C%2BVersion%2B1.3~Chapter~UNIT%2BGROUP%2B4117%2BWelfare%2BSupport%2BWorkers','2026-08-11'),
('NZ:counsellor','272111','Careers Counsellor',null,true,true,1,'https://www.immigration.govt.nz/opsmanual/89117.htm','2026-08-11'),
('NZ:counsellor','272113','Family and Marriage Counsellor',null,true,true,2,'https://www.immigration.govt.nz/opsmanual/89117.htm','2026-08-11'),
('NZ:counsellor','272114','Rehabilitation Counsellor',null,true,true,3,'https://www.immigration.govt.nz/opsmanual/89117.htm','2026-08-11'),
('NZ:counsellor','272115','Student Counsellor',null,true,true,4,'https://www.immigration.govt.nz/opsmanual/89117.htm','2026-08-11'),
('NZ:counsellor','272199','Counsellors nec',null,true,true,5,'https://www.immigration.govt.nz/opsmanual/89117.htm','2026-08-11')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,shortage_rating=excluded.shortage_rating,visa_eligible=excluded.visa_eligible,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

delete from public.country_occupation_links where profile_key in ('NZ:early-childhood-teacher','NZ:primary-school-teacher','NZ:secondary-school-teacher','NZ:special-education-teacher','NZ:social-worker','NZ:youth-worker','NZ:community-worker','NZ:counsellor');

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,region_code,sort_order,source_checked_at) values
('NZ:early-childhood-teacher','entry_program','Tahatū — Early Childhood Teacher','https://tahatu.govt.nz/work/explore-career-ideas/occupation/T00346-early-childhood-teacher','official_training',null,1,'2026-08-11'),
('NZ:early-childhood-teacher','source','Teaching Council — registration and practising certificate','https://teachingcouncil.nz/index.htm/become-a-teacher/based-in-aotearoa-new-zealand/register-to-teach','official_regulator',null,2,'2026-08-11'),
('NZ:early-childhood-teacher','source','Immigration New Zealand — Green List','https://www.immigration.govt.nz/opsmanual/89117.htm','official_immigration',null,3,'2026-08-11'),
('NZ:primary-school-teacher','entry_program','Tahatū — Primary School Teacher','https://tahatu.govt.nz/work/explore-career-ideas/occupation/T00350-primary-school-teacher','official_training',null,1,'2026-08-11'),
('NZ:primary-school-teacher','source','Teaching Council — registration and practising certificate','https://teachingcouncil.nz/index.htm/become-a-teacher/based-in-aotearoa-new-zealand/register-to-teach','official_regulator',null,2,'2026-08-11'),
('NZ:primary-school-teacher','source','Immigration New Zealand — Green List','https://www.immigration.govt.nz/opsmanual/89117.htm','official_immigration',null,3,'2026-08-11'),
('NZ:secondary-school-teacher','entry_program','Tahatū — Secondary School Teacher','https://tahatu.govt.nz/work/explore-career-ideas/occupation/T00353-secondary-school-teacher','official_training',null,1,'2026-08-11'),
('NZ:secondary-school-teacher','source','Teaching Council — registration and practising certificate','https://teachingcouncil.nz/index.htm/become-a-teacher/based-in-aotearoa-new-zealand/register-to-teach','official_regulator',null,2,'2026-08-11'),
('NZ:secondary-school-teacher','source','Immigration New Zealand — Green List','https://www.immigration.govt.nz/opsmanual/89117.htm','official_immigration',null,3,'2026-08-11'),
('NZ:special-education-teacher','entry_program','Teaching Council — approved ITE programmes (registered-teacher foundation)','https://teachingcouncil.nz/index.php/for-teacher-education-providers/your-ite-programme-toolkit/list-of-approved-ite-programmes','official_training',null,1,'2026-08-11'),
('NZ:special-education-teacher','source','Teaching Council — registration and practising certificate','https://teachingcouncil.nz/index.htm/become-a-teacher/based-in-aotearoa-new-zealand/register-to-teach','official_regulator',null,2,'2026-08-11'),
('NZ:special-education-teacher','source','Immigration New Zealand — Green List','https://www.immigration.govt.nz/opsmanual/89117.htm','official_immigration',null,3,'2026-08-11'),
('NZ:social-worker','entry_program','Tahatū — Social Worker','https://tahatu.govt.nz/work/explore-career-ideas/occupation/T00287-social-worker','official_training',null,1,'2026-08-11'),
('NZ:social-worker','source','Social Workers Registration Board — registration','https://swrb.govt.nz/registration/','official_regulator',null,2,'2026-08-11'),
('NZ:social-worker','source','Social Workers Registration Board — practising certificate','https://swrb.govt.nz/practice/practising-certificate/','official_regulator',null,3,'2026-08-11'),
('NZ:social-worker','source','Immigration New Zealand — Green List','https://www.immigration.govt.nz/opsmanual/89117.htm','official_immigration',null,4,'2026-08-11'),
('NZ:youth-worker','entry_program','Tahatū — Youth Worker','https://tahatu.govt.nz/work/explore-career-ideas/occupation/T01069-youth-worker','official_training',null,1,'2026-08-11'),
('NZ:youth-worker','source','ANZSCO 1.3 — Welfare Support Workers','https://www.abs.gov.au/ausstats/abs%40.nsf/Latestproducts/1220.0~2013%2C%2BVersion%2B1.3~Chapter~UNIT%2BGROUP%2B4117%2BWelfare%2BSupport%2BWorkers','official_classification',null,2,'2026-08-11'),
('NZ:community-worker','entry_program','Tahatū — Support Worker (closest community-support route)','https://tahatu.govt.nz/work/explore-career-ideas/occupation/T00528-support-worker','official_training',null,1,'2026-08-11'),
('NZ:community-worker','source','ANZSCO 1.3 — Welfare Support Workers','https://www.abs.gov.au/ausstats/abs%40.nsf/Latestproducts/1220.0~2013%2C%2BVersion%2B1.3~Chapter~UNIT%2BGROUP%2B4117%2BWelfare%2BSupport%2BWorkers','official_classification',null,2,'2026-08-11'),
('NZ:counsellor','entry_program','Tahatū — Counsellor','https://tahatu.govt.nz/work/explore-career-ideas/occupation/T01051-counsellor','official_training',null,1,'2026-08-11'),
('NZ:counsellor','source','Immigration New Zealand — Green List counsellor scope','https://www.immigration.govt.nz/opsmanual/89117.htm','official_immigration',null,2,'2026-08-11');

delete from public.country_occupation_program_links where profile_key in ('NZ:early-childhood-teacher','NZ:primary-school-teacher','NZ:secondary-school-teacher','NZ:special-education-teacher','NZ:social-worker','NZ:youth-worker','NZ:community-worker','NZ:counsellor') and program_ref like 'nz-program:%';

insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'NZ:' || poc.canonical_career_id,
       'nz-program:' || poc.programme_id::text,
       poc.normalized_relation_type,
       '2026-08-11'::date
from public.program_occupation_canonical_nz_v1 poc
join public.program_catalog_canonical_nz_v1 pc using (programme_id)
where poc.canonical_career_id in ('early-childhood-teacher','primary-school-teacher','secondary-school-teacher','special-education-teacher','social-worker','youth-worker','community-worker','counsellor')
  and pc.verification_tier = 'A'
  and pc.international_students_eligible is true
  and pc.code_signatory_status = 'confirmed'
  and coalesce(pc.canonical_admission_state,'') <> 'closed'
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;;
