-- Japan Health occupation cohort.
-- Classification basis: 2022 revision of the Ministry of Health, Labour and Welfare occupation classification.

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('JP:registered-nurse','JP','registered-nurse','看護師 — workplace-based classification umbrella','MHLW Occupation Classification','2022',null,'JPY',true,'厚生労働省 — 看護師免許','https://www.mhlw.go.jp/web/t_doc?dataId=80078000&dataType=0&pageNo=1','profile_ready','2026-08-10',now()),
('JP:midwife','JP','midwife','助産師','MHLW Occupation Classification','2022','022-02','JPY',true,'厚生労働省 — 助産師免許','https://www.mhlw.go.jp/web/t_doc?dataId=80078000&dataType=0&pageNo=1','profile_ready','2026-08-10',now()),
('JP:care-worker','JP','care-worker','介護職員 — facility/home-care umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:physiotherapist','JP','physiotherapist','理学療法士','MHLW Occupation Classification','2022','024-04','JPY',true,'厚生労働省 — 理学療法士免許','https://www.mhlw.go.jp/web/t_doc?dataId=80038000','profile_ready','2026-08-10',now()),
('JP:medical-laboratory-technician','JP','medical-laboratory-technician','臨床検査技師','MHLW Occupation Classification','2022','024-03','JPY',true,'厚生労働省 — 臨床検査技師免許','https://www.mhlw.go.jp/web/t_doc_keyword?dataId=80018000&dataType=0&keyword=%E8%87%A8%E5%BA%8A%E6%A4%9C%E6%9F%BB%E6%8A%80%E5%B8%AB%E7%AD%89%E3%81%AB%E9%96%A2%E3%81%99%E3%82%8B%E6%B3%95%E5%BE%8B&mode=0&pageNo=1','profile_ready','2026-08-10',now()),
('JP:radiographer','JP','radiographer','診療放射線技師','MHLW Occupation Classification','2022','024-01','JPY',true,'厚生労働省 — 診療放射線技師免許','https://www.mhlw.go.jp/web/t_doc?dataId=80012000','profile_ready','2026-08-10',now()),
('JP:pharmacist','JP','pharmacist','薬剤師','MHLW Occupation Classification','2022','021-04','JPY',true,'厚生労働省 — 薬剤師免許','https://www.mhlw.go.jp/web/t_doc?dataId=81001000','profile_ready','2026-08-10',now()),
('JP:occupational-therapist','JP','occupational-therapist','作業療法士','MHLW Occupation Classification','2022','024-05','JPY',true,'厚生労働省 — 作業療法士免許','https://www.mhlw.go.jp/web/t_doc?dataId=80038000','profile_ready','2026-08-10',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at) values
('JP:registered-nurse','2026-08-10',0,0,0,0,10,0,0,0,1,11,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','The 2022 MHLW classification splits 看護師・准看護師 by workplace under 023-01/02/03/99; the canonical Registered Nurse profile is restricted to 看護師 and therefore does not claim one exact small-classification code.','entry_level_basis','Approved Japanese nursing programmes are retained as direct study pathways, but completion alone is not a nursing licence.','qualification_note','A 看護師 must pass the national examination and obtain the Minister of Health, Labour and Welfare licence.','market_scope','No exact registered-nurse-only recurring comparable market series has been normalised across the workplace codes.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:midwife','2026-08-10',0,0,0,0,8,0,0,0,1,9,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','2022 MHLW 022-02 directly classifies 助産師.','entry_level_basis','Midwifery requires a regulated education and examination pathway; no approved CampCareer Japan programme link is currently published for this canonical career.','qualification_note','A 助産師 must pass both the midwife and nurse national examinations and obtain the ministerial licence.','market_scope','No exact recurring comparable 022-02 labour-market series has been normalised.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:care-worker','2026-08-10',0,0,0,0,15,0,0,0,5,20,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','The canonical Care Worker spans facility care 050-01/02/03/99 and home-care 051-01/02 rather than one exact 2022 MHLW small classification.','entry_level_basis','Facility-care entry can occur without a specific academic credential, while training such as 介護職員初任者研修 and the national 介護福祉士 qualification can strengthen or be required for particular service responsibilities.','qualification_note','介護福祉士 is a protected national title, but the broad care-worker occupation is not universally licensed; home-care service roles can have separate training requirements.','market_scope','Facility and home-care groups are not merged into a fabricated single market series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:physiotherapist','2026-08-10',0,0,0,0,10,0,0,0,1,11,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','2022 MHLW 024-04 directly classifies 理学療法士.','entry_level_basis','An approved Japanese physical-therapy programme is retained as a direct study pathway, subject to the statutory education and national-examination requirements.','qualification_note','A 理学療法士 must pass the national examination and obtain the Minister of Health, Labour and Welfare licence.','market_scope','No exact recurring comparable 024-04 market series is scored.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:medical-laboratory-technician','2026-08-10',0,0,0,0,10,0,0,0,1,11,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','2022 MHLW 024-03 directly classifies 臨床検査技師.','entry_level_basis','An approved Japanese medical-laboratory-science programme is retained as a direct study pathway; programme completion is not itself the professional licence.','qualification_note','Clinical laboratory technologists are licensed under the 臨床検査技師等に関する法律 after the national examination.','market_scope','No exact recurring comparable 024-03 market series is scored.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:radiographer','2026-08-10',0,0,0,0,10,0,0,0,1,11,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','2022 MHLW 024-01 directly classifies 診療放射線技師.','entry_level_basis','An approved Japanese radiological-technology programme is retained as a direct study pathway, subject to the statutory training and examination pathway.','qualification_note','A 診療放射線技師 must pass the national examination and obtain the Minister of Health, Labour and Welfare licence.','market_scope','No exact recurring comparable 024-01 market series is scored.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:pharmacist','2026-08-10',0,0,0,0,8,0,0,0,1,9,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','2022 MHLW 021-04 directly classifies 薬剤師.','entry_level_basis','An approved Japanese pharmacy programme is retained as a direct study pathway, but statutory educational eligibility and the national examination remain decisive.','qualification_note','A 薬剤師 must pass the national examination and obtain the Minister of Health, Labour and Welfare licence.','market_scope','No exact recurring comparable 021-04 market series is scored.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:occupational-therapist','2026-08-10',0,0,0,0,10,0,0,0,1,11,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','2022 MHLW 024-05 directly classifies 作業療法士.','entry_level_basis','An approved Japanese occupational-therapy programme is retained as a direct study pathway, subject to statutory education and national-examination requirements.','qualification_note','A 作業療法士 must pass the national examination and obtain the Minister of Health, Labour and Welfare licence.','market_scope','No exact recurring comparable 024-05 market series is scored.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10')
on conflict (profile_key,as_of_date) do update set shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('JP:registered-nurse','023-01','看護師・准看護師（病院・診療所） — 看護師 scope',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:registered-nurse','023-02','看護師・准看護師（介護施設） — 看護師 scope',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:registered-nurse','023-03','看護師・准看護師（訪問看護） — 看護師 scope',null,null,false,3,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:registered-nurse','023-99','その他の看護師・准看護師 — 看護師 scope',null,null,false,4,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:midwife','022-02','助産師',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:care-worker','050-01','高齢者入所型施設介護員',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:care-worker','050-02','高齢者通所型施設介護員',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:care-worker','050-03','障害者福祉施設介護員',null,null,false,3,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:care-worker','050-99','その他の施設介護の職業',null,null,false,4,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:care-worker','051-01','訪問介護員',null,null,false,5,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:care-worker','051-02','訪問入浴介助員',null,null,false,6,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:physiotherapist','024-04','理学療法士',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:medical-laboratory-technician','024-03','臨床検査技師',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:radiographer','024-01','診療放射線技師',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:pharmacist','021-04','薬剤師',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:occupational-therapist','024-05','作業療法士',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'job_search','Hello Work job search','https://www.hellowork.mhlw.go.jp/kensaku/GECA110010.do','government',10,'2026-08-10' from public.country_occupation_profiles p where p.country_code='JP' and p.canonical_career_id in ('registered-nurse','midwife','care-worker','physiotherapist','medical-laboratory-technician','radiographer','pharmacist','occupational-therapist')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'source','2022 MHLW occupation classification','https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','government',20,'2026-08-10' from public.country_occupation_profiles p where p.country_code='JP' and p.canonical_career_id in ('registered-nurse','midwife','care-worker','physiotherapist','medical-laboratory-technician','radiographer','pharmacist','occupational-therapist')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at) values
('JP:registered-nurse','source','Nurse licensing law','https://www.mhlw.go.jp/web/t_doc?dataId=80078000&dataType=0&pageNo=1','government',30,'2026-08-10'),
('JP:midwife','source','Midwife licensing law','https://www.mhlw.go.jp/web/t_doc?dataId=80078000&dataType=0&pageNo=1','government',30,'2026-08-10'),
('JP:care-worker','source','MHLW care-worker training overview','https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000054119.html','government',30,'2026-08-10'),
('JP:care-worker','source','MHLW job tag — facility care worker','https://shigoto.mhlw.go.jp/User/Occupation/Detail/134','government',31,'2026-08-10'),
('JP:physiotherapist','source','Physical and occupational therapist licensing law','https://www.mhlw.go.jp/web/t_doc?dataId=80038000','government',30,'2026-08-10'),
('JP:medical-laboratory-technician','source','Clinical laboratory technologist licensing law','https://www.mhlw.go.jp/web/t_doc_keyword?dataId=80018000&dataType=0&keyword=%E8%87%A8%E5%BA%8A%E6%A4%9C%E6%9F%BB%E6%8A%80%E5%B8%AB%E7%AD%89%E3%81%AB%E9%96%A2%E3%81%99%E3%82%8B%E6%B3%95%E5%BE%8B&mode=0&pageNo=1','government',30,'2026-08-10'),
('JP:radiographer','source','Radiological technologist licensing law','https://www.mhlw.go.jp/web/t_doc?dataId=80012000','government',30,'2026-08-10'),
('JP:pharmacist','source','Pharmacist Act','https://www.mhlw.go.jp/web/t_doc?dataId=81001000','government',30,'2026-08-10'),
('JP:occupational-therapist','source','Physical and occupational therapist licensing law','https://www.mhlw.go.jp/web/t_doc?dataId=80038000','government',30,'2026-08-10')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'JP:'||o.canonical_career_id,c.source_program_key,case when o.relation_type='direct' then 'direct' else 'related' end,coalesce(o.source_checked_at,'2026-08-10'::date)
from public.program_occupation_jp_staging o
join public.program_catalog_jp_staging c on c.id=o.program_catalog_id
where o.review_status='approved'
  and o.canonical_career_id in ('registered-nurse','midwife','care-worker','physiotherapist','medical-laboratory-technician','radiographer','pharmacist','occupational-therapist')
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;;
