-- Japan Environment / Agriculture occupation cohort.
-- Classification basis: 2022 revision of the Ministry of Health, Labour and Welfare occupation classification.

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('JP:environmental-scientist','JP','environmental-scientist','環境科学者 — research/environmental-investigation umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:agronomist','JP','agronomist','農業技術者 — agronomy/advisory scope','MHLW Occupation Classification','2022','005-01','JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:farm-manager','JP','farm-manager','農場管理者 — production-type farm-management umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:forestry-technician','JP','forestry-technician','林業技術者 — forestry technical scope','MHLW Occupation Classification','2022','005-01','JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:food-technologist','JP','food-technologist','食品技術者 — development/manufacturing umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:sustainability-specialist','JP','sustainability-specialist','サステナビリティ専門職 — environmental/planning umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:horticulturist','JP','horticulturist','園芸職 — crop/nursery/landscape umbrella','MHLW Occupation Classification','2022',null,'JPY',false,null,null,'profile_ready','2026-08-10',now()),
('JP:animal-science-technician','JP','animal-science-technician','畜産技術者 — animal-science technical scope','MHLW Occupation Classification','2022','005-01','JPY',false,null,null,'profile_ready','2026-08-10',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at) values
('JP:environmental-scientist','2026-08-10',0,0,0,0,10,0,0,0,5,15,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','Environmental Scientist spans natural-science research under 004-01 and environmental investigation/measurement under 011-99 rather than one exact MHLW small-classification code.','entry_level_basis','Environmental science, earth science and related natural-science study are common foundations; four approved Japanese programmes are retained as direct academic pathways.','qualification_note','No universal statutory licence covers the full Environmental Scientist occupation. Narrower regulated measurement work can require credentials such as 作業環境測定士 or 環境計量士.','market_scope','Research and environmental-investigation market data are not merged into one fabricated exact series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:agronomist','2026-08-10',0,0,0,0,12,0,0,0,5,17,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','MHLW 005-01 explicitly includes 農業技術者 and agricultural extension/advisory work covering crops, soils, fertilisers, pests and farm management.','entry_level_basis','Agricultural science, agronomy and related bioscience programmes are common academic foundations; six reviewed Japanese mappings are retained as related pathways rather than occupational qualification.','qualification_note','No universal personal Agronomist licence applies across the canonical role. Public extension or specialist duties can have separate recruitment or appointment requirements.','market_scope','The 005-01 group also contains forestry, livestock and fisheries technicians, so group-level market statistics are not treated as exact Agronomist observations.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:farm-manager','2026-08-10',0,0,0,0,15,0,0,0,5,20,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','Japan classifies agricultural production work by production type under 064 rather than publishing one generic Farm Manager small-classification code.','entry_level_basis','Farm management can be reached through agricultural study plus substantial practical production and business experience; six reviewed programmes are retained as related study pathways.','qualification_note','No universal Farm Manager licence applies. Specific pesticide use, machinery, livestock, biosecurity or regulated production duties can carry separate requirements.','market_scope','Crop and livestock production classifications are preserved separately instead of aggregating them into a fabricated generic farm-manager labour series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:forestry-technician','2026-08-10',0,0,0,0,12,0,0,0,5,17,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','MHLW 005-01 explicitly includes 林業技術者 covering forest regeneration, protection, utilisation and extension guidance.','entry_level_basis','Forestry, forest science and related agricultural study are common foundations; the reviewed Japanese forest-science programme is retained as related rather than automatic occupational qualification.','qualification_note','No universal personal Forestry Technician licence applies. Relevant credentials such as forestry extension, 技術士, surveying or forestry-skills qualifications can matter for particular roles.','market_scope','005-01 combines agriculture, forestry, livestock and fisheries technical work, so shared statistics are not treated as exact Forestry Technician market values.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:food-technologist','2026-08-10',0,0,0,0,12,0,0,0,5,17,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','Food Technologist spans MHLW 006-01 食品開発技術者 and 007-01 食品製造技術者, separating product development from manufacturing/process/quality engineering.','entry_level_basis','Food science, applied bioscience and related agricultural programmes can lead into the field; two reviewed Japanese programmes are retained as related pathways.','qualification_note','There is no universal personal Food Technologist licence. Particular factories, food-safety functions and statutory hygiene roles can have separate qualification requirements.','market_scope','Development and manufacturing technology are kept separate; their labour data are not merged into a fabricated exact Food Technologist series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:sustainability-specialist','2026-08-10',0,0,0,0,10,0,0,0,5,15,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','MHLW does not publish one standalone Sustainability Specialist code. Corporate sustainability work can overlap planning/analysis, environmental technical work and consulting depending on duties.','entry_level_basis','Environmental science, engineering, economics, policy and sustainability programmes are relevant; eleven reviewed Japanese programmes are retained as related pathways.','qualification_note','No universal statutory Sustainability Specialist licence applies. Narrow environmental measurement, engineering or consulting responsibilities may carry separate credentials.','market_scope','CampCareer does not substitute environmental-investigation or corporate-planning group data for an exact sustainability-specialist market series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:horticulturist','2026-08-10',0,0,0,0,15,0,0,0,5,20,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','The broad Horticulturist career spans crop cultivation under 064-02 and plant/nursery/landscape work including 064-05 rather than one exact Japanese code.','entry_level_basis','Horticulture can be entered through vocational, agricultural-science or practical production routes; six reviewed Japanese agriculture programmes are retained as related pathways.','qualification_note','No universal Horticulturist licence applies. Pesticide, machinery, landscaping-construction or supervisory duties can impose role-specific qualifications or training.','market_scope','Crop-production and landscape occupations are not merged into one fabricated horticulture labour series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('JP:animal-science-technician','2026-08-10',0,0,0,0,12,0,0,0,4,16,'career-opportunity-jp-v1','provisional',jsonb_build_object('classification_scope','MHLW 005-01 explicitly includes 畜産技術者 covering breeding, feeding, pasture, production methods and technical guidance.','entry_level_basis','Animal science, agriculture and bioscience study are common foundations; three reviewed Japanese programmes are retained as related pathways.','qualification_note','No universal Animal Science Technician licence covers the broad role. Specific duties such as 家畜人工授精 require separate statutory qualification, and veterinary acts remain outside this profile.','market_scope','005-01 combines livestock with other agriculture/forestry/fisheries technicians, so its statistics are not treated as exact animal-science-technician values.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10')
on conflict (profile_key,as_of_date) do update set shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('JP:environmental-scientist','004-01','自然科学系研究者 — environmental research scope',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:environmental-scientist','011-99','環境調査員 — environmental investigation/measurement scope',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1&pageNo=3','2026-08-10'),
('JP:agronomist','005-01','農業技術者 — agronomy/advisory scope',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:farm-manager','064-01','稲作・畑作 — production-management reference',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1&pageNo=2','2026-08-10'),
('JP:farm-manager','064-02','農作物栽培・収穫 — production-management reference',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1&pageNo=2','2026-08-10'),
('JP:farm-manager','064-03','家畜・家きん飼育 — production-management reference',null,null,false,3,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1&pageNo=2','2026-08-10'),
('JP:forestry-technician','005-01','林業技術者 — forestry technical scope',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:food-technologist','006-01','食品開発技術者 — product-development scope',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:food-technologist','007-01','食品製造技術者 — process/quality/manufacturing scope',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1&pageNo=2','2026-08-10'),
('JP:sustainability-specialist','011-99','環境技術・調査 scope',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1&pageNo=3','2026-08-10'),
('JP:sustainability-specialist','033-03','企画・調査事務 — corporate planning/analysis reference',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10'),
('JP:horticulturist','064-02','農作物栽培・収穫作業員（稲作・畑作を除く） — horticultural crop scope',null,null,false,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1&pageNo=2','2026-08-10'),
('JP:horticulturist','064-05','植木職、造園師 — nursery/landscape scope',null,null,false,2,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1&pageNo=2','2026-08-10'),
('JP:animal-science-technician','005-01','畜産技術者 — animal-science technical scope',null,null,true,1,'https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','2026-08-10')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'job_search','Hello Work job search','https://www.hellowork.mhlw.go.jp/kensaku/GECA110010.do','government',10,'2026-08-10' from public.country_occupation_profiles p where p.country_code='JP' and p.canonical_career_id in ('environmental-scientist','agronomist','farm-manager','forestry-technician','food-technologist','sustainability-specialist','horticulturist','animal-science-technician')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'source','MHLW 2022 occupation classification','https://www.mhlw.go.jp/web/t_doc?dataId=00tc6704&dataType=1','government',20,'2026-08-10' from public.country_occupation_profiles p where p.country_code='JP' and p.canonical_career_id in ('environmental-scientist','agronomist','farm-manager','forestry-technician','food-technologist','sustainability-specialist','horticulturist','animal-science-technician')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'JP:'||o.canonical_career_id, pc.source_program_key, case when o.relation_type='direct' then 'direct' else 'related' end, '2026-08-10'
from public.program_occupation_jp_staging o
join public.program_catalog_jp_staging pc on pc.id=o.program_catalog_id
where o.review_status='approved'
  and o.canonical_career_id in ('environmental-scientist','agronomist','farm-manager','forestry-technician','food-technologist','sustainability-specialist','horticulturist','animal-science-technician')
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;;
