delete from evidence.metric_observations where scope_type='country' and scope_id='SE' and metric_key in ('full_time_annual_earnings_range','average_annual_salary','student_living_cost_monthly_range','national_minimum_hourly_wage','tuition_annual_low','tuition_annual_high','visa_application_fee','student_work_hours_limit');
with snapshots as (
  select distinct on (s.source_key) s.source_key, ss.id snapshot_id from evidence.sources s join evidence.source_snapshots ss on ss.source_id=s.id
  where s.source_key in ('cc_se_scb_salary_2025','cc_se_migration_study_2026','cc_se_study_sweden_fees_2026','cc_se_employment_minimum_wage')
  order by s.source_key, ss.retrieved_at desc, ss.created_at desc
), rows_to_insert as (
  select 'full_time_annual_earnings_range'::text metric_key, jsonb_build_object('low',384000,'high',576000,'ranking_value',459600,'currency','SEK','basis','national_lower_to_upper_quartile_monthly_salary_annualised','measure_type','quartile_distribution','monthly_lower_quartile',32000,'monthly_median',38300,'monthly_upper_quartile',48000) value, 'SEK/year'::text unit, 'cc_se_scb_salary_2025'::text source_key, 'calculated'::text evidence_kind, 'high'::text confidence, 'SCB monthly quartiles and median are multiplied by twelve.'::text methodology, '{}'::jsonb assumptions, date '2025-12-31' effective_from
  union all select 'average_annual_salary', jsonb_build_object('amount',514800,'currency','SEK','basis','annualised_average_monthly_salary_all_sectors','monthly_amount',42900,'statistic_type','mean'), 'SEK/year','cc_se_scb_salary_2025','calculated','high','SCB average monthly salary is multiplied by twelve.','{}'::jsonb,date '2025-12-31'
  union all select 'student_living_cost_monthly_range', jsonb_build_object('low',10656,'high',12000,'ranking_value',10656,'currency','SEK','basis','2026_national_maintenance_requirement_to_stockholm_university_budget','scenario','one higher-education student; tuition excluded','stockholm_budget_source','https://www.su.se/english/education/new-in-sweden/living-costs'), 'SEK/month','cc_se_migration_study_2026','calculated','medium','Combines the national permit finance floor with Stockholm University current planning guidance.','{}'::jsonb,date '2026-06-11'
  union all select 'national_minimum_hourly_wage', jsonb_build_object('amount',null,'currency','SEK','basis','no_statutory_national_minimum_wage','not_applicable',true,'collective_bargaining_primary',true), 'SEK/hour','cc_se_employment_minimum_wage','observed','high','Sweden has no minimum-wage law; no universal hourly amount is inferred.','{}'::jsonb,date '2026-08-06'
  union all select 'tuition_annual_low', jsonb_build_object('amount',80000,'currency','SEK','basis','official_international_tuition_planning_range','student_type','non-EU/EEA/Swiss fee-liable student','published_average',129000), 'SEK/year','cc_se_study_sweden_fees_2026','observed','medium','Official national planning lower bound.','{}'::jsonb,date '2026-08-06'
  union all select 'tuition_annual_high', jsonb_build_object('amount',295000,'currency','SEK','basis','official_international_tuition_planning_range','student_type','non-EU/EEA/Swiss fee-liable student','published_average',129000), 'SEK/year','cc_se_study_sweden_fees_2026','observed','medium','Official national planning upper bound.','{}'::jsonb,date '2026-08-06'
  union all select 'visa_application_fee', jsonb_build_object('amount',1500,'currency','SEK','basis','adult_higher_education_residence_permit_fee','visa_type','residence permit for higher education','under_18_fee',750,'exemptions_apply',true), 'SEK','cc_se_migration_study_2026','observed','high','Stores the standard adult higher-education residence-permit application fee.','{}'::jsonb,date '2026-06-11'
  union all select 'student_work_hours_limit', jsonb_build_object('hours',15,'period','week','effective_date','2026-06-11','applies_to','bachelor_master_permits_granted_on_or_after_effective_date','summer_months_unrestricted',jsonb_build_array('June','July','August'),'exceptions_exist',true), 'hours/week','cc_se_migration_study_2026','observed','high','Stores the semester maximum introduced for covered permits from 11 June 2026.','{}'::jsonb,date '2026-06-11'
)
insert into evidence.metric_observations (metric_key,scope_type,scope_id,value,unit,source_snapshot_id,evidence_kind,confidence,methodology,assumptions,effective_from,review_status,reviewed_at,reviewer_note,updated_at)
select r.metric_key,'country','SE',r.value,r.unit,s.snapshot_id,r.evidence_kind,r.confidence,r.methodology,r.assumptions,r.effective_from,'verified',now(),'Official Sweden country metric standardisation for CampCareer batch 3.',now() from rows_to_insert r join snapshots s on s.source_key=r.source_key;;
