-- Australia Project Manager profile.
-- Canonical Project Manager has no single cross-industry six-digit OSCA occupation.
-- OSCA 511231 Program or Project Administrator is used only as the closest non-sector proxy.
-- Sector-specific OSCA 113232 ICT Project Manager and 131131 Construction Project Manager remain separate and are intentionally excluded.

update ingest.occupations_au
set shortage_rating = null,
    on_csol = true,
    median_salary_aud = null,
    confidence = 'official-profile-osl-csol-proxy',
    source_name = 'ABS OSCA 2024 v1.0 + JSA occupation profile/2025 OSL + current skilled occupation instruments; related proxy for canonical Project Manager',
    source_url = 'https://www.abs.gov.au/statistics/classifications/osca-occupation-standard-classification-australia/2024-version-1-0/browse-classification/5/51/511/5112/511231',
    last_verified = '2026-08-09',
    anzsco_v13 = '511112'
where anzsco_code = '511231' and occupation_en = 'Program or Project Administrator';

update ingest.visa_occupation_status_au
set reviewed_at = now(), reviewer_note = 'Reviewed OSCA 511231 correspondence to ANZSCO 511112 Program or Project Administrator. Current migration instruments list 511112 with VETASSESS. This is only a related proxy for CampCareer canonical Project Manager: VETASSESS excludes generalist management roles not concerned with administration of a particular program or project.'
where osca_code = '511231' and anzsco_v13_code = '511112' and list_name = 'Core Skills Occupation List (CSOL)' and status = 'eligible';

update public.courses_au set official_course_url='https://bond.edu.au/program/bachelor-of-project-management',official_url_status='verified',official_url_checked_at=now(),official_url_source='Provider current course page, verified 2026-08-09' where institution_id='bond-university' and course_code='0101294';
update public.courses_au set official_course_url='https://bond.edu.au/program/master-of-project-management',official_url_status='verified',official_url_checked_at=now(),official_url_source='Provider current course page, verified 2026-08-09' where institution_id='bond-university' and course_code='078813G';

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at)
values ('AU:project-manager','AU','project-manager','Project Manager — related proxy: Program or Project Administrator','OSCA','2024 v1.0','5112','AUD',false,'No universal statutory registration; VETASSESS assesses ANZSCO 511112 Program or Project Administrator when duties fit that nominated occupation','https://www.vetassess.com.au/check-my-occupation/professional-occupations/program-or-project-administrator','profile_ready','2026-08-09',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,employment_total,median_weekly_earnings,median_hourly_earnings,annualised_median_salary,all_occupations_median_weekly,part_time_share_pct,female_share_pct,median_age,average_full_time_hours,vacancies_three_month_avg,vacancy_period,vacancy_yoy_pct,employment_growth_5y_pct,employment_growth_10y_pct,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at)
values ('AU:project-manager','2026-05-01',null,null,null,null,1852,null,null,null,null,2107.33333,'2026-05-01',1.01,9.54,17.33,0,0,5,0,10,0,5,5,5,30,'career-opportunity-v1','provisional',jsonb_build_object(
'mapping_relation','related_proxy',
'current_classification_scope','Current OSCA has no single cross-industry six-digit Project Manager occupation. Sector-specific project managers are classified separately, including OSCA 113232 ICT Project Manager and 131131 Construction Project Manager. CampCareer uses OSCA 511231 Program or Project Administrator only as the closest non-sector project-delivery proxy and does not present it as an exact canonical title match.',
'proxy_511231_context',jsonb_build_object('legacy_anzsco_code','511112','legacy_employment_total',103200,'legacy_part_time_share_pct',20,'legacy_female_share_pct',59,'legacy_median_age',42,'legacy_average_full_time_hours',42,'data_as_at','2026-02-01','scope','JSA six-digit ANZSCO 511112 Program and Project Administrators; a related proxy, not exact generic Project Manager employment'),
'broader_anzsco_5111_context',jsonb_build_object('employment_total',158500,'median_weekly_earnings_aud',2130,'median_hourly_earnings_aud',59,'part_time_share_pct',11,'female_share_pct',57,'median_age',43,'average_full_time_hours',42,'scope','ANZSCO 5111 Contract, Program and Project Administrators; broader than the 511112 proxy and generic Project Manager career'),
'employment_scope','Because 511231/511112 is only a related proxy for generic Project Manager, its 103,200-worker JSA profile is retained as context and primary employment/demographic fields remain null.',
'earnings_scope','JSA does not publish six-digit median earnings for 511112. Broader ANZSCO 5111 median earnings of A$2,130 per week and A$59 per hour are contextual only, so salary receives zero points.',
'vacancy_scope','The May 2026 IVI three-month-average value of 2,107.33333 is broader ANZSCO 5111, versus 2,086.33333 in May 2025, about +1.01% year on year. Because both the career mapping and vacancy series are broader/proxy observations, vacancy intensity and trend receive zero points.',
'projection_scope','JSA broader ANZSCO 5111 projections are +9.54% from May 2025 to May 2030 and +17.33% to May 2035. Only partial growth credit is assigned because the series is broader and the canonical mapping is not exact.',
'shortage_note','The reviewed JSA 2025 OSL records OSCA 511231 Program or Project Administrator as No Shortage nationally. The generic Project Manager canonical career receives no shortage credit, and region-level shortage remains null because the official occupation is only a proxy.',
'visa_basis','Current migration instruments list ANZSCO 511112 Program or Project Administrator with VETASSESS. VETASSESS classifies it as Group C and requires an AQF Diploma or higher plus relevant employment under the applicable pathway. Only partial visa credit is assigned because a Project Manager title alone does not establish that the duties match 511112; generalist management roles are explicitly outside the VETASSESS occupation scope.',
'registration_basis','There is no universal statutory registration for cross-industry Project Managers. Sector-specific roles can have separate licensing or professional requirements, which are outside this non-sector proxy profile.',
'entry_level_basis','Bond University Bachelor of Project Management, CRICOS 0101294, provides a direct project-management degree and its Master of Project Management, CRICOS 078813G, provides a postgraduate route. Entry credit is moderated because the canonical Project Manager role commonly depends on practical delivery experience even though the 511112 proxy has a Diploma-level minimum assessment threshold.',
'entry_burden_basis','The 511112 proxy is VETASSESS Group C and has no statutory licence, but migration assessment requires relevant qualification and employment evidence. The score therefore gives a moderate low-burden bonus rather than treating the career as immediately accessible from study alone.',
'employer_diversity_basis','Curated employer coverage spans professional services, finance, resources, telecommunications and retail; replace with posting-level unique-employer counts when available.',
'score_note','Project Manager is scored conservatively because Australia has no exact cross-industry OSCA mapping. No shortage, salary, vacancy-intensity or vacancy-trend points are assigned. Broader long-run growth receives partial credit, direct study routes receive moderated entry credit, and the 511112 CSOL/VETASSESS pathway receives partial visa credit only.'),'2026-08-09')
on conflict (profile_key,as_of_date) do update set employment_total=excluded.employment_total,median_weekly_earnings=excluded.median_weekly_earnings,median_hourly_earnings=excluded.median_hourly_earnings,annualised_median_salary=excluded.annualised_median_salary,all_occupations_median_weekly=excluded.all_occupations_median_weekly,part_time_share_pct=excluded.part_time_share_pct,female_share_pct=excluded.female_share_pct,median_age=excluded.median_age,average_full_time_hours=excluded.average_full_time_hours,vacancies_three_month_avg=excluded.vacancies_three_month_avg,vacancy_period=excluded.vacancy_period,vacancy_yoy_pct=excluded.vacancy_yoy_pct,employment_growth_5y_pct=excluded.employment_growth_5y_pct,employment_growth_10y_pct=excluded.employment_growth_10y_pct,shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,legacy_code_system,legacy_code_version,legacy_code,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at)
values ('AU:project-manager','511231','Program or Project Administrator — related proxy for Project Manager','ANZSCO','2013 v1.3','511112',null,true,true,1,'https://www.abs.gov.au/statistics/classifications/osca-occupation-standard-classification-australia/2024-version-1-0/browse-classification/5/51/511/5112/511231','2026-08-09')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,legacy_code_system=excluded.legacy_code_system,legacy_code_version=excluded.legacy_code_version,legacy_code=excluded.legacy_code,shortage_rating=excluded.shortage_rating,visa_eligible=excluded.visa_eligible,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_region_metrics (profile_key,region_code,as_of_date,shortage_rating,vacancy_count,source_url) values
('AU:project-manager','ACT','2026-05-01',null,67.66667,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:project-manager','NSW','2026-05-01',null,572,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:project-manager','NT','2026-05-01',null,36,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:project-manager','QLD','2026-05-01',null,492,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:project-manager','SA','2026-05-01',null,140.66667,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:project-manager','TAS','2026-05-01',null,18,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:project-manager','VIC','2026-05-01',null,456.33333,'https://www.jobsandskills.gov.au/data/internet-vacancy-index'),('AU:project-manager','WA','2026-05-01',null,324.66667,'https://www.jobsandskills.gov.au/data/internet-vacancy-index')
on conflict (profile_key,region_code,as_of_date) do update set shortage_rating=excluded.shortage_rating,vacancy_count=excluded.vacancy_count,source_url=excluded.source_url;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,region_code,sort_order,source_checked_at) values
('AU:project-manager','job_search','SEEK — Project Manager jobs','https://www.seek.com.au/project-manager-jobs','private_job_board',null,1,'2026-08-09'),
('AU:project-manager','job_search','Workforce Australia — Project Manager search','https://www.workforceaustralia.gov.au/individuals/jobs/search?searchText=project%20manager','government_job_board',null,2,'2026-08-09'),
('AU:project-manager','employer','Deloitte Australia — Careers','https://www.deloitte.com/au/en/careers.html','professional_services',null,1,'2026-08-09'),
('AU:project-manager','employer','Commonwealth Bank — Careers','https://www.commbank.com.au/about-us/careers.html','financial_services',null,2,'2026-08-09'),
('AU:project-manager','employer','BHP — Careers','https://www.bhp.com/careers','resources',null,3,'2026-08-09'),
('AU:project-manager','employer','Telstra — Careers','https://www.telstra.com.au/careers','telecommunications',null,4,'2026-08-09'),
('AU:project-manager','employer','Woolworths Group — Careers','https://www.wowcareers.com.au/','retail',null,5,'2026-08-09'),
('AU:project-manager','entry_program','VETASSESS — Program or Project Administrator skills assessment','https://www.vetassess.com.au/check-my-occupation/professional-occupations/program-or-project-administrator','official_skills_assessment',null,1,'2026-08-09'),
('AU:project-manager','entry_program','Bond — Bachelor of Project Management','https://bond.edu.au/program/bachelor-of-project-management','university_program',null,2,'2026-08-09'),
('AU:project-manager','entry_program','Bond — Master of Project Management','https://bond.edu.au/program/master-of-project-management','university_program',null,3,'2026-08-09'),
('AU:project-manager','source','ABS OSCA — Program or Project Administrator 511231','https://www.abs.gov.au/statistics/classifications/osca-occupation-standard-classification-australia/2024-version-1-0/browse-classification/5/51/511/5112/511231','official_classification',null,1,'2026-08-09'),
('AU:project-manager','source','ABS OSCA — ICT Project Manager 113232','https://www.abs.gov.au/statistics/classifications/osca-occupation-standard-classification-australia/2024-version-1-0/browse-classification/1/11/113/1132/113232','official_classification',null,2,'2026-08-09'),
('AU:project-manager','source','ABS OSCA — Construction Project Manager 131131','https://www.abs.gov.au/statistics/classifications/osca-occupation-standard-classification-australia/2024-version-1-0/browse-classification/1/13/131/1311/131131','official_classification',null,3,'2026-08-09'),
('AU:project-manager','source','JSA — Program and Project Administrators 511112','https://www.jobsandskills.gov.au/data/occupation-and-industry-profiles/occupations/511112-program-and-project-administrators','official_labour_market',null,4,'2026-08-09'),
('AU:project-manager','source','JSA — Contract, Program and Project Administrators 5111','https://www.jobsandskills.gov.au/data/occupation-and-industry-profiles/occupations/5111-contract-program-and-project-administrators','official_labour_market',null,5,'2026-08-09'),
('AU:project-manager','source','JSA — Internet Vacancy Index','https://www.jobsandskills.gov.au/data/internet-vacancy-index','official_labour_market',null,6,'2026-08-09'),
('AU:project-manager','source','JSA — Employment Projections','https://www.jobsandskills.gov.au/data/employment-projections','official_labour_market',null,7,'2026-08-09'),
('AU:project-manager','source','JSA — 2025 Occupation Shortage List','https://www.jobsandskills.gov.au/data/occupation-shortage','official_shortage',null,8,'2026-08-09'),
('AU:project-manager','source','VETASSESS — Program or Project Administrator 511112','https://www.vetassess.com.au/check-my-occupation/professional-occupations/program-or-project-administrator','official_skills_assessment',null,9,'2026-08-09')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,region_code=excluded.region_code,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'AU:project-manager',concat('au-program:',id),'direct','2026-08-09' from public.courses_au where institution_id='bond-university' and course_code='0101294'
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;
insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'AU:project-manager',concat('au-program:',id),'graduate_entry','2026-08-09' from public.courses_au where institution_id='bond-university' and course_code='078813G'
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;;
